//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class VKPolygonDrawStyle, VKVectorTile;

@interface VKPolygonGroup : NSObject
{
    VKPolygonDrawStyle *_cachedPolygonStyle;
    VKVectorTile *_tile;
    float _contentScale;
    struct unique_ptr<ggl::MeshVendor<ggl::Building::BuildingMesh>, std::__1::default_delete<ggl::MeshVendor<ggl::Building::BuildingMesh>>> _extrusionFillMeshVendor;
    struct unique_ptr<ggl::MeshVendor<ggl::PrefilteredLine::PrefilteredLineMesh>, std::__1::default_delete<ggl::MeshVendor<ggl::PrefilteredLine::PrefilteredLineMesh>>> _extrusionStrokeMeshVendor;
    struct unique_ptr<ggl::MeshVendor<ggl::Building::BuildingMesh>, std::__1::default_delete<ggl::MeshVendor<ggl::Building::BuildingMesh>>> _extrusionFillMeshVendorForPointyRoofs;
    struct unique_ptr<ggl::MeshVendor<ggl::PrefilteredLine::PrefilteredLineMesh>, std::__1::default_delete<ggl::MeshVendor<ggl::PrefilteredLine::PrefilteredLineMesh>>> _extrusionStrokeMeshVendorForPointyRoofs;
    struct unique_ptr<ggl::MeshVendor<ggl::BuildingPointyRoof::BuildingMesh>, std::__1::default_delete<ggl::MeshVendor<ggl::BuildingPointyRoof::BuildingMesh>>> _pointyRoofFillMeshVendor;
    struct unique_ptr<ggl::MeshVendor<ggl::PrefilteredLine::PrefilteredLineMesh>, std::__1::default_delete<ggl::MeshVendor<ggl::PrefilteredLine::PrefilteredLineMesh>>> _pointyRoofStrokeMeshVendor;
    unsigned int _cullingMask;
    struct MeshSet<ggl::PolygonBase::MeshMesh, ggl::PolygonBase::DefaultVboVertexElement> _fillMeshInfo;
    struct MeshSet<ggl::PolygonMesh::MeshMesh, ggl::PolygonMesh::DefaultVboVertexElement> _strokeMeshInfo;
    struct MeshSet<ggl::PolygonBase::MeshMesh, ggl::PolygonBase::DefaultVboVertexElement> _fillMeshInfoForPointyRoofs;
    struct unordered_map<std::__1::pair<void *, unsigned long>, std::__1::vector<Edge, std::__1::allocator<Edge>>, std::__1::hash<SectionKey>, std::__1::equal_to<std::__1::pair<void *, unsigned long>>, std::__1::allocator<std::__1::pair<const std::__1::pair<void *, unsigned long>, std::__1::vector<Edge, std::__1::allocator<Edge>>>>> _polygonEdges;
    shared_ptr_6e6219d6 _styleQuery;
    struct vector<ggl::RenderItemBatcher, std::__1::allocator<ggl::RenderItemBatcher>> _fillRenderItemBatchers;
    struct vector<ggl::RenderItemBatcher, std::__1::allocator<ggl::RenderItemBatcher>> _strokeRenderItemBatchers;
    struct vector<std::__1::vector<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>, std::__1::allocator<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>>>, std::__1::allocator<std::__1::vector<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>, std::__1::allocator<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>>>>> _fillCullingGroups;
    struct vector<std::__1::vector<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>, std::__1::allocator<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>>>, std::__1::allocator<std::__1::vector<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>, std::__1::allocator<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>>>>> _strokeCullingGroups;
    struct vector<std::__1::vector<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>, std::__1::allocator<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>>>, std::__1::allocator<std::__1::vector<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>, std::__1::allocator<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>>>>> _extrusionFillCullingGroups;
    struct vector<std::__1::vector<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>, std::__1::allocator<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>>>, std::__1::allocator<std::__1::vector<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>, std::__1::allocator<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>>>>> _extrusionStrokeCullingGroups;
    struct vector<std::__1::vector<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>, std::__1::allocator<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>>>, std::__1::allocator<std::__1::vector<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>, std::__1::allocator<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>>>>> _fillCullingGroupsForPointyRoofs;
    struct vector<std::__1::vector<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>, std::__1::allocator<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>>>, std::__1::allocator<std::__1::vector<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>, std::__1::allocator<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>>>>> _extrusionFillCullingGroupsForPointyRoofs;
    struct vector<std::__1::vector<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>, std::__1::allocator<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>>>, std::__1::allocator<std::__1::vector<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>, std::__1::allocator<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>>>>> _extrusionStrokeCullingGroupsForPointyRoofs;
    struct vector<std::__1::vector<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>, std::__1::allocator<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>>>, std::__1::allocator<std::__1::vector<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>, std::__1::allocator<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>>>>> _pointyRoofFillCullingGroups;
    struct vector<std::__1::vector<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>, std::__1::allocator<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>>>, std::__1::allocator<std::__1::vector<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>, std::__1::allocator<std::__1::vector<ggl::Range, std::__1::allocator<ggl::Range>>>>>> _pointyRoofStrokeCullingGroups;
}

- (id)initWithStyleQuery:(shared_ptr_6e6219d6 *)arg1 tile:(id)arg2 contentScale:(float)arg3;
- (void)addExtrusionForPolygon:(CDStruct_153464bf *)arg1 building:(CDStruct_f5d783cd *)arg2 index:(unsigned int)arg3 ofTotal:(unsigned int)arg4 hasNonWaterStyle:(BOOL)arg5 triangulator:(id)arg6 forRoofStyle:(int)arg7;
- (BOOL)addPointyRoofForPolygon:(CDStruct_153464bf *)arg1 building:(CDStruct_f5d783cd *)arg2 buildingModel:(unsigned char)arg3 scaleThreshold:(float)arg4 styleIndex:(float)arg5;
- (BOOL)canConstructPointyRoofForPolygon:(CDStruct_153464bf *)arg1 building:(CDStruct_f5d783cd *)arg2 buildingModel:(unsigned char)arg3 scaleThreshold:(float)arg4;
- (unsigned char)indexForGeoFeatureAttributes:(id)arg1;
- (void)didFinishAddingData;
- (void)addPolygon:(CDStruct_153464bf *)arg1 building:(CDStruct_f5d783cd *)arg2 index:(unsigned int)arg3 ofTotal:(unsigned int)arg4 hasNonWaterStyle:(BOOL)arg5 accessor:(struct ResourceAccessor *)arg6 triangulator:(id)arg7 prepareExtrusion:(BOOL)arg8 forRoofStyle:(int)arg9 scaleThreshold:(float)arg10;
- (void)willAddDataWithAccessor:(struct ResourceAccessor *)arg1;
- (void)prepareForPolygon:(CDStruct_153464bf *)arg1 building:(CDStruct_f5d783cd *)arg2 hasNonWaterStyle:(BOOL)arg3 forRoofStyle:(int)arg4 scaleThreshold:(float)arg5;
- (void)updateCachedStyle;
@property(readonly, nonatomic) unsigned int cullingMask; // @synthesize cullingMask=_cullingMask;
- (void)addRangesToPointyRoofStrokeRenderItemBatcher:(struct RenderItemBatcher *)arg1 forMeshAtIndex:(unsigned long)arg2 cullingMask:(unsigned int)arg3;
@property(readonly, nonatomic) const MeshVendor_8027e961 *pointyRoofStrokeMeshVendor;
- (void)addRangesToPointyRoofExtrusionStrokeRenderItemBatcher:(struct RenderItemBatcher *)arg1 forMeshAtIndex:(unsigned long)arg2 cullingMask:(unsigned int)arg3;
@property(readonly, nonatomic) const MeshVendor_8027e961 *extrusionStrokeMeshVendorForPointyRoofs;
- (void)addRangesToExtrusionStrokeRenderItemBatcher:(struct RenderItemBatcher *)arg1 forMeshAtIndex:(unsigned long)arg2 cullingMask:(unsigned int)arg3;
@property(readonly, nonatomic) const MeshVendor_8027e961 *extrusionStrokeMeshVendor;
- (void)addRangesToPointyRoofFillRenderItemBatcher:(struct RenderItemBatcher *)arg1 forMeshAtIndex:(unsigned long)arg2 cullingMask:(unsigned int)arg3;
@property(readonly, nonatomic) const MeshVendor_c6d8e5cd *pointyRoofFillMeshVendor;
- (void)addRangesToPointyRoofExtrusionFillRenderItemBatcher:(struct RenderItemBatcher *)arg1 forMeshAtIndex:(unsigned long)arg2 cullingMask:(unsigned int)arg3;
@property(readonly, nonatomic) const MeshVendor_3faa0a72 *extrusionFillMeshVendorForPointyRoofs;
- (void)addRangesToExtrusionFillRenderItemBatcher:(struct RenderItemBatcher *)arg1 forMeshAtIndex:(unsigned long)arg2 cullingMask:(unsigned int)arg3;
@property(readonly, nonatomic) const MeshVendor_3faa0a72 *extrusionFillMeshVendor;
- (void)addRangesToStrokeRenderItemBatcher:(struct RenderItemBatcher *)arg1 forMeshAtIndex:(unsigned long)arg2 cullingMask:(unsigned int)arg3;
@property(readonly, nonatomic) vector_0edf1665 *strokeMeshes;
- (void)addRangesToPointyRoofTopRenderItemBatcher:(struct RenderItemBatcher *)arg1 forMeshAtIndex:(unsigned long)arg2 cullingMask:(unsigned int)arg3;
@property(readonly, nonatomic) vector_54f0f967 *fillMeshesForPointyRoofs;
- (void)addRangesToFillRenderItemBatcher:(struct RenderItemBatcher *)arg1 forMeshAtIndex:(unsigned long)arg2 cullingMask:(unsigned int)arg3;
@property(readonly, nonatomic) vector_54f0f967 *fillMeshes;
@property(readonly, nonatomic) shared_ptr_6e6219d6 *styleQuery; // @synthesize styleQuery=_styleQuery;
- (void).cxx_destruct;
- (id).cxx_construct;
- (void)dealloc;

@end

