//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURL.h"

@interface NSURL (LSAdditions)
- (id)mapsURL;
- (id)iTunesStoreURL;
- (id)iWorkDocumentName;
- (id)iWorkApplicationName;
- (BOOL)conformsToOverridePatternWithKey:(id)arg1;
- (BOOL)isiWorkURL;
- (id)betaStoreURL;
- (id)facebookURL;
- (id)iCloudFamilyURL;
- (id)photosURL;
- (id)fmipURL;
- (id)fmfURL;
- (id)gamecenterURL;
- (id)youTubeURL;
- (id)twitterURL;
@end

