//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CBPeripheral, NSString;

@interface BTLEAccessory : NSObject
{
    CBPeripheral *_peripheral;
    NSString *_name;
    double _lastSeen;
    int _lastRSSI;
}

@property(retain) CBPeripheral *peripheral; // @synthesize peripheral=_peripheral;
@property double lastSeen; // @synthesize lastSeen=_lastSeen;
@property int RSSI; // @synthesize RSSI=_lastRSSI;
- (id)initWithPeripheral:(id)arg1;
@property(copy) NSString *name; // @synthesize name=_name;
- (void)dealloc;

@end

