//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface BluetoothManager : NSObject
{
    struct BTLocalDeviceImpl *_localDevice;
    struct BTSessionImpl *_session;
    int _available;
    BOOL _audioConnected;
    BOOL _scanningEnabled;
    BOOL _scanningInProgress;
    unsigned int _scanningServiceMask;
    struct BTDiscoveryAgentImpl *_discoveryAgent;
    struct BTPairingAgentImpl *_pairingAgent;
    struct BTAccessoryManagerImpl *_accessoryManager;
    NSMutableDictionary *_btAddrDict;
    NSMutableDictionary *_btDeviceDict;
}

+ (int)lastInitError;
+ (void)setSharedInstanceQueue:(id)arg1;
+ (id)sharedInstance;
- (int)powerState;
- (BOOL)isDiscoverable;
- (id)connectingDevices;
- (void)_postNotification:(id)arg1;
- (BOOL)powered;
- (BOOL)available;
- (BOOL)setPowered:(BOOL)arg1;
- (BOOL)connected;
- (void)enableTestMode;
- (void)setAudioConnected:(BOOL)arg1;
- (BOOL)audioConnected;
- (void)_connectabilityChanged;
- (void)_connectedStatusChanged;
- (id)connectedDevices;
- (void)setConnectable:(BOOL)arg1;
- (BOOL)connectable;
- (id)localAddress;
- (void)setDiscoverable:(BOOL)arg1;
- (void)_advertisingChanged;
- (void)_discoveryStateChanged;
- (void)_setScanState:(int)arg1;
- (void)_restartScan;
- (BOOL)deviceScanningInProgress;
- (BOOL)deviceScanningEnabled;
- (BOOL)wasDeviceDiscovered:(id)arg1;
- (void)_removeDevice:(id)arg1;
- (BOOL)isAnyoneAdvertising;
- (BOOL)isAnyoneScanning;
- (void)_powerChanged;
- (void)postNotificationName:(id)arg1 object:(id)arg2 error:(id)arg3;
- (BOOL)_setup:(struct BTSessionImpl *)arg1;
- (BOOL)_onlySensorsConnected;
- (id)addDeviceIfNeeded:(struct BTDeviceImpl *)arg1;
- (BOOL)devicePairingEnabled;
- (void)_scanForServices:(unsigned int)arg1 withMode:(int)arg2;
- (void)_postNotificationWithArray:(id)arg1;
- (BOOL)_attach:(id)arg1;
- (void)endVoiceCommand:(id)arg1;
- (void)startVoiceCommand:(id)arg1;
- (void)unpairDevice:(id)arg1;
- (void)acceptSSP:(int)arg1 forDevice:(id)arg2;
- (void)setPincode:(id)arg1 forDevice:(id)arg2;
- (void)connectDevice:(id)arg1 withServices:(unsigned int)arg2;
- (void)connectDevice:(id)arg1;
- (struct BTAccessoryManagerImpl *)_accessoryManager;
- (BOOL)enabled;
- (void)_cleanup;
- (void)postNotification:(id)arg1;
- (BOOL)setEnabled:(BOOL)arg1;
- (void)postNotificationName:(id)arg1 object:(id)arg2;
- (id)init;
- (void)dealloc;
- (void)cancelPairing;
- (void)scanForServices:(unsigned int)arg1;
- (void)scanForConnectableDevices:(unsigned int)arg1;
- (BOOL)isServiceSupported:(unsigned int)arg1;
- (id)pairedDevices;
- (void)showPowerPrompt;
- (void)resetDeviceScanning;
- (void)setDeviceScanningEnabled:(BOOL)arg1;
- (void)setDevicePairingEnabled:(BOOL)arg1;

@end

