//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface BluetoothDevice : NSObject
{
    NSString *_name;
    NSString *_address;
    struct BTDeviceImpl *_device;
}

- (struct BTDeviceImpl *)device;
- (void)setPIN:(id)arg1;
- (BOOL)paired;
- (unsigned int)connectedServices;
- (id)address;
- (BOOL)connected;
- (void)setSyncGroup:(int)arg1 enabled:(BOOL)arg2;
- (id)syncGroups;
- (void)setSyncSettings:(CDStruct_b2f7276a)arg1;
- (CDStruct_b2f7276a)syncSettings;
- (void)endVoiceCommand;
- (void)startVoiceCommand;
- (void)unpair;
- (void)acceptSSP:(int)arg1;
- (void)connectWithServices:(unsigned int)arg1;
- (void)setServiceSetting:(unsigned int)arg1 key:(id)arg2 value:(id)arg3;
- (id)getServiceSetting:(unsigned int)arg1 key:(id)arg2;
- (BOOL)supportsBatteryLevel;
- (unsigned int)connectedServicesCount;
- (BOOL)cloudPaired;
- (id)scoUID;
- (unsigned int)minorClass;
- (unsigned int)majorClass;
- (BOOL)_isNameCached;
- (void)_clearName;
- (id)initWithDevice:(struct BTDeviceImpl *)arg1 address:(id)arg2;
- (BOOL)isAccessory;
- (void)disconnect;
- (void)connect;
- (int)batteryLevel;
- (int)compare:(id)arg1;
- (id)name;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (int)type;
- (id)description;
- (void)dealloc;
- (void)setDevice:(struct BTDeviceImpl *)arg1;
- (BOOL)isServiceSupported:(unsigned int)arg1;

@end

