//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RKAssets : NSObject
{
}

+ (id)wordIDs;
+ (id)synonyms;
+ (id)constantClasses;
+ (id)negationRegularExpressionPatterns;
+ (id)confirmationRegularExpressionPatterns;
+ (id)appreciationKeywords;
+ (id)alternativeInversions;
+ (id)polarTagKeywords;
+ (id)sensitiveSubjectRegularExpressionPatterns;
+ (id)categoryKeywordMap;
+ (id)stringsFromTable:(id)arg1 forLanguageIdentifier:(id)arg2;
+ (id)fixedPhrases;

@end

