//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ChatKit/CKNanoMediaPresenter.h>

@class UIImageView;

@interface _CKNanoMediaImagePresenter : CKNanoMediaPresenter
{
    UIImageView *_imageView;
}

- (struct CGSize)originalContentSize;
- (void)setZoomed:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)dealloc;

@end

