//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ChatKit/CKAnimatedImageMediaObject.h>

@interface CKAnimatedEmojiMediaObject : CKAnimatedImageMediaObject
{
    BOOL _systemEmoji;
}

+ (BOOL)shouldShadePreview;
+ (BOOL)shouldScaleUpPreview;
+ (id)attachmentSummary:(unsigned int)arg1;
+ (id)UTITypes;
- (id)backgroundColorOverride;
@property(nonatomic, getter=isSystemEmoji) BOOL systemEmoji; // @synthesize systemEmoji=_systemEmoji;
- (id)previewCachesFileURLWithOrientation:(BOOL)arg1 extension:(id)arg2;
- (id)pasteboardItem;
- (id)initWithTransfer:(id)arg1;
- (id)previewForWidth:(float)arg1 orientation:(BOOL)arg2;
- (id)fileURL;
- (id)previewItemTitle;

@end

