//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate;

@interface CKAssistantSMSSend : NSObject
{
    NSDate *_dateSent;
}

- (void)sendSMS:(id)arg1 toAddresses:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)_connectToDaemonIfNeeded;
- (id)errorWithDescription:(id)arg1;

@end

