//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ChatKit/CKChatItem.h>

@class IMHandle, NSDate;

@interface CKBalloonChatItem : CKChatItem
{
    BOOL _isFirstChatItem;
}

- (id)cellIdentifier;
- (BOOL)needsAdjustedTextAlignmentInsets;
- (BOOL)needsPreservedAspectRatio;
@property(nonatomic) BOOL isFirstChatItem; // @synthesize isFirstChatItem=_isFirstChatItem;
- (BOOL)displayDuringSend;
- (id)contactImage;
- (id)loadTranscriptDrawerText;
- (struct CGSize)loadSizeThatFits:(struct CGSize)arg1 textAlignmentInsets:(out struct UIEdgeInsets *)arg2;
- (BOOL)transcriptOrientation;
- (BOOL)wantsDrawerLayout;
- (struct UIEdgeInsets)transcriptTextAlignmentInsets;
@property(readonly, nonatomic) unsigned int balloonCorners;
- (void)configureBalloonView:(id)arg1;
@property(readonly, nonatomic) BOOL failed;
@property(readonly, nonatomic) Class balloonViewClass;
@property(readonly, nonatomic) BOOL balloonOrientation;
@property(readonly, nonatomic, getter=isFromMe) BOOL fromMe;
- (struct UIEdgeInsets)contentInsets;
@property(readonly, retain, nonatomic) IMHandle *sender;
@property(readonly, retain, nonatomic) NSDate *time;
- (Class)cellClass;
- (BOOL)isEditable;
- (id)description;

@end

