//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ChatKit/CKContactMediaObject.h>

#import "MKAnnotation.h"

@class NSString;

@interface CKLocationMediaObject : CKContactMediaObject <MKAnnotation>
{
    CDStruct_2c43369c _coordinate;
}

+ (id)placeholderPreviewForWidth:(float)arg1 orientation:(BOOL)arg2;
+ (id)vcardDataFromCLLocation:(id)arg1;
+ (Class)__ck_attachmentItemClass;
+ (BOOL)isPreviewable;
+ (id)attachmentSummary:(unsigned int)arg1;
+ (id)fallbackFilenamePrefix;
+ (id)titleBarMaskImageForWidth:(float)arg1;
+ (id)placeholderPreviewCache;
+ (id)UTITypes;
@property(nonatomic) CDStruct_2c43369c coordinate; // @synthesize coordinate=_coordinate;
- (int)mediaType;
- (id)mapItem;
- (id)vCardURLProperties;
- (id)generatePlaceholderThumbnailFillToSize:(struct CGSize)arg1 contentAlignmentInsets:(struct UIEdgeInsets)arg2;
- (id)pin;
- (id)generatePlaceholderThumbnailForWidth:(float)arg1 orientation:(BOOL)arg2;
- (BOOL)isDroppedPin;
- (id)bbPreviewFillToSize:(struct CGSize)arg1;
- (Class)previewBalloonViewClass;
- (id)previewCachesFileURLWithOrientation:(BOOL)arg1 extension:(id)arg2;
- (id)previewCacheKeyWithOrientation:(BOOL)arg1;
- (struct CGSize)bbSize;
- (id)generateThumbnailFillToSize:(struct CGSize)arg1 contentAlignmentInsets:(struct UIEdgeInsets)arg2;
- (id)initWithTransfer:(id)arg1;
- (id)previewForWidth:(float)arg1 orientation:(BOOL)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly, copy, nonatomic) NSString *subtitle;
@property(readonly) Class superclass;
@property(readonly, copy, nonatomic) NSString *title;

@end

