//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSDictionary, NSString, NSURL;

@interface CKMediaObject : NSObject
{
    id <CKFileTransfer> _transfer;
}

+ (id)iconCache;
+ (BOOL)shouldShadePreview;
+ (Class)__ck_attachmentItemClass;
+ (BOOL)isPreviewable;
+ (BOOL)shouldScaleUpPreview;
+ (id)attachmentSummary:(unsigned int)arg1;
+ (id)fallbackFilenamePrefix;
+ (id)UTITypes;
@property(readonly, nonatomic) int mediaType;
- (id)fileManager;
@property(readonly, copy, nonatomic) NSString *filename;
- (void)_sampleImageEdges:(id)arg1 usingRect:(struct CGRect)arg2 forMostlyWhitePixels:(unsigned int *)arg3 otherPixels:(unsigned int *)arg4;
- (id)JPEGDataFromImage:(id)arg1;
- (id)downloadProgressString;
- (id)downloadProgressImage;
- (BOOL)shouldShowDisclosure;
@property(readonly, nonatomic) Class _cknmp_mediaPresenterClass;
@property(readonly, nonatomic) NSString *_cknmp_presenterTitle;
- (id)bbPreviewFillToSize:(struct CGSize)arg1;
- (id)fileSizeString;
- (Class)previewBalloonViewClass;
- (void)savePreview:(id)arg1 toURL:(id)arg2 forOrientation:(BOOL)arg3;
- (id)generatePreviewFromThumbnail:(id)arg1 width:(float)arg2 orientation:(BOOL)arg3;
- (id)savedPreviewFromURL:(id)arg1 forOrientation:(BOOL)arg2;
- (id)previewCachesFileURLWithOrientation:(BOOL)arg1 extension:(id)arg2;
- (id)previewDispatchCache;
- (id)previewCacheKeyWithOrientation:(BOOL)arg1;
- (Class)coloredBalloonViewClass;
- (id)icon;
- (id)generateThumbnailForWidth:(float)arg1 orientation:(BOOL)arg2;
- (struct CGSize)bbSize;
- (BOOL)isPreviewable;
- (id)generateThumbnailFillToSize:(struct CGSize)arg1 contentAlignmentInsets:(struct UIEdgeInsets)arg2;
- (id)pasteboardItem;
@property(readonly, copy, nonatomic) NSString *transferGUID;
- (id)initWithTransfer:(id)arg1;
@property(readonly, copy, nonatomic) NSDictionary *transcoderUserInfo;
@property(retain, nonatomic) id <CKFileTransfer> transfer; // @synthesize transfer=_transfer;
@property(readonly, copy, nonatomic) NSString *UTIType;
- (BOOL)shouldBeQuickLooked;
- (BOOL)canExport;
- (BOOL)shouldShowViewer;
- (id)composeImages;
- (Class)balloonViewClassForWidth:(float)arg1 orientation:(BOOL)arg2;
- (void)export:(id)arg1;
- (id)previewForWidth:(float)arg1 orientation:(BOOL)arg2;
@property(readonly, copy, nonatomic) NSURL *fileURL;
- (id)previewItemURL;
@property(readonly, copy, nonatomic) NSString *mimeType;
- (id)location;
- (id)subtitle;
@property(readonly, copy, nonatomic) NSData *data;
- (id)title;
- (id)description;
- (void)dealloc;

@end

