//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PUICSlider.h"

@class NSString, UILabel;

@interface CKNanoTimelineControlsView : PUICSlider
{
    UILabel *_topAccessoryLabel;
    UILabel *_bottomAccessoryLabel;
}

@property(retain, nonatomic) UILabel *bottomAccessoryLabel; // @synthesize bottomAccessoryLabel=_bottomAccessoryLabel;
@property(retain, nonatomic) UILabel *topAccessoryLabel; // @synthesize topAccessoryLabel=_topAccessoryLabel;
@property(copy, nonatomic) NSString *bottomAccessoryText;
@property(copy, nonatomic) NSString *topAccessoryText;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

