//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PUICActionController.h"

@class CKConversation, CKTranscriptController;

@interface CKNanoTranscriptActionController : PUICActionController
{
    CKTranscriptController *_transcriptController;
    CKConversation *_conversation;
}

@property(retain, nonatomic) CKTranscriptController *transcriptController; // @synthesize transcriptController=_transcriptController;
- (void)replyAnimated:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (void)shareCurrentLocation;
- (id)selectContactItemWithImage:(id)arg1 action:(SEL)arg2;
- (void)showContactInfo:(id)arg1;
- (void)reply;
- (void)generateActionItems;
- (id)initInTranscriptController:(id)arg1;
@property(retain, nonatomic) CKConversation *conversation; // @synthesize conversation=_conversation;
- (void)dealloc;

@end

