//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ChatKit/CKTranscriptCell.h>

@class UIButton;

@interface CKNanoButtonCell : CKTranscriptCell
{
    UIButton *_replyButton;
}

+ (float)defaultCellHeight;
@property(retain, nonatomic) UIButton *replyButton; // @synthesize replyButton=_replyButton;
- (void)layoutSubviewsForAlignmentContents;
- (void)configureForChatItem:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

