//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ChatKit/CKNanoSiriObject.h>

@class NSMutableDictionary;

@interface CKNanoSiriRequestHandlerFactory : CKNanoSiriObject
{
    NSMutableDictionary *_registry;
}

+ (id)sharedInstance;
- (void)registerRequestHandlerClass:(Class)arg1;
- (id)requestHandlerForSiriTask:(id)arg1;
- (id)description;
- (id)init;
- (void)dealloc;

@end

