//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

#import "NACVolumeControllerDelegate.h"
#import "NSFileManagerDelegate.h"
#import "PUICCrownInputSequencerDelegate.h"

@class NSString, PUICCrownInputSequencer;

@interface CKNanoVolumeControlView : UIImageView <PUICCrownInputSequencerDelegate, NACVolumeControllerDelegate, NSFileManagerDelegate>
{
    PUICCrownInputSequencer *_crownInputSequencer;
    id <NACVolumeController> _volumeController;
    unsigned int _currentLevel;
}

+ (id)speakerImageForVolumeLevel:(unsigned int)arg1;
+ (unsigned int)volumeLevelFromVolumeValue:(float)arg1;
@property(retain, nonatomic) PUICCrownInputSequencer *crownInputSequencer; // @synthesize crownInputSequencer=_crownInputSequencer;
- (void)crownInputSequencer:(id)arg1 offsetDidReachBoundary:(int)arg2;
- (void)crownInputSequencerOffsetDidChange:(id)arg1;
- (void)volumeControllerDidUpdateVolumeControlAvailibility:(id)arg1;
- (void)volumeControllerDidUpdateVolumeValue:(id)arg1;
@property(nonatomic) unsigned int currentLevel; // @synthesize currentLevel=_currentLevel;
@property(retain, nonatomic) id <NACVolumeController> volumeController; // @synthesize volumeController=_volumeController;
- (void)updateVolumeLevel;
- (BOOL)canBecomeFirstResponder;
- (void)_wheelChangedWithEvent:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

