//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class ALAssetsLibrary, CKDispatchQueue, CKTranscriptController, NSArray, NSCache, NSMutableArray, NSObject<OS_dispatch_group>, NSString, UICollectionView, UITableView, UITapGestureRecognizer, UIView, UIWindow;

@interface CKPhotoPickerSheetViewController : UIViewController <UICollectionViewDataSource, UICollectionViewDelegate, UITableViewDataSource, UITableViewDelegate, UIGestureRecognizerDelegate>
{
    CKTranscriptController *_owner;
    ALAssetsLibrary *_library;
    NSMutableArray *_thumbnails;
    NSCache *_largePhotos;
    NSArray *_assets;
    BOOL _isDesaturated;
    BOOL _largeView;
    BOOL _initialLoadFinished;
    NSObject<OS_dispatch_group> *_loadingGroup;
    BOOL _presented;
    BOOL _presenting;
    NSString *_takePhotoText;
    id <CKCameraSheetViewControllerDelegate> _delegate;
    UIWindow *_window;
    UIView *_bgDimmingView;
    UIView *_sheetView;
    UITableView *_buttonsTableView;
    UICollectionView *_photosCollectionView;
    CKDispatchQueue *_largePhotoQueue;
    UIView *_zoomingView;
    UITapGestureRecognizer *_tapGestureRecognizer;
}

@property(copy, nonatomic) NSString *takePhotoText; // @synthesize takePhotoText=_takePhotoText;
- (void)dismissPhotoPickerSheetWithCompletion:(CDUnknownBlockType)arg1;
- (void)presentPhotoPickerSheetWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithPresentationViewController:(id)arg1;
- (void)_sendSelectedAssets:(BOOL)arg1;
@property(retain, nonatomic) UIView *zoomingView; // @synthesize zoomingView=_zoomingView;
- (id)_thumbnailForIndex:(unsigned int)arg1;
- (void)_beginDesaturation;
@property(nonatomic) BOOL presented; // @synthesize presented=_presented;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(retain, nonatomic) UITableView *buttonsTableView; // @synthesize buttonsTableView=_buttonsTableView;
- (void)_handleTapInMainCollectionView:(id)arg1;
- (float)_heightOfTableView:(id)arg1;
@property(retain, nonatomic) UIView *bgDimmingView; // @synthesize bgDimmingView=_bgDimmingView;
- (void)_cancelPhotoPickerTap;
@property(retain, nonatomic) UICollectionView *photosCollectionView; // @synthesize photosCollectionView=_photosCollectionView;
@property(retain, nonatomic) CKDispatchQueue *largePhotoQueue; // @synthesize largePhotoQueue=_largePhotoQueue;
- (void)_endDesaturation;
- (void)_finishedLoadingAssets;
@property(retain, nonatomic) UIView *sheetView; // @synthesize sheetView=_sheetView;
@property(nonatomic) BOOL presenting; // @synthesize presenting=_presenting;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)loadView;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (int)numberOfSectionsInCollectionView:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (void)collectionView:(id)arg1 didDeselectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)preferredContentSize;
- (BOOL)shouldAutorotate;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
@property(nonatomic) id <CKCameraSheetViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(int)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

