//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ChatKit/CKUIBehaviorNano.h>

@interface CKUIBehaviorNanoNotifications : CKUIBehaviorNano
{
}

- (id)layoutAttributes;
- (float)nanoNoteSenderContentSpace;
- (BOOL)modifiesSingleLineBalloonLayout;
- (BOOL)modifiesFirstBalloonLayout;
- (float)topTranscriptSpace;
- (BOOL)shouldUseRotisserieScrolling;
- (BOOL)showsBalloonChevron;
- (id)transcriptTextFont;
- (float)bottomTranscriptSpace;
- (float)leftBalloonMaxWidthForTranscriptWidth:(float)arg1 marginInsets:(struct UIEdgeInsets)arg2;
- (struct UIEdgeInsets)transcriptMarginInsets;

@end

