//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ChatKit/CKUIBehavior.h>

@interface CKUIBehaviorPad : CKUIBehavior
{
}

- (float)attachmentBrowserGridInterItemSpacing;
- (struct CGSize)attachmentBrowserDefaultSizeForSquare;
- (BOOL)presentsFullscreenInViewService;
- (struct CGSize)documentIconSize;
- (struct UIEdgeInsets)contactPhotoTranscriptInsets;
- (float)leftSplitPaneWidthFraction;
- (float)leftSplitPaneMaximumWidth;
- (float)leftSplitPaneMinimumWidth;
- (BOOL)showMMSSetup;
- (float)transcriptHeaderViewMaxRows;
- (BOOL)presentForwardingUIModally;
- (BOOL)presentsQuickLookController;
- (BOOL)shouldReconfigureNewComposeOnRotation;
- (BOOL)usesCustomSplitViewMasterColumnWidth;
- (BOOL)usesUncollapsedSplitview;
- (float)leftSplitPaneWidthForUIInterfaceOrientation:(int)arg1;
- (BOOL)shouldShowDisclosureChevronInRecipientAtoms;
- (BOOL)presentsReaderController;
- (float)transcriptContactImageDiameter;
- (BOOL)showPendingInConversationList;
- (BOOL)shouldDimTranscript;
- (BOOL)showsConversationListCellChevronImage;
- (BOOL)shouldShowContactPhotosInConversationList;
- (BOOL)shouldSuppressRotationInNewCompose;
- (BOOL)lowClearanceInLandscape;
- (unsigned int)numberOfButtonsInPhotoPicker;
- (float)photoPickerMaxZoomedPhotoHeight;
- (BOOL)photoPickerShouldZoomOnSelection;
- (float)photoPickerPopoverWidth;
- (BOOL)shouldRefreshAlternateAddressesSheet;
- (BOOL)usesPopovers;
- (unsigned int)supportedInterfaceOrientations;

@end

