//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSLocking.h"

@class NSString;

@interface NSCondition : NSObject <NSLocking>
{
    void *_priv;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
- (void)finalize;
- (BOOL)waitUntilDate:(id)arg1;
- (void)signal;
@property(copy) NSString *name;
- (void)unlock;
- (void)lock;
- (id)description;
- (id)init;
- (void)dealloc;
- (void)broadcast;
- (void)wait;

@end

