//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/NSPredicate.h>

@interface NSFalsePredicate : NSPredicate
{
}

+ (void)initialize;
+ (BOOL)supportsSecureCoding;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (BOOL)_allowsEvaluation;
+ (id)defaultInstance;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned int)hash;
- (unsigned int)retainCount;
- (BOOL)isEqual:(id)arg1;
- (id)autorelease;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (oneway void)release;
- (id)retain;
- (BOOL)evaluateWithObject:(id)arg1 substitutionVariables:(id)arg2;
- (void)_validateForMetadataQueryScopes:(id)arg1;
- (id)predicateFormat;
- (void)acceptVisitor:(id)arg1 flags:(unsigned int)arg2;

@end

