//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSProgressPublisher.h"

@class NSDictionary, NSLock, NSMutableDictionary, NSMutableSet, NSString, NSXPCConnection;

@interface NSProgress : NSObject <NSProgressPublisher>
{
    id _group;
    long long _reserved4;
    id _values;
    id _reserved5;
    CDUnknownBlockType _cancellationHandler;
    CDUnknownBlockType _pausingHandler;
    CDUnknownBlockType _prioritizationHandler;
    unsigned long long _flags;
    id _userInfoProxy;
    NSString *_publisherID;
    NSXPCConnection *_connection;
    int _unpublishingBlockageCount;
    int _disconnectingBlockageCount;
    int _remoteObserverCount;
    NSMutableDictionary *_acknowledgementHandlersByBundleID;
    NSMutableDictionary *_lastNotificationTimesByKey;
    NSMutableDictionary *_userInfoLastNotificationTimesByKey;
    NSLock *_lock;
    NSMutableSet *_childrenGroups;
}

+ (id)_addSubscriberForCategory:(id)arg1 usingPublishingHandler:(CDUnknownBlockType)arg2;
+ (void)_removeSubscriber:(id)arg1;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
+ (id)progressWithTotalUnitCount:(long long)arg1;
+ (id)currentProgress;
+ (id)_subscriberInterface;
+ (id)addSubscriberForFileURL:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
+ (void)removeSubscriber:(id)arg1;
+ (id)addSubscriberForFileURL:(id)arg1 withPublishingHandler:(CDUnknownBlockType)arg2;
+ (id)keyPathsForValuesAffectingLocalizedAdditionalDescription;
+ (id)keyPathsForValuesAffectingLocalizedDescription;
+ (id)_addSubscriberForFileURL:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
+ (id)_addSubscriberForFileURL:(id)arg1 withPublishingHandler:(CDUnknownBlockType)arg2;
+ (id)_publisherInterface;
+ (id)_registrarInterface;
@property(readonly, getter=isPaused) BOOL paused;
- (void)setUserInfoObject:(id)arg1 forKey:(id)arg2;
@property(copy) NSString *kind;
- (BOOL)isFinished;
- (void)pause;
@property long long completedUnitCount;
@property long long totalUnitCount;
@property(readonly) double fractionCompleted;
@property(readonly, getter=isIndeterminate) BOOL indeterminate;
@property(copy) NSString *localizedDescription;
@property(readonly, getter=isCancelled) BOOL cancelled;
@property(copy) CDUnknownBlockType cancellationHandler;
@property(readonly, copy) NSDictionary *userInfo;
@property(readonly, copy) NSString *description;
- (id)init;
- (void)dealloc;
- (void)cancel;
- (void)resignCurrent;
- (void)becomeCurrentWithPendingUnitCount:(long long)arg1;
- (void)acknowledge;
- (void)handleAcknowledgementByAppWithBundleIdentifer:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)_setRemoteValue:(id)arg1 forKey:(id)arg2 inUserInfo:(BOOL)arg3;
- (id)_initWithValues:(id)arg1;
- (void)handleAcknowledgementByAppWithBundleIdentifier:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (CDUnknownBlockType)prioritizationHandler;
- (void)setPrioritizationHandler:(CDUnknownBlockType)arg1;
- (BOOL)isPrioritizable;
- (void)setPrioritizable:(BOOL)arg1;
- (id)_publishingAppBundleIdentifier;
@property(readonly, getter=isOld) BOOL old;
- (void)acknowledgeWithSuccess:(BOOL)arg1;
- (CDUnknownBlockType)acknowledgementHandlerForAppBundleIdentifier:(id)arg1;
- (void)setAcknowledgementHandler:(CDUnknownBlockType)arg1 forAppBundleIdentifier:(id)arg2;
- (void)unpublish;
- (void)publish;
@property(copy) CDUnknownBlockType pausingHandler;
@property(getter=isPausable) BOOL pausable;
@property(getter=isCancellable) BOOL cancellable;
@property(copy) NSString *localizedAdditionalDescription;
- (oneway void)appWithBundleID:(id)arg1 didAcknowledgeWithSuccess:(BOOL)arg2;
- (oneway void)stopProvidingValues;
- (oneway void)startProvidingValuesWithInitialAcceptor:(CDUnknownBlockType)arg1;
- (CDUnknownBlockType)_acknowledgementHandlerForAppBundleIdentifier:(id)arg1;
- (void)_setAcknowledgementHandler:(CDUnknownBlockType)arg1 forAppBundleIdentifier:(id)arg2;
- (void)_unpublish;
- (void)_unblockDisconnecting;
- (void)_publish;
- (void)_setUserInfoValue:(id)arg1 forKey:(id)arg2;
- (void)_updateFractionCompletedFromOldFraction:(id)arg1 toNewFraction:(id)arg2;
- (void)_setValueForKeys:(CDUnknownBlockType)arg1 settingBlock:(CDUnknownBlockType)arg2;
- (void)_notifyRemoteObserversOfValueForKey:(id)arg1 inUserInfo:(BOOL)arg2;
- (void)_unblockUnpublishing;
- (void)__notifyRemoteObserversOfValueForKey:(id)arg1 inUserInfo:(BOOL)arg2;
- (void)_addChild:(id)arg1 toGroup:(id)arg2 isPaused:(char *)arg3 isCancelled:(char *)arg4;
- (id)ownedDictionaryObjectForKey:(id)arg1;
- (id)ownedDictionaryKeyEnumerator;
- (unsigned int)ownedDictionaryCount;
- (id)_indentedDescription:(unsigned int)arg1;
- (void)_removeGroup:(id)arg1 fraction:(id)arg2 portion:(long long)arg3;
- (void)_updateGroup:(id)arg1 oldFraction:(id)arg2 newFraction:(id)arg3 portion:(long long)arg4;
- (oneway void)prioritize;
- (void)_setGroup:(id)arg1;
- (void)_setCompletedUnitCount:(long long)arg1 totalUnitCount:(long long)arg2;
- (id)initWithParent:(id)arg1 userInfo:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

