//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface NSThread : NSObject
{
    id _private;
    unsigned char _bytes[44];
}

+ (void)sleepUntilDate:(id)arg1;
+ (void)detachNewThreadSelector:(SEL)arg1 toTarget:(id)arg2 withObject:(id)arg3;
+ (id)callStackSymbols;
+ (id)currentThread;
+ (BOOL)isMainThread;
+ (void)exit;
+ (void)sleepForTimeInterval:(double)arg1;
+ (BOOL)isDying;
+ (BOOL)setThreadPriority:(double)arg1;
+ (double)threadPriority;
+ (id)mainThread;
+ (BOOL)isMultiThreaded;
+ (id)callStackReturnAddresses;
@property(readonly, getter=isExecuting) BOOL executing;
@property(readonly, getter=isFinished) BOOL finished;
- (void)main;
- (id)initWithTarget:(id)arg1 selector:(SEL)arg2 object:(id)arg3;
- (void)start;
@property(readonly, getter=isCancelled) BOOL cancelled;
@property(readonly, retain) NSMutableDictionary *threadDictionary;
@property(copy) NSString *name;
@property(readonly) BOOL isMainThread;
- (id)description;
- (id)init;
- (void)dealloc;
- (void)cancel;
- (void)_nq:(id)arg1;
@property unsigned int stackSize;
- (id)runLoop;
- (BOOL)isDying;
@property int qualityOfService;
@property double threadPriority;

@end

