//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSXPCProxyCreating.h"

@class NSObject<OS_dispatch_queue>, NSString, NSXPCInterface, NSXPCListenerEndpoint;

@interface NSXPCConnection : NSObject <NSXPCProxyCreating>
{
    void *_xconnection;
    id _incomingReplyInfo;
    NSObject<OS_dispatch_queue> *_userQueue;
    unsigned int _state;
    unsigned int _state2;
    CDUnknownBlockType _interruptionHandler;
    CDUnknownBlockType _invalidationHandler;
    id _exportInfo;
    id _replyTable;
    id _importInfo;
    id <NSObject> _otherInfo;
    id _reserved1;
    id _lock;
    NSXPCInterface *_remoteObjectInterface;
    NSString *_serviceName;
    NSXPCListenerEndpoint *_endpoint;
    id _eCache;
    id _dCache;
}

+ (void)endTransaction;
+ (id)currentConnection;
+ (id)_currentBoost;
+ (void)beginTransaction;
- (void)finalize;
- (void)addBarrierBlock:(CDUnknownBlockType)arg1;
- (CDStruct_6ad76789)auditToken;
@property(readonly) int processIdentifier;
- (id)_xpcConnection;
@property(copy) CDUnknownBlockType interruptionHandler;
@property(readonly, retain) NSXPCListenerEndpoint *endpoint;
- (void)stop;
- (id)_queue;
@property(retain) id exportedObject;
@property(retain) NSXPCInterface *exportedInterface;
@property(copy) CDUnknownBlockType invalidationHandler;
- (id)initWithServiceName:(id)arg1;
- (void)_setQueue:(id)arg1;
- (void)setOptions:(unsigned int)arg1;
@property(readonly, retain) id remoteObjectProxy;
- (id)initWithMachServiceName:(id)arg1;
- (id)remoteObjectProxyWithErrorHandler:(CDUnknownBlockType)arg1;
- (void)resume;
@property(retain) NSXPCInterface *remoteObjectInterface; // @synthesize remoteObjectInterface=_remoteObjectInterface;
- (id)initWithMachServiceName:(id)arg1 options:(unsigned int)arg2;
- (void)start;
- (id)userInfo;
- (void)suspend;
- (void)setUserInfo:(id)arg1;
- (void)invalidate;
- (id)delegate;
- (id)description;
- (id)init;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (void)_decodeProgressMessageWithData:(id)arg1;
- (void)_updateProgress:(unsigned long long)arg1 completed:(long long)arg2 total:(long long)arg3;
- (void)_killConnection:(int)arg1;
- (void)_setTargetUserIdentifier:(unsigned int)arg1;
- (void)_setUUID:(id)arg1;
@property(readonly) unsigned int effectiveGroupIdentifier;
@property(readonly) unsigned int effectiveUserIdentifier;
@property(readonly) int auditSessionIdentifier;
- (void)_removeImportedProxy:(unsigned long long)arg1;
- (void)_addImportedProxy:(unsigned long long)arg1;
- (id)remoteObjectProxyWithTimeout:(double)arg1 errorHandler:(CDUnknownBlockType)arg2;
- (id)remoteObjectProxyWithUserInfo:(id)arg1 errorHandler:(CDUnknownBlockType)arg2;
- (void)_addClassToDecodeCache:(Class)arg1;
- (BOOL)_decodeCacheContainsClass:(Class)arg1;
- (void)_addClassToEncodeCache:(Class)arg1;
- (BOOL)_encodeCacheContainsClass:(Class)arg1;
- (id)replacementObjectForEncoder:(id)arg1 object:(id)arg2;
- (id)valueForEntitlement:(id)arg1;
- (id)_exportTable;
@property(readonly, copy) NSString *serviceName;
- (void)_sendInvocation:(id)arg1 proxyNumber:(unsigned long long)arg2 remoteInterface:(id)arg3 withErrorHandler:(CDUnknownBlockType)arg4 timeout:(double)arg5;
- (void)_sendInvocation:(id)arg1 proxyNumber:(unsigned long long)arg2 remoteInterface:(id)arg3 withErrorHandler:(CDUnknownBlockType)arg4;
- (void)_sendInvocation:(id)arg1 proxyNumber:(unsigned long long)arg2 remoteInterface:(id)arg3;
- (id)initWithEndpoint:(id)arg1;
- (id)_initWithPeerConnection:(id)arg1 name:(id)arg2 options:(unsigned int)arg3;
- (void)_decodeAndInvokeMessageWithData:(id)arg1;
- (void)_sendDesistForProxyNumber:(unsigned long long)arg1;
- (void)_decodeAndInvokeReplyBlockWithData:(id)arg1 replyInfo:(id)arg2;
- (void)_pauseProgress:(unsigned long long)arg1;
- (void)_cancelProgress:(unsigned long long)arg1;
- (void)_sendInvocation:(id)arg1 proxyNumber:(unsigned long long)arg2 remoteInterface:(id)arg3 withErrorHandler:(CDUnknownBlockType)arg4 timeout:(double)arg5 userInfo:(id)arg6;
- (id)initWithListenerEndpoint:(id)arg1;
- (id)initWithServiceName:(id)arg1 options:(unsigned int)arg2;
- (id)_errorDescription;

@end

