//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSXPCConnection.h"

@class NSObject<OS_dispatch_queue>, NSXPCInterface, Protocol;

@interface MSXPCConnection : NSXPCConnection
{
    NSObject<OS_dispatch_queue> *_queue;
    NSXPCInterface *_remoteObjectInterface;
    NSXPCInterface *_exportedInterface;
    id _exportedObject;
    CDUnknownBlockType _interruptionHandler;
    CDUnknownBlockType _invalidationHandler;
    Protocol *_protocol;
    NSXPCConnection *_connection;
}

- (void)_sendInvocation:(id)arg1 remoteInterface:(id)arg2 errorHandler:(CDUnknownBlockType)arg3;
- (id)initWithProtocol:(id)arg1;
@property(readonly, retain, nonatomic) Protocol *protocol; // @synthesize protocol=_protocol;
- (int)processIdentifier;
- (void)setInterruptionHandler:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) NSXPCConnection *connection; // @synthesize connection=_connection;
- (void)setExportedObject:(id)arg1;
- (void)setExportedInterface:(id)arg1;
- (void)setInvalidationHandler:(CDUnknownBlockType)arg1;
- (id)remoteObjectProxy;
- (id)remoteObjectProxyWithErrorHandler:(CDUnknownBlockType)arg1;
- (void)resume;
- (void)setRemoteObjectInterface:(id)arg1;
- (id)exportedInterface;
- (void)suspend;
- (void)invalidate;
- (id)description;
- (void)dealloc;
- (id)remoteObjectInterface;
- (unsigned int)effectiveGroupIdentifier;
- (unsigned int)effectiveUserIdentifier;
- (int)auditSessionIdentifier;
- (id)exportedObject;
- (CDUnknownBlockType)invalidationHandler;
- (CDUnknownBlockType)interruptionHandler;

@end

