//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAsset, CLLocation, NSDate, NSObject<OS_dispatch_queue>, NSString, NSURL, PHAdjustmentData, UIImage;

@interface PHContentEditingInput : NSObject
{
    long long _sandboxExtensionHandle;
    NSObject<OS_dispatch_queue> *_avAssetIsolationQueue;
    AVAsset *_avAsset;
    int _mediaType;
    unsigned int _mediaSubtypes;
    NSDate *_creationDate;
    CLLocation *_location;
    NSString *_uniformTypeIdentifier;
    PHAdjustmentData *_adjustmentData;
    UIImage *_displaySizeImage;
    NSURL *_fullSizeImageURL;
    int _fullSizeImageOrientation;
    int _baseVersion;
    NSURL *_videoURL;
}

@property(nonatomic) int baseVersion; // @synthesize baseVersion=_baseVersion;
@property(copy) NSURL *fullSizeImageURL; // @synthesize fullSizeImageURL=_fullSizeImageURL;
@property int mediaType; // @synthesize mediaType=_mediaType;
@property(copy) NSDate *creationDate; // @synthesize creationDate=_creationDate;
@property(retain) PHAdjustmentData *adjustmentData; // @synthesize adjustmentData=_adjustmentData;
@property(copy) NSString *uniformTypeIdentifier; // @synthesize uniformTypeIdentifier=_uniformTypeIdentifier;
@property(copy) CLLocation *location; // @synthesize location=_location;
@property(copy, nonatomic) NSURL *videoURL; // @synthesize videoURL=_videoURL;
- (void).cxx_destruct;
- (id)description;
- (id)init;
- (void)dealloc;
@property(readonly) AVAsset *avAsset; // @synthesize avAsset=_avAsset;
- (id)imagePreview;
- (void)loadFullSizeImageDataWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)_invalidateAVAsset;
@property int fullSizeImageOrientation; // @synthesize fullSizeImageOrientation=_fullSizeImageOrientation;
@property(retain) UIImage *displaySizeImage; // @synthesize displaySizeImage=_displaySizeImage;
- (void)requestFullSizeImageURLWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)consumeSandboxExtensionToken:(id)arg1;
@property unsigned int mediaSubtypes; // @synthesize mediaSubtypes=_mediaSubtypes;
- (BOOL)isMediaSubtype:(unsigned int)arg1;
- (id)audioMix;
- (id)videoComposition;

@end

