//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Photos/PHObject.h>

@class NSString;

@interface PHCollection : PHObject
{
    unsigned int _estimatedPhotosCount;
    unsigned int _estimatedVideosCount;
}

+ (id)fetchMomentsForAssetsWithLocalIdentifiers:(id)arg1 options:(id)arg2;
+ (id)fetchTopLevelUserCollectionsWithOptions:(id)arg1;
+ (id)fetchCollectionsInCollectionList:(id)arg1 options:(id)arg2;
+ (BOOL)managedObjectSupportsTrashedState;
+ (id)_transformValueExpression:(id)arg1 forKeyPath:(id)arg2;
+ (id)entityKeyForPropertyKey:(id)arg1;
+ (id)fetchPredicateFromComparisonPredicate:(id)arg1;
+ (id)managedEntityName;
- (BOOL)canPerformEditOperation:(int)arg1;
@property(readonly, nonatomic) NSString *localizedTitle;
- (id)description;
@property(readonly, nonatomic) BOOL canContainCollections;
@property(readonly, nonatomic) BOOL canContainAssets;
- (BOOL)collectionCanBePinned;
@property(readonly, nonatomic) unsigned int estimatedVideosCount; // @synthesize estimatedVideosCount=_estimatedVideosCount;
@property(readonly, nonatomic) unsigned int estimatedPhotosCount; // @synthesize estimatedPhotosCount=_estimatedPhotosCount;
- (BOOL)collectionHasFixedOrder;

@end

