//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PHPhotoLibraryChangeObserver.h"

@class NSString;

@interface PHImageManager : NSObject <PHPhotoLibraryChangeObserver>
{
    id _cachedDomain;
    unsigned int _managerID;
}

+ (void)initialize;
+ (id)defaultManager;
+ (struct CGSize)sizeOfBestNonFullscreenThumbnailAndContentMode:(int *)arg1;
+ (struct CGSize)fullScreenSizeForScreen:(id)arg1 contentMode:(int *)arg2;
+ (BOOL)useNewImageManager;
+ (struct CGSize)sizeForPLFormat:(int)arg1 fallBackSize:(struct CGSize)arg2 contentMode:(int *)arg3;
- (int)requestImageDataForAsset:(id)arg1 options:(id)arg2 resultHandler:(CDUnknownBlockType)arg3;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
- (id)init;
- (void)dealloc;
- (id)requestAsynchronousVideoURLForImageLoadingAsset:(id)arg1 options:(id)arg2 resultHandler:(CDUnknownBlockType)arg3;
- (id)requestAsynchronousImageForImageLoadingAsset:(id)arg1 targetSize:(struct CGSize)arg2 contentMode:(int)arg3 options:(id)arg4 resultHandler:(CDUnknownBlockType)arg5;
- (void)requestSynchronousImageForImageLoadingAsset:(id)arg1 targetSize:(struct CGSize)arg2 contentMode:(int)arg3 options:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (int)requestAVAssetForVideo:(id)arg1 options:(id)arg2 resultHandler:(CDUnknownBlockType)arg3;
- (int)requestExportSessionForVideo:(id)arg1 options:(id)arg2 exportPreset:(id)arg3 resultHandler:(CDUnknownBlockType)arg4;
- (int)requestPlayerItemForVideo:(id)arg1 options:(id)arg2 resultHandler:(CDUnknownBlockType)arg3;
- (void)cancelImageRequest:(int)arg1;
- (int)requestImageForAsset:(id)arg1 targetSize:(struct CGSize)arg2 contentMode:(int)arg3 options:(id)arg4 resultHandler:(CDUnknownBlockType)arg5;
- (struct CGImage *)newResizedImageForImage:(struct CGImage *)arg1 withSize:(struct CGSize)arg2 normalizedCropRect:(struct CGRect)arg3 contentMode:(int)arg4;
- (void)photoLibraryDidChange:(id)arg1;
- (int)_requestAVAssetForVideo:(id)arg1 options:(id)arg2 resultHandler:(CDUnknownBlockType)arg3;
- (id)requestAsynchronousImageForAsset:(id)arg1 targetSize:(struct CGSize)arg2 contentMode:(int)arg3 options:(id)arg4 resultHandler:(CDUnknownBlockType)arg5;
- (void)requestSynchronousImageForAsset:(id)arg1 targetSize:(struct CGSize)arg2 contentMode:(int)arg3 options:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (id)requestAsynchronousVideoURLForAsset:(id)arg1 options:(id)arg2 resultHandler:(CDUnknownBlockType)arg3;
- (id)_videoAVObjectBuilderFromVideoURL:(id)arg1 info:(id)arg2 playbackOnly:(BOOL)arg3;
- (id)_dictionaryBySettingObject:(id)arg1 forKey:(id)arg2 inDictionary:(id)arg3;
- (void)unregisterRequest:(id)arg1;
- (void)registerRequest:(id)arg1;
- (id)requestAsynchronousVideoURLForAsset:(id)arg1 chainedToMasterRequest:(id)arg2 options:(id)arg3 resultHandler:(CDUnknownBlockType)arg4;
- (id)requestAsynchronousImageForAsset:(id)arg1 chainedToMasterRequest:(id)arg2 targetSize:(struct CGSize)arg3 contentMode:(int)arg4 options:(id)arg5 resultHandler:(CDUnknownBlockType)arg6;
@property(readonly, nonatomic) unsigned int managerID; // @synthesize managerID=_managerID;
- (id)imageForAsset:(id)arg1 targetSize:(struct CGSize)arg2 contentMode:(int)arg3 options:(id)arg4 outInfo:(id *)arg5;
- (id)_domain;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

