//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ImageCapture/ICDevice.h>

@class NSArray, NSString;

@interface ICCameraDevice : ICDevice
{
    void *_cameraProperties;
}

+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
- (void)finalize;
- (void)addToMetadataFetchQ:(id)arg1;
- (void)addToThumbnailFetchQ:(id)arg1;
- (void)removeFolder:(id)arg1;
- (void)requestDownloadFile:(id)arg1 options:(id)arg2 downloadDelegate:(id)arg3 didDownloadSelector:(SEL)arg4 contextInfo:(void *)arg5;
- (void)requestEject;
- (void)requestDeleteFiles:(id)arg1;
- (void)requestSyncClock;
- (id)filesOfType:(id)arg1;
- (void)pendNotifyingDelegateOfAddedItem:(id)arg1;
- (void)notifyDelegateOfAddedItem:(id)arg1;
@property(getter=isEjectable) BOOL ejectable;
- (void)addFolder:(id)arg1;
- (void)incrementNumberOfDownloadableItems;
- (void)incrementEstimatedNumberOfDownloadableItems;
- (void)decrementEstimatedNumberOfDownloadableItems;
- (void)decrementNumberOfDownloadableItems;
- (void)receivedDeviceCommandCompletion;
@property(getter=isAccessRestrictedAppleDevice) BOOL accessRestrictedAppleDevice;
- (id)deviceQSemaphore;
- (id)generalQ;
- (double)downloadCancelTimestamp;
@property unsigned int numberOfDownloadableItems;
@property unsigned int estimatedNumberOfDownloadableItems;
@property(readonly) NSArray *mediaFiles;
@property(readonly) BOOL batteryLevelAvailable;
@property unsigned int contentCatalogPercentCompleted;
@property BOOL allowsSyncingClock;
@property BOOL beingEjected;
@property(copy) NSString *volumePath;
- (void)handleImageCaptureEventNotification:(id)arg1;
- (void)handleCommandCompletionNotification:(id)arg1;
- (void)requestCloseSession;
- (void)requestOpenSession;
- (void)cancelDownload;
@property(readonly) unsigned int batteryLevel;
@property(getter=isLocked) BOOL locked;
@property(readonly) double timeOffset;
@property(readonly) NSArray *contents;
- (id)description;
- (id)init;
- (void)dealloc;

@end

