//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RDGizmoCommands : NSObject
{
}

- (void)disableMusicSync;
- (void)disableCalendarSync;
- (void)disableMessageExpiration;
- (void)stopPlayingDemoMovie;
- (void)resetNotificationCenterIfNecessary;
- (void)startPlayingDemoMovie;
- (void)renewBacklightAssertion;
- (id)getBacklightAssertionQueue;
- (void)resetHeySiri;
- (void)resetFontSizeToDefaultValue;
- (void)resetBrightnessToDefaultValue;
- (void)requestNotificationCenterCleanup;
- (void)resetStopwatch;
- (void)reboot;
- (void)enableSleep;
- (void)disableSleep;

@end

