//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@interface BRiWorkSharingInfo : NSObject <NSSecureCoding, NSCopying>
{
    BOOL _options;
}

+ (BOOL)supportsSecureCoding;
- (id)initWithOptions:(BOOL)arg1;
- (BOOL)isEqualToiWorkSharingInfo:(id)arg1;
- (id)initWithSharingInfo:(id)arg1;
@property(nonatomic) BOOL options; // @synthesize options=_options;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end

