//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

#import "BRNonLocalVersionReceiving.h"

@class GSPermanentStorage, NSError, NSMutableArray, NSMutableDictionary, NSString, NSURL;

@interface BRListNonLocalVersionsOperation : NSOperation <BRNonLocalVersionReceiving>
{
    NSURL *_documentURL;
    NSMutableArray *_versions;
    NSMutableDictionary *_versionsByEtag;
    GSPermanentStorage *_versionsStore;
    id <BRNonLocalVersionSending> _sender;
    BOOL _executing;
    BOOL _finished;
    BOOL _state;
    CDUnknownBlockType _fetchingVersionsDoneBlock;
}

@property(retain, nonatomic) NSError *error;
@property(copy, nonatomic) CDUnknownBlockType fetchingVersionsDoneBlock; // @synthesize fetchingVersionsDoneBlock=_fetchingVersionsDoneBlock;
- (oneway void)newThumbnailForVersionWithEtag:(id)arg1;
- (oneway void)versionsDone;
- (oneway void)newVersionAtURL:(id)arg1 faultURL:(id)arg2 faultExtension:(id)arg3 etag:(id)arg4 hasThumbnail:(BOOL)arg5 lastEditorDeviceName:(id)arg6;
- (BOOL)_setVersionStoreForDocumentAtURL:(id)arg1 error:(id *)arg2;
- (BOOL)_advanceToState:(BOOL)arg1 result:(id)arg2 error:(id)arg3;
@property(nonatomic, getter=isExecuting) BOOL executing; // @synthesize executing=_executing;
- (BOOL)__advanceToState:(BOOL)arg1 result:(id)arg2 error:(id)arg3;
- (BOOL)__finishIfCancelled;
- (void)_senderInvalidate;
@property(nonatomic, getter=isFinished) BOOL finished; // @synthesize finished=_finished;
- (void)start;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (void)cancel;
@property(readonly, nonatomic) NSMutableArray *versions; // @synthesize versions=_versions;
- (id)initWithDocumentURL:(id)arg1;
- (BOOL)isConcurrent;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

