//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (TIExtras)
+ (struct USet *)_nonFullwidthLettersAndNumbersSet;
+ (struct USet *)_fullwidthLettersAndNumbersSet;
+ (struct USet *)_bopomofoToneSet;
+ (struct USet *)_bopomofoSet;
+ (struct USet *)_nonHiraganaKatakanaOrBopomofoSet;
+ (struct USet *)_nonKatakanaOrKanjiSet;
+ (struct USet *)_nonHiraganaOrKatakanaSet;
+ (struct USet *)_hiraganaSet;
+ (struct USet *)_nonJapaneseLetterSet;
+ (struct USet *)_nonIdeographicCharacterSet;
+ (struct USet *)_japaneseLetterSet;
+ (struct USet *)_ideographSet;
+ (struct USet *)_characterSetWithPattern:(id)arg1;
+ (id)stringWithUnichar:(unsigned long)arg1;
+ (id)_stringWithUnichar:(unsigned long)arg1;
- (unsigned int)editDistanceFrom:(id)arg1;
- (BOOL)looksLikeURL;
- (BOOL)looksLikeNumberInput;
- (BOOL)looksLikeEmailAddress;
- (BOOL)isTripledPunctuation;
- (BOOL)isNewlineOrReturn;
- (BOOL)isSpaceOrReturn;
- (BOOL)isSpace;
- (BOOL)isPlainSpace;
- (BOOL)isLeftAssociative;
- (BOOL)endsSentence;
- (id)stringByTrimmingLastCharacter;
- (id)stringByTrimmingCharactersInCFCharacterSet:(struct __CFCharacterSet *)arg1;
- (id)_stringByConvertingFromFullWidthToHalfWidth;
- (id)_stringByConvertingFromHalfWidthToFullWidth;
- (BOOL)_shouldBePaddedWithSpaces;
- (BOOL)_containsFullwidthLettersAndNumbers;
- (BOOL)_containsFullwidthLettersAndNumbersOnly;
- (BOOL)_containsCJKSymbolsAndPunctuation;
- (BOOL)_containsHiraganaKatakanaOrBopomofo;
- (BOOL)_containsKatakanaOrKanji;
- (BOOL)_containsHiraganaOrKatakana;
- (BOOL)_containsHiraganaOnly;
- (BOOL)_isModifierSymbol;
- (unsigned int)_UTF8SizeOfRange:(struct _NSRange)arg1;
- (struct _NSRange)_rangeOfString:(id)arg1 fromLocation:(unsigned int)arg2;
- (void)_enumerateLongCharactersInRange:(struct _NSRange)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (BOOL)_looksLikeURL;
- (BOOL)_looksLikeNumberInput;
- (BOOL)_looksLikeEmailAddress;
- (BOOL)_isSpace;
- (BOOL)_isLeftAssociative;
- (BOOL)_endsSentence;
- (id)_stringByTransliteratingToZhuyin:(BOOL)arg1;
- (id)_stringByTransliteratingToPinyin:(BOOL)arg1;
- (unsigned long)_firstLongCharacter;
- (BOOL)_isTripledPunctuation;
- (BOOL)_containsCJKScriptsOnly;
- (BOOL)isDelete;
- (BOOL)isNaturallyRTL;
- (BOOL)_contentsExclusivelyInCharacterSet:(struct USet *)arg1;
- (BOOL)_containsEmoji;
- (id)_stringByReplacingCharactersInSet:(struct __CFCharacterSet *)arg1 withCharacter:(unsigned long)arg2;
- (BOOL)_containsJapanese;
- (id)_stringByTransliteratingToZhuyin;
- (id)_stringByTranscribingFromLanguage:(id)arg1;
- (BOOL)_containsIdeographicCharacters;
- (unsigned int)_editDistanceFrom:(id)arg1;
- (BOOL)_containsCJScriptsOnly;
- (id)stringByReplacingCharacter:(unsigned long)arg1 withCharacter:(unsigned long)arg2;
- (struct _NSRange)_rangeOfBackwardDeletionClusterAtIndex:(unsigned int)arg1;
- (id)_stringByApplyingTransform:(id)arg1;
- (id)_stringByTranscribingUsingTokenizer:(struct __CFStringTokenizer *)arg1;
- (BOOL)_containsJapaneseOnly;
- (id)_firstGrapheme;
- (BOOL)_isSpaceOrReturn;
- (BOOL)_containsSubstring:(id)arg1;
- (BOOL)containsSubstring:(id)arg1;
- (unsigned short)_firstChar;
- (id)_stringByReplacingCharacter:(unsigned long)arg1 withCharacter:(unsigned long)arg2;
- (BOOL)_containsCJScripts;
- (unsigned int)_graphemeCount;
- (BOOL)_isIdeographicGlyphs;
- (BOOL)_isDelete;
- (BOOL)_isNewlineOrReturn;
- (BOOL)_containsBopomofoToneOnly;
- (BOOL)_containsBopomofoOnly;
- (id)_lastGrapheme;
- (BOOL)_isPlainSpace;
- (BOOL)_isNaturallyRTL;
- (id)_stringByTrimmingCharactersInCFCharacterSet:(struct __CFCharacterSet *)arg1;
- (id)_stringByTrimmingLastCharacter;
- (id)stringByReplacingCharactersInSet:(struct __CFCharacterSet *)arg1 withCharacter:(unsigned long)arg2;
- (id)_stringByTransliteratingToPinyin;
- (id)_stringByTransliteratingToPinyinAsFamilyName;
- (id)_stringByTransliteratingToZhuyinAsFamilyName;
- (BOOL)_isOnlyIdeographs;
@end

