//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@interface TIHandwritingStrokes : NSObject <NSCopying, NSSecureCoding>
{
    struct vector<std::__1::vector<TIHandwritingPoint, std::__1::allocator<TIHandwritingPoint>>, std::__1::allocator<std::__1::vector<TIHandwritingPoint, std::__1::allocator<TIHandwritingPoint>>>> _strokes;
    BOOL _continuePreviousStroke;
}

+ (BOOL)supportsSecureCoding;
- (unsigned int)totalNumberOfPoints;
- (void)removeAllStrokes;
- (void)endStroke;
- (void).cxx_destruct;
- (void)removeStrokeAtIndex:(unsigned int)arg1;
- (id).cxx_construct;
- (struct CGPoint)pointAtIndex:(unsigned int)arg1 inStrokeAtIndex:(unsigned int)arg2;
- (unsigned int)numberOfPointsInStrokeAtIndex:(unsigned int)arg1;
- (void)addPoint:(struct CGPoint)arg1;
- (unsigned int)numberOfStrokes;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

