//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <TextInput/TIKeyboardCandidate.h>

@class NSString;

@interface TIKeyboardCandidateSingle : TIKeyboardCandidate
{
    NSString *_candidate;
    NSString *_input;
}

+ (id)candidateWithCandidate:(id)arg1 forInput:(id)arg2;
+ (id)candidateWithUnchangedInput:(id)arg1;
+ (BOOL)supportsSecureCoding;
+ (int)type;
- (id)initWithCandidate:(id)arg1;
- (id)initWithUnchangedInput:(id)arg1;
- (id)initWithCandidate:(id)arg1 forInput:(id)arg2;
- (void)encodeWithCandidateResultSetCoder:(id)arg1;
- (id)initWithCandidateResultSetCoder:(id)arg1;
@property(copy, nonatomic) NSString *candidate; // @synthesize candidate=_candidate;
@property(copy, nonatomic) NSString *input; // @synthesize input=_input;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end

