//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class NSArray;

@interface TILexicon : NSObject <NSCopying, NSSecureCoding>
{
    NSArray *_entries;
}

+ (id)lexiconWithEntries:(id)arg1;
+ (void)requestLexiconFromBundlePath:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
+ (BOOL)supportsSecureCoding;
@property(readonly, nonatomic) NSArray *entries; // @synthesize entries=_entries;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end

