//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <EventKitUI/EKCalendarInfo.h>

@interface EKDeclinedCalendarItemInfo : EKCalendarInfo
{
}

- (id)icon;
- (void)setSelected:(BOOL)arg1;
- (BOOL)isEditable;
- (id)title;
- (id)description;
- (id)init;
- (BOOL)excludeFromSelectAll;

@end

