//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ML3MusicLibrary, NSMutableArray, NSObject<OS_dispatch_queue>;

@interface ML3SortMapSections : NSObject
{
    NSMutableArray *_sectionNameOrders;
    NSObject<OS_dispatch_queue> *_sectionQueue;
    ML3MusicLibrary *_library;
}

+ (id)sharedSectionsForLibrary:(id)arg1;
+ (void)initialize;
- (id)nameOrderForSection:(unsigned char)arg1;
- (id)_initWithLibrary:(id)arg1;
- (void)_loadWithConnection:(id)arg1 forLibrary:(id)arg2;
- (void)resetSections;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end

