//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSHTTPURLResponse, NSNumber, NSString;

@interface SSAuthenticationResponse : NSObject
{
    NSDictionary *_responseDictionary;
    int _urlBagType;
    NSHTTPURLResponse *_urlResponse;
}

@property(readonly) NSHTTPURLResponse *URLResponse;
- (int)_responseTypeForStatusValue:(int)arg1;
- (int)_responseTypeForErrorNumber:(int)arg1;
- (int)_responseTypeForFailureType:(int)arg1;
@property(readonly) NSNumber *accountUniqueIdentifier;
- (id)_valueForFirstAvailableKey:(id)arg1;
@property(readonly) NSNumber *failureType;
- (id)newAccount;
- (id)initWithURLResponse:(id)arg1 dictionary:(id)arg2;
@property int URLBagType; // @synthesize URLBagType=_urlBagType;
@property(readonly) int availableServiceTypes;
@property(readonly) int accountKind;
@property(readonly) NSString *creditsString;
@property(readonly) int enabledServiceTypes;
@property(readonly, getter=isNewCustomer) BOOL newCustomer;
@property(readonly) NSDictionary *responseDictionary; // @synthesize responseDictionary=_responseDictionary;
@property(readonly) NSString *userMessage;
@property(readonly) int responseType;
@property(readonly) NSString *accountName;
@property(readonly) NSString *token;
- (void)dealloc;
@property(readonly) NSString *storeFrontIdentifier;

@end

