//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "SSXPCCoding.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>, NSString;

@interface SSOperationProgress : NSObject <SSXPCCoding, NSCopying>
{
    BOOL _canPause;
    double _changeRate;
    long long _currentValue;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    double _estimatedTimeRemaining;
    long long _maxValue;
    long long _normalizedCurrentValue;
    long long _normalizedMaxValue;
    int _operationType;
    NSMutableArray *_snapshotTimes;
    NSMutableArray *_snapshotValues;
    int _units;
}

@property BOOL canPause;
@property long long currentValue;
@property int units;
@property double estimatedTimeRemaining;
@property double changeRate;
- (void)resetSnapshots;
- (void)_updateStatisticsFromSnapshots;
@property long long maxValue;
@property long long normalizedMaxValue;
@property long long normalizedCurrentValue;
@property int operationType;
- (id)copyXPCEncoding;
- (id)initWithXPCEncoding:(id)arg1;
- (void)snapshot;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSString *description;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

