//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

#import "NSURLConnectionDelegate.h"

@class NSCachedURLResponse, NSData, NSHTTPURLResponse, NSMutableData, NSMutableSet, NSObject<OS_dispatch_queue>, NSRunLoop, NSString, NSURL, NSURLRequest, SSMetricsPageEvent, SSVURLDataConsumer;

@interface SSVLoadURLOperation : NSOperation <NSURLConnectionDelegate>
{
    NSMutableData *_dataBuffer;
    SSVURLDataConsumer *_dataConsumer;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    CDUnknownBlockType _expiredOutputBlock;
    NSData *_inputData;
    BOOL _iTunesStoreRequest;
    SSMetricsPageEvent *_metricsPageEvent;
    CDUnknownBlockType _outputBlock;
    NSMutableSet *_protocolRedirectURLs;
    BOOL _recordsMetrics;
    NSURL *_redirectURL;
    NSString *_referrerApplicationName;
    NSString *_referrerURLString;
    NSHTTPURLResponse *_response;
    NSRunLoop *_runLoop;
    NSString *_storeFrontSuffix;
    BOOL _stopped;
    NSURLRequest *_urlRequest;
}

- (id)_dataForCachedResponse:(struct _CFCachedURLResponse *)arg1;
@property(copy) NSString *storeFrontSuffix;
@property(copy) NSString *referrerURLString;
@property(copy) NSString *referrerApplicationName;
@property BOOL recordsMetrics;
@property(copy) CDUnknownBlockType expiredOutputBlock;
- (void)dispatchSync:(CDUnknownBlockType)arg1;
- (void)dispatchAsync:(CDUnknownBlockType)arg1;
@property(readonly) NSCachedURLResponse *cachedURLResponse;
- (id)initWithData:(id)arg1 fromOperation:(id)arg2;
- (void)_keepAliveTimer:(id)arg1;
- (long)_runRunLoopUntilStopped;
- (void)_stopIfCancelled;
- (void)_releaseOutputBlocks;
@property(copy) CDUnknownBlockType outputBlock;
- (id)_outputForData:(id)arg1 error:(id *)arg2;
- (void)_applyResponseToMetrics:(id)arg1;
- (void)_finishWithOutput:(id)arg1 error:(id)arg2;
- (void)_runOnce;
- (void)_finishWithData:(id)arg1;
- (void)_stopRunLoop;
- (id)_newURLRequestWithRedirectURL:(id)arg1;
@property(readonly) SSMetricsPageEvent *metricsPageEvent;
- (id)_initSSVLoadURLOperation;
@property(getter=isITunesStoreRequest) BOOL ITunesStoreRequest;
- (id)initWithURLRequestProperties:(id)arg1;
@property(retain) SSVURLDataConsumer *dataConsumer;
- (void).cxx_destruct;
- (void)main;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
@property(readonly) NSURL *URL;
- (id)initWithURL:(id)arg1;
- (id)init;
- (void)cancel;
- (id)initWithURLRequest:(id)arg1;
@property(readonly) NSURLRequest *URLRequest;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

