//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PLArchiveJobManager.h"

@class NSMutableArray, NSNumber, NSString, PLEntryNotificationOperatorComposition, PLNSTimerOperatorComposition;

@interface PLArchiveManager : NSObject <PLArchiveJobManager>
{
    BOOL _enabled;
    BOOL _interrupted;
    NSNumber *_minDaysMainDB;
    NSNumber *_minDaysTotalLogDuration;
    PLNSTimerOperatorComposition *_periodicTimer;
    NSMutableArray *_archiveJobs;
    PLEntryNotificationOperatorComposition *_unpluggedNotification;
    PLEntryNotificationOperatorComposition *_displayOnNotification;
    NSMutableArray *_notificationBlocks;
}

+ (id)archiveEntriesUnfinished;
+ (id)archiveEntriesFinished;
+ (id)archiveEntriesWhere:(id)arg1;
+ (void)crashMoverDidFinish;
+ (void)systemTimeChangedByOffset:(double)arg1;
+ (void)linkAllArchiveDBToCRFolder;
+ (id)storageQueue;
+ (id)sharedInstance;
+ (id)workQueue;
- (void)disable;
- (void)runJobs;
- (void)scheduleJobs;
@property(retain) NSMutableArray *notificationBlocks; // @synthesize notificationBlocks=_notificationBlocks;
@property(retain) PLEntryNotificationOperatorComposition *displayOnNotification; // @synthesize displayOnNotification=_displayOnNotification;
@property(retain) PLEntryNotificationOperatorComposition *unpluggedNotification; // @synthesize unpluggedNotification=_unpluggedNotification;
@property(retain) NSMutableArray *archiveJobs; // @synthesize archiveJobs=_archiveJobs;
@property(retain) PLNSTimerOperatorComposition *periodicTimer; // @synthesize periodicTimer=_periodicTimer;
@property(retain, nonatomic) NSNumber *minDaysTotalLogDuration; // @synthesize minDaysTotalLogDuration=_minDaysTotalLogDuration;
@property(retain, nonatomic) NSNumber *minDaysMainDB; // @synthesize minDaysMainDB=_minDaysMainDB;
- (void)migrateArchive:(id)arg1;
- (void)runActivity;
- (BOOL)shouldRun;
- (void)handleFailure:(int)arg1 forArchiveEntry:(id)arg2;
- (void)recover;
- (void)registerForArchivingNotificationUsingBlock:(CDUnknownBlockType)arg1;
- (void)migrate;
@property BOOL interrupted; // @synthesize interrupted=_interrupted;
- (void)cleanup;
- (void).cxx_destruct;
- (void)enable;
@property BOOL enabled; // @synthesize enabled=_enabled;
- (id)init;
- (void)dealloc;
- (void)interrupt;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

