//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PowerlogCore/PLEntry.h>

@class NSDate, NSString;

@interface PLArchiveEntry : PLEntry
{
    BOOL _systemTimeOffsetModified;
}

+ (id)entryKey;
+ (id)storageQueue;
+ (void)load;
@property(readonly) NSDate *endDate;
@property(readonly) NSDate *startDate;
- (id)initEntryWithRawData:(id)arg1;
@property(readonly) BOOL fullMode;
@property(readonly) BOOL systemTimeOffsetModified; // @synthesize systemTimeOffsetModified=_systemTimeOffsetModified;
- (void)linkToCR;
@property(nonatomic) long long mainDBSizeAtStart;
@property(readonly, nonatomic) BOOL removed;
@property(retain, nonatomic) NSDate *removedDate;
@property(retain, nonatomic) NSDate *syncedOffDate;
@property(nonatomic) unsigned int numAttempts;
@property(nonatomic) double systemTimeOffset;
- (id)initWithMetadata:(id)arg1;
- (id)initWithStartDate:(id)arg1 endDate:(id)arg2 andUUID:(id)arg3;
@property(readonly, nonatomic) NSString *crPath;
@property(readonly, nonatomic) BOOL syncedOff;
@property(readonly, nonatomic) NSString *compressedPath;
@property(readonly) NSString *uuid;
@property(nonatomic) int stage;
- (void)update;
- (void)log;
@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic) NSString *path;

@end

