//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CloudKit/CKOperation.h>

@class CKShareID, NSArray, NSMutableArray, NSMutableDictionary;

@interface CKModifyShareCommentsOperation : CKOperation
{
    NSArray *_commentsToSave;
    NSArray *_commentIDsToDelete;
    CKShareID *_shareID;
    CDUnknownBlockType _modifyShareCommentCompletionBlock;
    NSMutableArray *_savedComments;
    NSMutableDictionary *_commentsToSaveByLocalID;
    NSMutableArray *_deletedCommentIDs;
    NSMutableDictionary *_errorsByCommentID;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType modifyShareCommentCompletionBlock; // @synthesize modifyShareCommentCompletionBlock=_modifyShareCommentCompletionBlock;
@property(retain, nonatomic) NSMutableArray *deletedCommentIDs; // @synthesize deletedCommentIDs=_deletedCommentIDs;
@property(retain, nonatomic) NSMutableArray *savedComments; // @synthesize savedComments=_savedComments;
@property(retain, nonatomic) NSMutableDictionary *errorsByCommentID; // @synthesize errorsByCommentID=_errorsByCommentID;
@property(copy, nonatomic) NSArray *commentIDsToDelete; // @synthesize commentIDsToDelete=_commentIDsToDelete;
@property(copy, nonatomic) NSArray *commentsToSave; // @synthesize commentsToSave=_commentsToSave;
@property(retain, nonatomic) NSMutableDictionary *commentsToSaveByLocalID; // @synthesize commentsToSaveByLocalID=_commentsToSaveByLocalID;
- (id)initWithCommentsToSave:(id)arg1 commentIDsToDelete:(id)arg2 inShareWithID:(id)arg3;
@property(copy, nonatomic) CKShareID *shareID; // @synthesize shareID=_shareID;
- (void)_handleProgressCallback:(id)arg1;
- (void)performCKOperation;
- (BOOL)CKOperationShouldRun:(id *)arg1;
- (void)_finishOnCallbackQueueWithError:(id)arg1;
- (void)fillOutOperationInfo:(id)arg1;

@end

