//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CloudKit/CKNotification.h>

#import "NSSecureCoding.h"

@class CKDiscoveredUserInfo, CKShareID;

@interface CKShareNotification : CKNotification <NSSecureCoding>
{
    int _shareNotificationReason;
    CKShareID *_shareID;
    CKDiscoveredUserInfo *_participantInfo;
}

+ (BOOL)supportsSecureCoding;
- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(copy, nonatomic) CKDiscoveredUserInfo *participantInfo; // @synthesize participantInfo=_participantInfo;
@property(nonatomic) int shareNotificationReason; // @synthesize shareNotificationReason=_shareNotificationReason;
- (id)initWithRemoteNotificationDictionary:(id)arg1;
@property(copy, nonatomic) CKShareID *shareID; // @synthesize shareID=_shareID;
- (id)CKPropertiesDescription;

@end

