//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class CKRecordID, NSString;

@interface CKShareParticipant : NSObject <NSSecureCoding, NSCopying>
{
    BOOL _isCurrentUser;
    CKRecordID *_userRecordID;
    NSString *_firstName;
    NSString *_lastName;
    NSString *_emailAddress;
    NSString *_participantID;
    int _acceptanceStatus;
    int _itemPermission;
    int _listPermission;
    int _originalAcceptanceStatus;
    int _originalItemPermission;
    int _originalListPermission;
}

+ (BOOL)supportsSecureCoding;
@property(copy, nonatomic) NSString *lastName; // @synthesize lastName=_lastName;
@property(copy, nonatomic) NSString *firstName; // @synthesize firstName=_firstName;
@property(copy, nonatomic) NSString *participantID; // @synthesize participantID=_participantID;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)debugDescription;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) BOOL isCurrentUser; // @synthesize isCurrentUser=_isCurrentUser;
@property(copy, nonatomic) NSString *emailAddress; // @synthesize emailAddress=_emailAddress;
@property(nonatomic) int originalListPermission; // @synthesize originalListPermission=_originalListPermission;
@property(nonatomic) int originalItemPermission; // @synthesize originalItemPermission=_originalItemPermission;
@property(nonatomic) int originalAcceptanceStatus; // @synthesize originalAcceptanceStatus=_originalAcceptanceStatus;
@property(nonatomic) int acceptanceStatus; // @synthesize acceptanceStatus=_acceptanceStatus;
@property(copy, nonatomic) CKRecordID *userRecordID; // @synthesize userRecordID=_userRecordID;
- (id)_initWithUserRecordID:(id)arg1 participantID:(id)arg2 emailAddress:(id)arg3 acceptanceStatus:(int)arg4 itemPermission:(int)arg5 listPermission:(int)arg6;
@property(nonatomic) int listPermission; // @synthesize listPermission=_listPermission;
@property(nonatomic) int itemPermission; // @synthesize itemPermission=_itemPermission;
- (BOOL)isEquivalentToParticipant:(id)arg1;
- (id)CKPropertiesDescription;

@end

