//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSString, SSURLConnectionRequest;

@interface HSAccountStore : NSObject
{
    int _defaultsDidChangeToken;
    SSURLConnectionRequest *_groupIDRequest;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)defaultStore;
- (void)clearCaches;
@property(retain, nonatomic) SSURLConnectionRequest *groupIDRequest; // @synthesize groupIDRequest=_groupIDRequest;
- (void)clearAllCredentials;
@property(copy, nonatomic) NSString *appleID; // @dynamic appleID;
- (BOOL)canDetermineGroupID;
- (void)_onBackgroundQueue_determineGroupIDWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)clearGroupID;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(copy, nonatomic) NSString *groupID; // @dynamic groupID;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;
- (void)determineGroupIDWithCompletionHandler:(CDUnknownBlockType)arg1;
@property(copy, nonatomic) NSString *password; // @dynamic password;

@end

