//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBTransaction.h"

@class NSMutableDictionary;

@interface IOSSHLTransaction : FBTransaction
{
    NSMutableDictionary *_transactionContext;
    IOSSHLTransaction *_parent;
}

@property(nonatomic) __weak IOSSHLTransaction *parent; // @synthesize parent=_parent;
- (void)setTransactionContextObject:(id)arg1 forKey:(id)arg2;
- (void)clearTransactionContextObjectForKey:(id)arg1;
- (id)transactionContextObjectForKey:(id)arg1;
- (void)addChildTransaction:(id)arg1;
- (BOOL)shouldWatchdog:(id *)arg1;
- (double)watchdogTimeout;
- (void).cxx_destruct;

@end

