//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BSFileLogger.h"

@class NSString;

@interface IOSSHLTransactionLogger : BSFileLogger
{
    NSString *_overrideLogPath;
}

- (int)maxLogSize;
- (BOOL)shouldEnableOnInternalBuilds;
- (unsigned int)logDestinations;
- (id)logPath;
- (void).cxx_destruct;
- (void)_setEnabled:(BOOL)arg1;
- (BOOL)isEnabled;
- (id)name;
- (id)init;

@end

