//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IOSSHLActivationSettings, IOSSHLApplication, NSArray, NSDictionary, NSNumber, NSString, NSURL, UILocalNotification;

@protocol IOSSHLUIDelegate <NSObject>
- (BOOL)createDownscaledSnapshots;
- (void)applicationOpenURL:(NSURL *)arg1 withApplication:(IOSSHLApplication *)arg2 sender:(IOSSHLApplication *)arg3 publicURLsOnly:(BOOL)arg4 animating:(BOOL)arg5 needsPermission:(BOOL)arg6 activationSettings:(IOSSHLActivationSettings *)arg7 withResult:(void (^)(int))arg8;
- (void)failedTest:(NSString *)arg1 withResults:(NSDictionary *)arg2;
- (void)appExitedAbnormally:(IOSSHLApplication *)arg1;
- (BOOL)hasLockScreen;
- (BOOL)hasSetupApp;
- (BOOL)isPresentationALockVunerability:(IOSSHLApplication *)arg1 withURL:(NSURL *)arg2;
- (BOOL)isPresentationIdentifierRestrictionDisabled:(NSString *)arg1;
- (BOOL)underMemoryPressure;
- (void)resetIdleTimerAndUndim:(_Bool)arg1;
- (void)powerDownForCriticalBattery;
- (void)powerDown;
- (void)reboot;
- (void)noteInterfaceOrientationChanged:(int)arg1 duration:(float)arg2;
- (int)activeInterfaceOrientation;
- (BOOL)systemAppWantsOrientationEvents;
- (NSString *)systemAppBundleIdentifier;
- (short)powerLogClientID;

@optional
- (void)showLanguageChangingUI:(BOOL)arg1 completion:(void (^)(void))arg2;
- (BOOL)isPasscodeLockedOrBlocked;
- (BOOL)isPasscodeLocked;
- (BOOL)hasUIEverBeenLocked;
- (BOOL)isUILocked;
- (_Bool)relaunchingForSetupLanguageChange;
- (_Bool)willRunSetupApplication;
- (void)handleNotRelaunchingSetup;
- (_Bool)isInSetupMode;
- (_Bool)updateInSetupMode;
- (NSString *)setupApplicationBundleID;
- (IOSSHLApplication *)setupApplication;
- (void)applicationDidUpdateSystemLocalNotificationTimers:(IOSSHLApplication *)arg1;
- (void)application:(IOSSHLApplication *)arg1 didSnoozeSystemLocalNotification:(UILocalNotification *)arg2;
- (BOOL)application:(IOSSHLApplication *)arg1 hasSystemAlarmSnoozeNotification:(UILocalNotification *)arg2;
- (void)applicationWillDeactivateAllLocalNotifications:(IOSSHLApplication *)arg1;
- (void)application:(IOSSHLApplication *)arg1 willDeactivateLocalNotification:(UILocalNotification *)arg2;
- (void)application:(IOSSHLApplication *)arg1 willFireSystemLocalNotification:(UILocalNotification *)arg2;
- (void)indicateConnectedToPower;
- (void)batteryStatusDidChange:(NSDictionary *)arg1;
- (void)systemAppSetTypingActive:(_Bool)arg1;
- (void)setNextAssistantRecognitionStrings:(NSArray *)arg1;
- (NSNumber *)setNextVoiceRecognitionAudioInputPaths:(NSArray *)arg1;
@end

