//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IOSSHLMuteModel : NSObject
{
    int _notifyToken;
    BOOL _systemMuted;
    id <IOSSHLMuteModelDelegate> _delegate;
}

- (void)_ringerStateChanged;
- (void)_setSystemMuted:(BOOL)arg1;
- (BOOL)_isRingerStateMuted;
- (void).cxx_destruct;
@property(nonatomic) __weak id <IOSSHLMuteModelDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;
- (void)dealloc;
@property(nonatomic, getter=isMuted) BOOL muted;
- (void)_registerForNotifications;
- (void)_unregisterForNotifications;

@end

