//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IdleTimer, NSMutableDictionary;

@interface IOSSHLUserIdleMonitor : NSObject
{
    NSMutableDictionary *_timers;
    int _timerMode;
    IdleTimer *_activeTimer;
    double _idleSecondsLastIdle;
    double _idleSecondsNextIdle;
}

+ (id)sharedInstance;
- (void)_userEventUnidled;
- (void)_userEventIdled;
- (void)_userEventPresenceExpired;
- (void)_userEventPresent;
- (void)postponeIdlingForAction:(id)arg1 forSeconds:(double)arg2 forReason:(id)arg3;
- (void)unregisterIdlingAction:(id)arg1;
@property(nonatomic) double idleSecondsNextIdle; // @synthesize idleSecondsNextIdle=_idleSecondsNextIdle;
@property(nonatomic) int timerMode; // @synthesize timerMode=_timerMode;
@property(nonatomic) __weak IdleTimer *activeTimer; // @synthesize activeTimer=_activeTimer;
- (void)_idleActiveTimerAndActivateNextTimer_shouldAlwaysSetPresenseMode:(_Bool)arg1;
@property(nonatomic) double idleSecondsLastIdle; // @synthesize idleSecondsLastIdle=_idleSecondsLastIdle;
- (void)_unidleAndRestartAllTimers;
- (void)_setUserEventTimer:(id)arg1 mode:(int)arg2 timerSeconds:(double)arg3 idleSecondsNextIdle:(double)arg4;
- (id)_expireTimersAndFindNextUnexpiredOneAfterSeconds:(double)arg1 hasEnabledIdleTimers:(_Bool *)arg2;
- (void)_postponementComplete:(id)arg1;
- (void)_resetUserIdleTimerForcedRestart:(_Bool)arg1;
- (void)enableIdlingForAction:(id)arg1 enabled:(_Bool)arg2 retroactive:(_Bool)arg3;
- (void)restartIdlingForAction:(id)arg1;
- (void)setIdleSeconds:(double)arg1 forReason:(id)arg2 ofAction:(id)arg3;
- (void)registerIdlingAction:(id)arg1 idleBlock:(CDUnknownBlockType)arg2 unidleBlock:(CDUnknownBlockType)arg3;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end

