//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer;

@interface IOSSHLButtonKeyState : NSObject
{
    NSTimer *_holdTimer;
    NSTimer *_tapTimer;
    unsigned int _tapCount:8;
    unsigned long long _downtime;
    unsigned long long _firstUptime;
    _Bool _down;
    _Bool _gestureStoppedUntilUp;
    id <IOSSHLButtonKeyStateDelegate> _delegate;
    int _heldState;
}

@property(nonatomic) int heldState; // @synthesize heldState=_heldState;
- (_Bool)isProcessingGestures;
- (id)heldStateDescription;
- (id)downDescription;
@property(readonly, nonatomic, getter=isDown) _Bool down; // @synthesize down=_down;
- (void)stopHoldGesture;
@property(nonatomic) _Bool gestureStoppedUntilUp; // @synthesize gestureStoppedUntilUp=_gestureStoppedUntilUp;
- (void)_handleButtonTappedTimeout:(id)arg1;
- (void)_buttonWasHeld:(id)arg1;
- (void)_handleGesturesCompleted;
- (void)_handleButtonTapped;
- (void)_buttonWasLongHeld:(id)arg1;
- (void)_handleButtonHeld:(int)arg1;
- (void)setDown:(_Bool)arg1 timestamp:(unsigned long long)arg2;
- (id)initWithDown:(_Bool)arg1 timestamp:(unsigned long long)arg2 delegate:(id)arg3;
- (void).cxx_destruct;
- (unsigned int)tapCount;
@property(nonatomic) __weak id <IOSSHLButtonKeyStateDelegate> delegate; // @synthesize delegate=_delegate;
- (id)description;
- (id)init;

@end

