//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IOSSHLSnapshotDataProvider.h"

@class IOSSHLSnapshotDataProviderContext, NSString, UIScreen;

@interface IOSSHLIOSurfacePNGSnapshotDataProvider : NSObject <IOSSHLSnapshotDataProvider>
{
    struct __IOSurface *_surface;
    IOSSHLSnapshotDataProviderContext *_context;
    BOOL _shouldRotate;
    UIScreen *_screen;
}

- (id)fetchData;
- (id)initWithIOSurfaceRef:(struct __IOSurface *)arg1 screen:(id)arg2 context:(id)arg3 shouldRotate:(BOOL)arg4;
- (void).cxx_destruct;
@property(readonly, retain, nonatomic) IOSSHLSnapshotDataProviderContext *context; // @synthesize context=_context;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

