//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NPSDomainAccessor, NPSManager, NSMutableDictionary;

@interface IOSSHLBackedUpDataStoreManager : NSObject
{
    NPSManager *_manager;
    NPSDomainAccessor *_domainAccessor;
    NSMutableDictionary *_data;
}

+ (id)sharedInstance;
- (void)_applicationStateChanged:(id)arg1;
- (void)removeAllObjectsForApplication:(id)arg1;
- (void)removeObjectForKey:(id)arg1 application:(id)arg2;
- (void)setObject:(id)arg1 forKey:(id)arg2 application:(id)arg3;
- (void)_restore;
- (void)_backup;
- (void)_postRestoreCompleteNotification;
- (void)_initialSyncCompleted;
- (void)_applicationStateBackupChanged;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end

