//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IOSSHLApplicationTerminationAssertion.h"

@class IOSSHLApplicationTerminationAssertionManager, NSString;

@interface IOSSHLApplicationTerminationAssertionImpl : NSObject <IOSSHLApplicationTerminationAssertion>
{
    NSString *_presentationId;
    unsigned char _reason;
    IOSSHLApplicationTerminationAssertionManager *_manager;
}

@property(readonly, copy, nonatomic) NSString *presentationId; // @synthesize presentationId=_presentationId;
- (id)initWithPresentationId:(id)arg1 reason:(unsigned char)arg2 manager:(id)arg3;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned char reason; // @synthesize reason=_reason;
@property(readonly, copy) NSString *description;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

