//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IOSSHLRenderImage : NSObject
{
    struct _CARenderImage *_image;
}

- (id)initWithRenderImage:(struct _CARenderImage *)arg1;
- (void)dealloc;
- (void *)CA_copyRenderValue;

@end

