//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IOSSystemShell/IOSSHLTransaction.h>

@interface IOSSHLWorkspaceTransaction : IOSSHLTransaction
{
}

- (void)_didComplete:(BOOL)arg1;
- (void)_performDeviceCoherencyCheck;
- (BOOL)_canBeInterrupted;
- (void)keepAliveForAsyncBlock:(CDUnknownBlockType)arg1;

@end

