//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (IOSSystemShell)
- (id)iosshlf_foldWithInitialValue:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)iosshlf_first:(unsigned int)arg1;
- (id)iosshlf_reverse;
- (id)iosshlf_mapNoNulls:(CDUnknownBlockType)arg1;
- (id)iosshlf_firstObjectOfClassNamed:(id)arg1;
- (id)iosshlf_filter:(CDUnknownBlockType)arg1;
- (id)iosshlf_map:(CDUnknownBlockType)arg1;
- (void)iosshlf_each:(CDUnknownBlockType)arg1;
- (id)iosshlf_firstObjectOfClass:(Class)arg1;
- (id)iosshlf_firstObjectPassingTest:(CDUnknownBlockType)arg1;
@end

