//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (IOSSHLGraphics)
+ (id)iosshlg_imageFromContextWithSize:(struct CGSize)arg1 scale:(float)arg2 type:(int)arg3 pool:(id)arg4 drawing:(CDUnknownBlockType)arg5;
+ (unsigned long)iosshlg_bytesNeededForSize:(struct CGSize)arg1 scale:(float)arg2 withContextType:(int)arg3;
+ (id)iosshlg_imageFromContextWithSize:(struct CGSize)arg1 scale:(float)arg2 type:(int)arg3 pool:(id)arg4 drawing:(CDUnknownBlockType)arg5 encapsulation:(CDUnknownBlockType)arg6;
- (id)iosshlg_cropImageWithRect:(struct CGRect)arg1 outputSize:(struct CGSize)arg2;
- (id)iosshlg_squareImage;
- (id)iosshlg_thumbnailFitToSize:(struct CGSize)arg1;
@property(readonly, nonatomic) struct CGSize pixelSize;
- (id)iosshlg_memoryMappedImageWithPool:(id)arg1;
- (BOOL)iosshlg_hasAlpha;
- (struct CGImage *)_newThumbnailWithImageSource:(struct CGImageSource *)arg1 forMaxPixelDimension:(float)arg2;
- (struct CGImageSource *)_newSource;
- (struct CGImage *)_newThumbnailWithJPEG:(id)arg1 forMaxPixelDimension:(float)arg2;
- (id)iosshlg_resizeImageToSize:(struct CGSize)arg1 preservingAspectRatio:(BOOL)arg2;
- (id)iosshlg_resizeImageToSize:(struct CGSize)arg1;
- (id)_thumbnailFitToSize:(struct CGSize)arg1;
- (BOOL)isAnimated;
@end

