//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SSDownloadQueueObserver.h"

@class NSMutableSet, NSObject<OS_dispatch_queue>, NSString;

@interface ISNetworkObserver : NSObject <SSDownloadQueueObserver>
{
    NSString *_dataStatusIndicator;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    BOOL _isCellularRestricted;
    double _lastNetworkTypeChangeTime;
    int _networkUsageCount;
    int _networkType;
    NSObject<OS_dispatch_queue> *_notificationQueue;
    NSMutableSet *_observedDownloadQueues;
    NSString *_operatorName;
    struct __SCNetworkReachability *_reachability;
    NSString *_registrationStatus;
    struct __CTServerConnection *_telephonyServer;
}

+ (void)setWiFiEnabled:(BOOL)arg1;
+ (void)setAirplaneModeEnabled:(BOOL)arg1;
+ (void)set3GEnabled:(BOOL)arg1;
+ (id)sharedInstance;
- (void)_reloadNetworkTypeWithReachabilityFlags:(unsigned int)arg1;
- (void)_reloadCellularRestriction;
- (void)reloadNetworkType;
@property(readonly) NSString *modemRegistrationStatus;
- (BOOL)isCellularDataEnabledForBundleIdentifier:(id)arg1;
@property(readonly) NSString *dataStatusIndicator;
- (void)endObservingDownloadQueue:(id)arg1;
- (void)beginObservingDownloadQueue:(id)arg1;
- (int)_networkTypeFromDataIndicator:(id)arg1;
- (int)_networkTypeForReachabilityFlags:(unsigned int)arg1;
- (void)_postTypeChangedNotificationFromValue:(int)arg1 toValue:(int)arg2;
- (int)_setNetworkType:(int)arg1;
- (void)_reloadNetworkType;
- (id)_dataStatusIndicator;
- (id)copyValueForCarrierBundleKey:(id)arg1;
- (void)_postUsageChangedToValue:(BOOL)arg1;
- (BOOL)_ntsIsUsingNetwork;
- (int)_currentNetworkType;
@property(readonly) NSString *connectionTypeHeader;
@property(readonly) double lastNetworkTypeChangeTime;
- (void)endUsingNetwork;
- (void)beginUsingNetwork;
- (void)downloadQueue:(id)arg1 changedWithRemovals:(id)arg2;
- (void)downloadQueueNetworkUsageChanged:(id)arg1;
@property(readonly, getter=isUsingNetwork) BOOL usingNetwork;
@property int networkType;
@property(readonly) NSString *operatorName;
- (void)_handleTelephonyNotificationWithName:(struct __CFString *)arg1 userInfo:(struct __CFDictionary *)arg2;
- (id)init;
- (void)dealloc;
@property(readonly) BOOL shouldShowCellularAutomaticDownloadsSwitch;
- (void)_applicationWillEnterForegroundNotification:(id)arg1;
@property(readonly, getter=isWiFiEnabled) BOOL wifiEnabled;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

