//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface ISSoftwareMap : NSObject
{
    NSArray *_applications;
}

+ (void)_startWatchingInstallationNotifications;
+ (id)loadedMap;
+ (void)invalidateCurrentMap;
+ (BOOL)haveApplicationsOfType:(id)arg1;
+ (void)enumerateApplicationsForProxies:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
+ (id)containerPathForApp:(id)arg1 homeDirectory:(id)arg2 systemMetadataDirectory:(id)arg3;
+ (id)_newSoftwareUpdateDictionaryForApplication:(id)arg1;
+ (id)copySoftwareUpdatesPropertyListWithApplications:(id)arg1 updatesContext:(id)arg2;
+ (id)currentMap;
+ (void)startObservingNotifications;
+ (void)setCurrentMap:(id)arg1;
+ (BOOL)currentMapIsValid;
+ (id)applicationForBundleIdentifier:(id)arg1;
+ (id)applicationForBundleIdentifier:(id)arg1 applicationType:(id)arg2;
- (id)copySoftwareUpdatesPropertyList;
- (id)applicationForItemIdentifier:(id)arg1;
- (id)copySoftwareUpdatesPropertyListWithUpdatesContext:(id)arg1;
- (void)_loadFromMobileInstallation;
- (id)applicationForBundleIdentifier:(id)arg1;
- (id)init;
- (void)dealloc;
@property(readonly, nonatomic) NSArray *applications;

@end

