//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <iTunesStore/ISURLOperation.h>

@class NSNumber;

@interface ISStoreURLOperation : ISURLOperation
{
    NSNumber *_authenticatedDSID;
    BOOL _canSendGUIDParameter;
    BOOL _ignorePreexistingSecureToken;
    BOOL _needsAuthentication;
    BOOL _needsURLBag;
    BOOL _performsMachineDataActions;
    BOOL _shouldSendXTokenHeader;
    BOOL _urlKnownToBeTrusted;
    BOOL _useUserSpecificURLBag;
}

+ (id)propertyListOperationWithURLBagKey:(id)arg1;
+ (id)itemPingOperationWithIdentifier:(unsigned long long)arg1 urlBagKey:(id)arg2;
+ (void)handleITunesStoreResponseHeaders:(id)arg1 withAccountIdentifier:(id)arg2;
+ (void)addITunesStoreHeadersToRequest:(id)arg1 withAccountIdentifier:(id)arg2;
+ (id)_restrictionsHeaderValue;
+ (void)_addITunesStoreHeadersToRequest:(id)arg1 withURLBag:(id)arg2 account:(id)arg3;
+ (void)_addITunesStoreHeadersToRequest:(id)arg1 withURLBag:(id)arg2 accountIdentifier:(id)arg3;
+ (id)pingOperationWithUrl:(id)arg1;
@property BOOL useUserSpecificURLBag; // @synthesize useUserSpecificURLBag=_useUserSpecificURLBag;
@property BOOL shouldSendXTokenHeader;
@property BOOL performsMachineDataActions;
@property BOOL canSendGUIDParameter;
- (void)_addStandardQueryParametersForURL:(id)arg1;
- (id)_resolvedURLInBagContext:(id)arg1 URLBag:(id *)arg2;
@property BOOL needsURLBag; // @synthesize needsURLBag=_needsURLBag;
@property BOOL urlKnownToBeTrusted; // @synthesize urlKnownToBeTrusted=_urlKnownToBeTrusted;
@property(nonatomic) BOOL ignorePreexistingSecureToken;
- (BOOL)_isErrorTokenError:(id)arg1;
- (void)_runURLOperation;
- (BOOL)_authenticateWithContext:(id)arg1 error:(id *)arg2;
- (id)_copyAuthenticationContextForAttemptNumber:(int)arg1;
- (id)_urlBagForContext:(id)arg1;
- (id)_copyURLBagContext;
- (BOOL)_canSendTokenToURL:(id)arg1;
@property(retain) NSNumber *authenticatedDSID; // @synthesize authenticatedDSID=_authenticatedDSID;
- (BOOL)shouldFollowRedirectWithRequest:(id)arg1 returningError:(id *)arg2;
- (BOOL)handleRedirectFromDataProvider:(id)arg1 error:(id *)arg2;
- (id)authenticatedAccountDSID;
- (id)newRequestWithURL:(id)arg1;
- (id)_copyAuthenticationContext;
- (id)_account;
- (void)_setStoreFrontIdentifier:(id)arg1 isTransient:(BOOL)arg2;
@property BOOL needsAuthentication; // @synthesize needsAuthentication=_needsAuthentication;
- (void)handleResponse:(id)arg1;
- (void)run;
- (id)init;
- (void)dealloc;

// Remaining properties
@property id <ISStoreURLOperationDelegate> delegate; // @dynamic delegate;

@end

