//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ALRecorder, NSString;

@interface AppleLisaHIDDevice : NSObject
{
    struct __IOHIDDevice *_deviceRef;
    char *_report;
    unsigned char _getReportPayload[512];
    BOOL _registeredForInput;
    BOOL _isOpen;
    CDUnknownFunctionPointerType _frameCallback;
    void *_frameRefcon;
    CDUnknownFunctionPointerType _imageCallback;
    void *_imageRefcon;
    CDUnknownFunctionPointerType _algsCallback;
    void *_algsRefcon;
    CDUnknownFunctionPointerType _debugCallback;
    void *_debugRefcon;
    unsigned int _service;
    NSString *_transport;
    NSString *_className;
    CDStruct_47010e4b *_currentHeaderInput;
    CDStruct_37378fbc *_currentImageInput;
    CDStruct_bd23d6e8 *_currentAlgsInput;
    CDStruct_e720c65b *_currentDebugInput;
    ALRecorder *_recorder;
}

+ (id)getDefaultDevice;
+ (BOOL)setDefaultDevice:(id)arg1;
+ (id)availableDevices;
@property(retain) NSString *className; // @synthesize className=_className;
- (BOOL)open;
- (int)setOperatingMode:(int)arg1;
@property CDStruct_e720c65b *currentDebugInput; // @synthesize currentDebugInput=_currentDebugInput;
@property CDStruct_bd23d6e8 *currentAlgsInput; // @synthesize currentAlgsInput=_currentAlgsInput;
@property CDStruct_37378fbc *currentImageInput; // @synthesize currentImageInput=_currentImageInput;
@property CDStruct_47010e4b *currentHeaderInput; // @synthesize currentHeaderInput=_currentHeaderInput;
@property(retain) NSString *transport; // @synthesize transport=_transport;
- (int)setAlgsReportAlways:(BOOL)arg1;
- (int)getAlgsReportAlways:(char *)arg1;
- (void)parseInputReport:(char *)arg1 reportID:(unsigned int)arg2 reportLength:(long)arg3;
- (void)unregisterFrameheaderInputCallback:(CDUnknownFunctionPointerType)arg1;
- (void)registerFrameheaderInputCallback:(CDUnknownFunctionPointerType)arg1 withRefcon:(void *)arg2;
- (int)setFeatureReport:(unsigned char)arg1 buffer:(char *)arg2 length:(long)arg3;
- (int)getFeatureReport:(unsigned char)arg1 buffer:(char *)arg2 length:(int *)arg3;
- (void)unregisterForInputCallbacks;
- (void)registerForInputCallbacks;
- (int)getDeviceChipID:(char *)arg1;
- (id)savedNameForDevice;
- (id)initWithHIDDeviceRef:(struct __IOHIDDevice *)arg1;
- (int)getDeviceFWVersions:(unsigned short *)arg1;
- (int)setDebugMode:(BOOL)arg1;
- (int)getDebugMode:(char *)arg1;
- (int)setDACManual:(unsigned short)arg1;
- (int)getDACManual:(unsigned short *)arg1;
- (int)setDACSource:(unsigned char)arg1;
- (int)getDACSource:(unsigned char *)arg1;
- (int)getOperatingMode:(int *)arg1;
- (void)unregisterDebugInputCallback:(CDUnknownFunctionPointerType)arg1;
- (void)registerDebugInputCallback:(CDUnknownFunctionPointerType)arg1 withRefcon:(void *)arg2;
- (void)unregisterAlgsInputCallback:(CDUnknownFunctionPointerType)arg1;
- (void)registerAlgsInputCallback:(CDUnknownFunctionPointerType)arg1 withRefcon:(void *)arg2;
- (void)unregisterImageInputCallback:(CDUnknownFunctionPointerType)arg1;
- (void)registerImageInputCallback:(CDUnknownFunctionPointerType)arg1 withRefcon:(void *)arg2;
- (void).cxx_destruct;
- (BOOL)close;
@property __weak ALRecorder *recorder; // @synthesize recorder=_recorder;
- (void)dealloc;
@property(readonly) unsigned int service; // @synthesize service=_service;

@end

