//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AppleElementsDevice;

@protocol AppleElementsDeviceDelegate <NSObject>

@optional
- (void)inputDataStreamStopped:(AppleElementsDevice *)arg1;
- (void)inputDataStreamStarted:(AppleElementsDevice *)arg1;
@end

