//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "OSDControllerProtocol.h"

@class NSLock, NSString;

@interface OSDBBController : NSObject <OSDControllerProtocol>
{
    float upperErrorLimit;
    float lowerErrorLimit;
    float lastInput;
    float lastOutput;
    _Bool controllerConfigStatus;
    NSLock *resourceLock;
}

@property(nonatomic) float upperErrorLimit; // @synthesize upperErrorLimit;
@property(nonatomic) float lowerErrorLimit; // @synthesize lowerErrorLimit;
- (float)updateControllerMonitoredVariables:(float)arg1;
- (_Bool)pauseController;
- (float)getLastOutput;
- (_Bool)resetController;
- (_Bool)configureController:(id)arg1;
- (void).cxx_destruct;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

