//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_semaphore>, NSOperationQueue, OSDRawGyroDevice;

@interface OSDBumpMonitor : NSObject
{
    struct CLRunningVector3d<float> _gyroFilter;
    NSObject<OS_dispatch_queue> *_monitorQueue;
    NSObject<OS_dispatch_semaphore> *_semaphore;
    struct __CFRunLoop *_runloop;
    OSDRawGyroDevice *_gyro;
    NSOperationQueue *_gyroDataOperationQueue;
    _Bool _activeBumpEvent;
    CDUnknownBlockType _handler;
    NSOperationQueue *_handlerOperationQueue;
    _Bool _monitorStarted;
    float _gyroSampleInterval;
    float _varianceThreshold;
    unsigned int _varianceBufferSize;
    unsigned int _bumpsDetected;
}

- (_Bool)startMonitorOnQueue:(id)arg1 withHandler:(CDUnknownBlockType)arg2 error:(id *)arg3;
- (id)initWithSampleInterval:(float)arg1 varianceThreshold:(float)arg2 varianceBufferSize:(unsigned int)arg3;
@property(readonly, nonatomic) float gyroSampleInterval; // @synthesize gyroSampleInterval=_gyroSampleInterval;
- (void)_gyroDataCallback:(id)arg1;
@property(nonatomic) unsigned int bumpsDetected; // @synthesize bumpsDetected=_bumpsDetected;
@property(readonly, nonatomic) float varianceThreshold; // @synthesize varianceThreshold=_varianceThreshold;
@property(nonatomic) _Bool monitorStarted; // @synthesize monitorStarted=_monitorStarted;
- (void)_spinUpBumpMonitor;
@property(readonly, nonatomic) unsigned int varianceBufferSize; // @synthesize varianceBufferSize=_varianceBufferSize;
- (void).cxx_destruct;
- (id).cxx_construct;
- (id)init;
- (void)dealloc;
- (void)stopMonitor;

@end

