//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSLock, NSMutableDictionary;

@interface OSDCLTMNotificationCenter : NSObject
{
    BOOL _enabled;
    BOOL _supported;
    NSMutableDictionary *_observers;
    int _lastlevel;
    NSLock *_lock;
}

+ (id)defaultCenter;
- (void)removeObserver:(id)arg1 forThermalLevel:(int)arg2;
- (int)addObserver:(id)arg1 withSelector:(SEL)arg2 forThermalLevel:(int)arg3;
- (void)_queryPrefsForCLTMStatus;
- (void)_handleNotification;
@property(readonly, nonatomic) int currentLevel;
- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL isEnabled; // @synthesize isEnabled=_enabled;
- (id)init;
- (void)dealloc;
@property(readonly, nonatomic) BOOL isSupported; // @synthesize isSupported=_supported;

@end

