//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface OSDDisplayDevice : NSObject
{
    struct __IOMobileFramebuffer *_framebuffer;
    struct __IODPDevice *_dpDevice;
    struct __IOAVDevice *_avDevice;
}

- (float)getVRR;
- (_Bool)isDisplayVBLCountIncrementing;
- (id)readEepromLut:(int)arg1 filepath:(id)arg2 error:(id *)arg3;
- (id)readEeprom:(int)arg1 filepath:(id)arg2 error:(id *)arg3;
- (_Bool)programEepromBinary:(int)arg1 filepath:(id)arg2 error:(id *)arg3;
- (_Bool)programEepromLut:(int)arg1 filepath:(id)arg2 error:(id *)arg3;
- (_Bool)reloadEeprom:(id *)arg1;
- (_Bool)setGammaResponseCorrection:(_Bool)arg1 error:(id *)arg2;
- (void)_hexDump:(id)arg1 offset:(unsigned int)arg2 len:(unsigned int)arg3;
- (long)_getTotalVBLCount;
- (struct __IOMobileFramebuffer *)_framebuffer;
- (_Bool)isDisplayVBLCountIncrementingForTime:(double)arg1;
- (int)_readEeprom:(char *)arg1 offset:(unsigned short)arg2 size:(unsigned short)arg3;
- (int)_clearEepromI2CAddrAndProtect:(_Bool)arg1;
- (int)_writeEeprom:(char *)arg1 offset:(unsigned short)arg2 size:(unsigned short)arg3;
- (int)_setEepromI2CAddrAndUnprotect:(_Bool)arg1;
- (_Bool)_createLutFromData:(id)arg1 file:(id)arg2 error:(id *)arg3;
- (id)_accessEeprom:(int)arg1 buffer:(id)arg2 eepromBlock:(int)arg3 error:(id *)arg4;
- (id)_parseTable:(id)arg1 ver:(unsigned short)arg2 error:(id *)arg3;
- (int)_writeRegister:(unsigned char)arg1 offset:(unsigned char)arg2 data:(unsigned char)arg3;
- (int)_readRegister:(unsigned char)arg1 offset:(unsigned char)arg2 data:(char *)arg3;
- (int)_unlockFwAccess;
- (int)_unlockRegAccess;
@property(nonatomic) struct __IOAVDevice *avDevice; // @synthesize avDevice=_avDevice;
@property(nonatomic) struct __IODPDevice *dpDevice; // @synthesize dpDevice=_dpDevice;
- (id)init;
- (void)dealloc;

@end

