//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface OSDEzLink : NSObject
{
    struct {
        CDStruct_d4216171 _field1;
        char *_field2;
        unsigned int _field3;
        void *_field4;
        unsigned int _field5;
        int _field6;
    } *Info;
    unsigned int dockfifoService;
    unsigned int dockfifoConnect;
}

+ (id)link;
- (void)_teardown;
- (int)_setup;
- (int)_writeDockFIFOData:(id)arg1 error:(id *)arg2;
- (id)_readDockFIFODataOfLength:(unsigned int)arg1 timeout:(double)arg2 error:(id *)arg3;
- (id)receiveDataWithTimeout:(double)arg1 error:(id *)arg2;
- (_Bool)sendData:(id)arg1 timeout:(double)arg2 error:(id *)arg3;
- (_Bool)flush:(id *)arg1;
- (int)_flushDockFIFO:(id *)arg1;
- (id)init;
- (void)dealloc;

@end

