//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface OSDHIDEventRef : NSObject
{
    struct __IOHIDEvent *_eventRef;
}

+ (id)refWithIOHIDEventRef:(struct __IOHIDEvent *)arg1;
@property(readonly, nonatomic) struct __IOHIDEvent *hidEventRef; // @synthesize hidEventRef=_eventRef;
- (id)initWithIOHIDEventRef:(struct __IOHIDEvent *)arg1;
- (id)description;

@end

