//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray;

@interface OSDHIDEventSystemClient : NSObject
{
    struct __IOHIDEventSystemClient *_hidClient;
    CDUnknownFunctionPointerType _callback;
    SEL _callbackSel;
    void *_cbTarget;
    void *_cbContext;
    NSMutableArray *_matchingServices;
    int _eventState;
    BOOL __unitTest_timedOut;
}

+ (id)hidClient;
@property(readonly, nonatomic) struct __IOHIDEventSystemClient *ioHIDClient; // @synthesize ioHIDClient=_hidClient;
- (id)startEventsWithCallback:(SEL)arg1 withTarget:(id)arg2;
- (BOOL)setReportInterval:(long)arg1 forAppleUsagePage:(unsigned long)arg2;
- (BOOL)setProperty:(id)arg1 withValue:(id)arg2 forService:(struct __IOHIDServiceClient *)arg3;
- (BOOL)setProperty:(id)arg1 withValue:(id)arg2;
- (id)getProperty:(id)arg1;
- (BOOL)service:(struct __IOHIDServiceClient *)arg1 matchesAppleUsage:(unsigned long)arg2;
- (void)addAllAppleServicesForMatching;
- (void)removeAllMatchedServices;
- (id)initWithClientType:(int)arg1;
@property(readonly, nonatomic) __weak NSArray *matchedServices; // @dynamic matchedServices;
- (id)startEventsWithCallback:(CDUnknownFunctionPointerType)arg1 target:(void *)arg2 andContext:(void *)arg3;
- (BOOL)setReportInterval:(long)arg1 forService:(struct __IOHIDServiceClient *)arg2;
- (struct __IOHIDServiceClient *)getAppleServiceForUsage:(unsigned long)arg1;
- (struct __IOHIDServiceClient *)getServiceForPrimaryUsage:(unsigned long)arg1 andUsage:(unsigned long)arg2;
- (id)getProperty:(id)arg1 forService:(struct __IOHIDServiceClient *)arg2;
- (BOOL)service:(struct __IOHIDServiceClient *)arg1 matchesPrimaryUsage:(unsigned long)arg2 andUsage:(unsigned long)arg3;
- (void)addAppleServiceForMatching:(unsigned long)arg1;
- (void)addUsagePage:(unsigned long)arg1 andServiceForMatching:(unsigned long)arg2;
- (void)stopEvents;
- (void)_resetMatchingServices;
- (BOOL)_setProperty:(struct __CFString *)arg1 forService:(struct __IOHIDServiceClient *)arg2 withValue:(void *)arg3;
- (void)_callbackBounceWithEvent:(id)arg1;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end

