//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@interface OSDIOAccessory : NSObject
{
    unsigned int _accessoryService;
    unsigned int _accessoryIterator;
    unsigned int _accessoryNotification;
    struct IONotificationPort *_notificationPort;
    id <OSDIOAccessoryDelegate> _delegate;
}

+ (void)initialize;
+ (id)sharedInstance;
@property(readonly, getter=_TriStarREV) int TriStarREV;
@property(readonly, getter=_IOUserClientClass) __weak NSString *IOUserClientClass;
@property(readonly, getter=_IOProviderClass) __weak NSString *IOProviderClass;
@property(readonly, getter=_IONameMatched) __weak NSString *IONameMatched;
@property(readonly, getter=_IOMatchCategory) __weak NSString *IOMatchCategory;
@property(readonly, getter=_IOGeneralInterest) __weak NSString *IOGeneralInterest;
@property(readonly, getter=_IOClass) __weak NSString *IOClass;
@property(readonly, getter=_IONameMatch) __weak NSArray *IONameMatch;
@property(readonly, getter=_IOAccessoryPowerCurrentLimits) __weak NSArray *IOAccessoryPowerCurrentLimits;
@property(readonly, getter=_IOAccessorySupportedPowerModes) __weak NSArray *IOAccessorySupportedPowerModes;
@property(readonly, getter=_IOProbeScore) int IOProbeScore;
@property(readonly, getter=_IOAccessoryUSBCurrentLimitOffset) int IOAccessoryUSBCurrentLimitOffset;
@property(readonly, getter=_IOAccessoryUSBCurrentLimitBase) int IOAccessoryUSBCurrentLimitBase;
@property(readonly, getter=_IOAccessoryUSBCurrentLimit) int IOAccessoryUSBCurrentLimit;
@property(readonly, getter=_IOAccessoryUSBConnectType) int IOAccessoryUSBConnectType;
@property(readonly, getter=_IOAccessoryPrimaryDevicePort) int IOAccessoryPrimaryDevicePort;
@property(readonly, getter=_IOAccessoryPowerMode) int IOAccessoryPowerMode;
@property(readonly, getter=_IOAccessoryOrientation) int IOAccessoryOrientation;
@property(readonly, getter=_IOAccessoryManagerType) int IOAccessoryManagerType;
@property(readonly, getter=_IOAccessoryManagerSystemID) int IOAccessoryManagerSystemID;
@property(readonly, getter=_IOAccessoryID) int IOAccessoryID;
@property(readonly, getter=_IOAccessoryUSBActive) BOOL IOAccessoryUSBActive;
@property(readonly, getter=_IOAccessoryPowerHandshake) BOOL IOAccessoryPowerHandshake;
@property(readonly, getter=_IOAccessoryUSBPower) BOOL IOAccessoryUSBPower;
@property(readonly, getter=_IOAccessoryManagerSleepPower) BOOL IOAccessoryManagerSleepPower;
@property(readonly, getter=_IOAccessoryDetect) BOOL IOAccessoryDetect;
@property(readonly, getter=_CFBundleIdentifier) __weak NSString *CFBundleIdentifier;
- (void)_OSDIOAccessoryInterestHandler:(unsigned int)arg1 messageType:(unsigned int)arg2 messageArgument:(void *)arg3;
- (struct IONotificationPort *)_getAccessoryNotificationPort;
@property(readonly, getter=_getAccessoryProperties) __weak NSDictionary *getAccessoryProperties;
@property(readonly, getter=_getAccessoryService) unsigned int getAccessoryService;
- (void).cxx_destruct;
@property(nonatomic) __weak id <OSDIOAccessoryDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;
- (void)dealloc;

@end

