//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <FactoryDiags/OSDLisaCallbackData.h>

@interface OSDLisaAlgsData : OSDLisaCallbackData
{
}

@property(readonly, nonatomic) unsigned int timeDelta;
@property(readonly, nonatomic) unsigned short fingerDetect;
@property(readonly, nonatomic) short countDelta;
@property(readonly, nonatomic) unsigned short countsPerRevolution;
@property(readonly, nonatomic) unsigned char packetTrigger;

@end

