//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <FactoryDiags/OSDLisaCallbackData.h>

@class NSArray;

@interface OSDLisaDebugData : OSDLisaCallbackData
{
}

@property(readonly, nonatomic) NSArray *scanTypeValues;
@property(readonly, nonatomic) NSArray *ePhaseValues;

@end

