//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface OSDLisaCallbackData : NSObject
{
    NSData *_inputHeader;
    NSData *_summary;
}

- (int)calibrationCookie;
- (int)DACValue;
- (int)DACSource;
- (int)buttonState;
- (int)payloadLength;
- (int)frameNumber;
- (int)frameType;
- (id)initWithInputHeader:(id)arg1 inputSummary:(id)arg2;
- (void).cxx_destruct;
- (int)timestamp;

@end

