//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AppleLisaHIDDevice, NSMutableDictionary;

@interface OSDLisa : NSObject
{
    NSMutableDictionary *_imageOperationQueueTable;
    NSMutableDictionary *_algsOperationQueueTable;
    NSMutableDictionary *_debugOperationQueueTable;
    AppleLisaHIDDevice *_lisaDevice;
    _Bool _imageCallbackRegistered;
    _Bool _algsCallbackRegistered;
    _Bool _debugCallbackRegistered;
}

- (unsigned int)operatingMode;
- (_Bool)setOperatingMode:(unsigned int)arg1;
- (id)_debugOperationQueueTable;
- (id)_algsOperationQueueTable;
- (id)_imageOperationQueueTable;
- (unsigned short)deviceFirmwareVersion;
- (_Bool)debugMode;
- (unsigned short)getDACManual;
- (void)stopLisaDebugUpdates;
- (void)startLisaDebugUpdatesToQueue:(id)arg1 withHandler:(CDUnknownBlockType)arg2;
- (void)stopLisaAlgsUpdates;
- (void)startLisaAlgsUpdatesToQueue:(id)arg1 withHandler:(CDUnknownBlockType)arg2;
- (void)stopLisaImageUpdates;
- (void)startLisaImageUpdatesToQueue:(id)arg1 withHandler:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) _Bool lisaAvailable;
- (_Bool)setDebugMode:(_Bool)arg1;
- (_Bool)setDACManual:(unsigned short)arg1;
- (_Bool)setDACSource:(unsigned char)arg1;
- (unsigned char)DACSource;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end

