//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface OSDLaunch : NSObject
{
}

+ (id)copyJobDictionary:(id)arg1;
+ (_Bool)unload:(id)arg1;
+ (_Bool)load:(id)arg1;

@end

