//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSObject<OS_dispatch_queue>;

@interface OSDMesaDevice : NSObject
{
    CDStruct_217a53aa *_cachedStatus;
    _Bool _driverExists;
    _Bool _fwLoaded;
    NSObject<OS_dispatch_queue> *_queue;
    struct AppleMesaInterfaceStruct **_mesaInterface;
    unsigned int _ioService;
    unsigned int _mesaConnect;
}

+ (id)mesaDevice;
+ (_Bool)_isFirmwareLoadedIn:(CDStruct_217a53aa *)arg1;
@property(readonly, nonatomic) _Bool driverExists; // @synthesize driverExists=_driverExists;
- (_Bool)setFingerDetectMode:(_Bool)arg1;
@property(readonly, nonatomic) _Bool inCaptureMode; // @dynamic inCaptureMode;
@property(readonly, nonatomic) _Bool inFingerDetectMode; // @dynamic inFingerDetectMode;
@property(readonly, nonatomic) _Bool inIdleMode; // @dynamic inIdleMode;
- (id)calibrationSource;
@property(readonly, nonatomic) __weak NSNumber *patchRevision; // @dynamic patchRevision;
- (void)_disconnectMesaDevice;
- (_Bool)_connectMesaDevice;
- (_Bool)_isSensorInMode:(int)arg1;
- (BOOL)_deviceExists;
- (void)_checkForAndLoadFirmware;
- (int)_refreshCachedStatus;
- (int)_getStatusInto:(CDStruct_217a53aa *)arg1;
@property(readonly, nonatomic) _Bool isFirmwareLoaded; // @dynamic isFirmwareLoaded;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end

