//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSMutableArray, NSMutableDictionary, NSString;

@interface OSDPDCATestSequence : NSObject
{
    NSMutableArray *_results;
    NSDate *_startTime;
    NSDate *_stopTime;
    NSString *_serialNumber;
    NSString *_softwareName;
    NSString *_softwareVersion;
    NSString *_limitsVersion;
    NSMutableDictionary *_deviceAttributes;
}

@property(retain, nonatomic) NSDate *stopTime; // @synthesize stopTime=_stopTime;
@property(retain, nonatomic) NSMutableDictionary *deviceAttributes; // @synthesize deviceAttributes=_deviceAttributes;
- (id)initWithSerialNumber:(id)arg1 softwareName:(id)arg2 softwareVersion:(id)arg3 startTime:(id)arg4 stopTime:(id)arg5 limitsVersion:(id)arg6 deviceAttributes:(id)arg7;
@property(readonly, nonatomic) _Bool overallResult;
@property(copy, nonatomic) NSString *serialNumber; // @synthesize serialNumber=_serialNumber;
@property(copy, nonatomic) NSString *limitsVersion; // @synthesize limitsVersion=_limitsVersion;
- (id)makeAlphanumericString:(id)arg1;
- (_Bool)stringIsAlphanumericPeriod:(id)arg1;
@property(copy, nonatomic) NSString *softwareVersion; // @synthesize softwareVersion=_softwareVersion;
@property(copy, nonatomic) NSString *softwareName; // @synthesize softwareName=_softwareName;
- (id)initWithDictionary:(id)arg1 timeZone:(id)arg2;
- (void)addResult:(id)arg1;
@property(retain, nonatomic) NSMutableArray *results; // @synthesize results=_results;
@property(retain, nonatomic) NSDate *startTime; // @synthesize startTime=_startTime;
- (void).cxx_destruct;
- (id)dictionary;
- (id)initWithDictionary:(id)arg1;
- (id)init;

@end

