//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray;

@interface OSDPDCAObject : NSObject
{
    NSMutableArray *_internalTestSequences;
}

- (id)currentResult;
- (id)currentTestSequence;
@property(retain, nonatomic) NSMutableArray *internalTestSequences; // @synthesize internalTestSequences=_internalTestSequences;
- (void)addTestSequence:(id)arg1;
@property(readonly, nonatomic) NSArray *testSequences;
- (id)initWithDictionary:(id)arg1 timeZone:(id)arg2;
- (void)addResult:(id)arg1;
- (void).cxx_destruct;
- (id)dictionary;
- (id)initWithDictionary:(id)arg1;
- (id)init;

@end

