//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AEOpalPlatinumDeviceDelegate.h"
#import "AppleElementsManagerDelegate.h"

@class AEOpalPlatinumDevice, AppleElementsManager, NSMutableDictionary, NSString, OSDPlatinumData;

@interface OSDPlatinum : NSObject <AppleElementsManagerDelegate, AEOpalPlatinumDeviceDelegate>
{
    NSMutableDictionary *_operationQueueTable;
    AppleElementsManager *_elementsManager;
    AEOpalPlatinumDevice *_platinumDevice;
    _Bool _startedDataStream;
    OSDPlatinumData *_platinumData;
}

- (void)appleElementsPlatinumInput:(CDStruct_34fda668 *)arg1 device:(id)arg2;
- (void)deviceManager:(id)arg1 removedDevice:(id)arg2;
- (void)deviceManager:(id)arg1 addedDevice:(id)arg2;
- (void)_setPlatinumData:(id)arg1;
- (id)_operationQueueTable;
@property(retain, nonatomic) OSDPlatinumData *platinumData; // @synthesize platinumData=_platinumData;
- (_Bool)setScanSchedule:(unsigned char)arg1;
- (unsigned char)scanSchedule;
- (_Bool)setDigiPotSource:(unsigned char)arg1;
- (unsigned char)digiPotSource;
- (void)stopPlatinumUpdates;
- (void)startPlatinumUpdates;
@property(readonly, nonatomic) _Bool platinumAvailable;
- (void)startPlatinumUpdatesToQueue:(id)arg1 withHandler:(CDUnknownBlockType)arg2;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

