//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSOperationQueue, OSDSPU;

@interface OSDRawGyroDevice : NSObject
{
    NSOperationQueue *_operationQueue;
    struct __IOHIDEventSystemClient *_HIDSystemClient;
    struct __IOHIDServiceClient *_GyroPlugin;
    NSMutableArray *_samples;
    double _lastTimestamp;
    BOOL _getTemperature;
    SEL _registeredCallback;
    id _registeredDelegate;
    OSDSPU *_spu;
    BOOL getTemperature;
}

@property(nonatomic) struct __IOHIDServiceClient *_GyroPlugin; // @synthesize _GyroPlugin;
@property(readonly, nonatomic) float resonantFreq;
- (id)sampleForDuration:(float)arg1 sampleInterval:(float)arg2 withTemperature:(BOOL)arg3 lowPassFilter:(int)arg4;
- (void)_adjustGyroMultByType;
- (struct __IOHIDServiceClient *)getGyroPlugin;
- (struct __IOHIDEventSystemClient *)getHIDSystem;
- (void)enqueueCallback:(id)arg1;
@property(readonly, nonatomic, getter=_getTemperature) BOOL getTemperature; // @synthesize getTemperature;
- (void)sampleForDurationCallback:(id)arg1;
- (void)unregisterGyroCallbackIOKit;
- (int)registerGyroCallbackIOKit:(float)arg1 withTemperature:(BOOL)arg2 lowPassFilter:(int)arg3;
- (void)unregisterGyroCallback;
- (int)registerGyroCallback:(SEL)arg1 delegate:(id)arg2 operationQueue:(id)arg3 sampleInterval:(float)arg4 withTemperature:(BOOL)arg5 lowPassFilter:(int)arg6;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end

