//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSecureCoding.h"

@class NSMutableDictionary, NSString, OSDPDCAObject;

@interface OSDSimplePDCAObject : NSObject <NSSecureCoding>
{
    NSString *_softwareName;
    NSString *_softwareVersion;
    NSString *_limitsVersion;
    NSMutableDictionary *_deviceAttributes;
    OSDPDCAObject *_pdca;
    unsigned int _currentRetest;
}

+ (id)objectsInPDCADictionary;
+ (BOOL)supportsSecureCoding;
@property(retain, nonatomic) NSMutableDictionary *deviceAttributes; // @synthesize deviceAttributes=_deviceAttributes;
- (_Bool)loadFromDictionary:(id)arg1;
- (_Bool)addDeviceAttribute:(id)arg1 value:(id)arg2;
- (_Bool)addParametricTestNamed:(id)arg1 passed:(_Bool)arg2 value:(id)arg3 subtest:(id)arg4 subsubtest:(id)arg5 lowerLimit:(id)arg6 upperLimit:(id)arg7 units:(id)arg8 failureMessage:(id)arg9 priority:(unsigned int)arg10;
- (_Bool)addPassFailTestNamed:(id)arg1 passed:(_Bool)arg2 subtest:(id)arg3 subsubtest:(id)arg4 failureMessage:(id)arg5 priority:(unsigned int)arg6;
- (void)incrementResultGroup;
- (_Bool)loadFromPath:(id)arg1;
- (void)ensureEnoughTestSequences:(unsigned long)arg1;
@property(nonatomic) unsigned int currentRetest; // @synthesize currentRetest=_currentRetest;
@property(retain, nonatomic) OSDPDCAObject *pdca; // @synthesize pdca=_pdca;
@property(retain, nonatomic) NSString *limitsVersion; // @synthesize limitsVersion=_limitsVersion;
@property(retain, nonatomic) NSString *softwareVersion; // @synthesize softwareVersion=_softwareVersion;
@property(retain, nonatomic) NSString *softwareName; // @synthesize softwareName=_softwareName;
- (void).cxx_destruct;
- (id)dictionary;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

