//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface OSDSeajay : NSObject
{
    unsigned int seajayService;
    unsigned int seajayConnect;
}

- (_Bool)readUSBPowerInfo:(char *)arg1 currentAvailable:(unsigned short *)arg2 error:(id *)arg3;
- (_Bool)readThermistor:(unsigned char)arg1 value:(char *)arg2 error:(id *)arg3;
- (_Bool)readVBusPower:(unsigned short *)arg1 isenseOVP:(unsigned short *)arg2 error:(id *)arg3;
- (_Bool)readCoilPower:(unsigned short *)arg1 isenseIDT:(unsigned short *)arg2 error:(id *)arg3;
- (id)remoteSerialNumber:(id *)arg1;
- (id)remoteModelNumber:(id *)arg1;
- (id)remoteProductName:(id *)arg1;
- (id)remoteVendorName:(id *)arg1;
- (id)remoteFirmwareRevision:(id *)arg1;
- (id)remoteHardwareRevision:(id *)arg1;
- (_Bool)loopback:(id)arg1 timeout:(double)arg2 error:(id *)arg3;
- (id)_readConfigurationStringWithIndex:(unsigned char)arg1 error:(id *)arg2;
- (id)_sendTelegramOnStream:(unsigned char)arg1 returnStream:(unsigned char)arg2 data:(id)arg3 telegram:(_Bool)arg4 timeout:(double)arg5 error:(id *)arg6;
- (id)resetCount:(id *)arg1;
- (_Bool)setConnectState:(unsigned char)arg1 error:(id *)arg2;
- (_Bool)engageCloak:(BOOL)arg1 error:(id *)arg2;
- (_Bool)sendEndTestPacket:(id *)arg1;
- (_Bool)sendStartTestPacket:(id *)arg1;
- (id)irectADC;
- (id)firmwareVersion;
- (id)dummyLoad;
- (id)vrectTarget;
- (id)vrectADC;
- (_Bool)_write8BitRegister:(unsigned int)arg1 value:(unsigned char)arg2 error:(id *)arg3;
- (unsigned char)connectState:(id *)arg1;
- (unsigned short)_read16BitRegister:(unsigned int)arg1 error:(id *)arg2;
- (unsigned char)_read8BitRegister:(unsigned int)arg1 error:(id *)arg2;
- (id)statusBits;
- (void)_closeC26Service:(unsigned int)arg1 connect:(unsigned int)arg2;
- (_Bool)_openC26Service:(unsigned int *)arg1 connect:(unsigned int *)arg2;
- (_Bool)connected;
- (id)frequency;
- (id)init;
- (void)dealloc;

@end

