//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary;

@interface OSDSensors : NSObject
{
    NSArray *syntheticSensors;
    NSDictionary *_sensorModels;
}

+ (void)initialize;
+ (id)sharedInstance;
- (id)sensorNamesForType:(int)arg1;
- (float)readSensor:(id)arg1 type:(int)arg2;
- (float)readSensorByID:(id)arg1 type:(int)arg2;
@property(copy, nonatomic) NSArray *syntheticSensors; // @synthesize syntheticSensors;
- (id)readSensor:(id)arg1 type:(int)arg2 error:(id *)arg3;
- (id)readSensorByID:(id)arg1 type:(int)arg2 error:(id *)arg3;
- (id)getSensorsForType:(int)arg1 sortByID:(_Bool)arg2;
@property(retain, nonatomic) NSDictionary *sensorModels; // @synthesize sensorModels=_sensorModels;
- (void).cxx_destruct;
- (id)init;

@end

