//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface OSDSPUDevice : NSObject
{
}

- (unsigned int)_findHIDDevice:(id)arg1 error:(id *)arg2;
- (struct __CFDictionary *)_serviceIDMatching:(int)arg1;
- (unsigned int)_findInterface:(id)arg1 error:(id *)arg2;
- (id)_callMethodWithInterfaceName:(id)arg1 methodID:(unsigned int)arg2 input:(unsigned long long *)arg3 inputCnt:(unsigned int)arg4 inPayload:(id)arg5 error:(id *)arg6;
- (id)deviceCalibration:(id)arg1 error:(id *)arg2;
- (id)deviceModel:(id)arg1 error:(id *)arg2;
- (id)deviceManufacturer:(id)arg1 error:(id *)arg2;
- (_Bool)waitForReadyWithTimeout:(double)arg1 error:(id *)arg2;
- (id)_getDeviceProperty:(id)arg1 withID:(unsigned long long)arg2 error:(id *)arg3;
- (_Bool)ready:(id *)arg1;
- (void)_teardownSPUService:(unsigned int)arg1 connect:(unsigned int)arg2 notifyPort:(struct IONotificationPort *)arg3 notifyHandle:(unsigned int)arg4;
- (int)_setupSPUService:(unsigned int *)arg1 connect:(unsigned int *)arg2 notifyPort:(struct IONotificationPort **)arg3 notifyHandle:(unsigned int *)arg4 notifyBlock:(CDUnknownBlockType)arg5;
- (id)_performSPUAppCommandWithPacketType:(unsigned int)arg1 inPayload:(id)arg2 error:(id *)arg3;
- (id)firmwareVersion:(id *)arg1;
- (id)startupTimeForDevice:(id)arg1 error:(id *)arg2;
- (id)sampleRatesForDevice:(id)arg1 error:(id *)arg2;
- (_Bool)forceSPUPanic:(id)arg1;
- (_Bool)requestSystemWake:(unsigned int)arg1 error:(id *)arg2;

@end

