//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSFileHandle, NSMutableDictionary;

@interface OSDThermalVirusLauncher : NSObject
{
    NSMutableDictionary *processList;
    _Bool virus_level_changed;
    int current_virus_level;
    int current_duty_cycle;
    NSFileHandle *_stdoutFH;
    NSFileHandle *_stderrFH;
}

@property(readonly, getter=_getVirusLevel) int virusLevel;
- (void)cleanupViruses;
- (_Bool)launchVirus:(id)arg1 withRelaunchFlag:(_Bool)arg2;
- (void)verifyVirusesAreRunning;
- (void)killAllActiveViruses;
- (_Bool)initializeTaskHandler:(id)arg1 withLaunchPath:(id)arg2 arguments:(id)arg3 stdError:(id)arg4 stdOutput:(id)arg5;
@property(retain, nonatomic) NSFileHandle *stderrFH; // @synthesize stderrFH=_stderrFH;
@property(retain, nonatomic) NSFileHandle *stdoutFH; // @synthesize stdoutFH=_stdoutFH;
@property(readonly, getter=_getDutyCycle) int dutyCycle;
- (_Bool)addHeatingProcess:(id)arg1 withLevel:(int)arg2 ofType:(int)arg3;
- (_Bool)setThermalVirusLevel:(int)arg1;
- (_Bool)setThermalVirusDutyCycle:(int)arg1;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end

