//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSObject<OS_dispatch_source>, NSString;

@interface OSDTask : NSObject
{
    NSArray *curArguments;
    NSDictionary *curEnvironment;
    NSString *curLaunchPath;
    NSString *curDirPath;
    id curstdErr;
    id curstdInput;
    id curstdOutput;
    NSObject<OS_dispatch_source> *processSource;
    unsigned int suspendCounter;
    int returnStatus;
    int taskStatusInfo;
    int taskState;
    int curPid;
    CDUnknownBlockType _terminationHandler;
}

+ (id)launchWithShell:(id)arg1;
+ (id)launchedTaskWithLaunchPath:(id)arg1 arguments:(id)arg2;
- (id)arguments;
- (void)setEnvironment:(id)arg1;
- (int)getReturnValueAndKillAfterTimeout:(double)arg1;
- (void)killAfterUnsuccessfulTermination;
- (void)killAfterUnsuccessfulTerminationWithTimeout:(double)arg1;
- (void)kill;
- (void)sendSignal:(int)arg1;
- (_Bool)waitUntilExitWithTimeout:(double)arg1;
@property(copy, nonatomic) CDUnknownBlockType terminationHandler; // @synthesize terminationHandler=_terminationHandler;
- (int)processIdentifier;
- (void).cxx_destruct;
- (_Bool)isRunning;
- (_Bool)resume;
- (_Bool)suspend;
- (id)environment;
- (id)init;
- (void)dealloc;
- (void)waitUntilExit;
- (id)standardError;
- (id)standardOutput;
- (id)standardInput;
- (void)setStandardError:(id)arg1;
- (void)setStandardOutput:(id)arg1;
- (void)setStandardInput:(id)arg1;
- (id)launchPath;
- (void)interrupt;
- (void)setLaunchPath:(id)arg1;
- (void)setCurrentDirectoryPath:(id)arg1;
- (void)launch;
- (int)terminationReason;
- (int)terminationStatus;
- (void)setArguments:(id)arg1;
- (id)currentDirectoryPath;
- (void)terminate;

@end

