//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface OSDVersion : NSObject
{
    NSString *rootVersion;
    NSDictionary *_OSDVersionInfo;
    NSDictionary *_LLDVersionInfo;
}

+ (id)sharedInstance;
- (id)factoryLLScriptsCommonVersion;
- (id)factoryLLDiagsExtrasVersion;
- (id)factoryLLScriptsPlatformsVersion;
- (id)factoryLLDiagsVersion;
- (id)rootVersionLLD;
@property(readonly, nonatomic) NSString *rootVersion; // @synthesize rootVersion;
@property(retain, nonatomic) NSDictionary *LLDVersionInfo; // @synthesize LLDVersionInfo=_LLDVersionInfo;
@property(retain, nonatomic) NSDictionary *OSDVersionInfo; // @synthesize OSDVersionInfo=_OSDVersionInfo;
- (id)rootVersionOSD;
- (void).cxx_destruct;
- (id)init;

@end

