//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSMutableDictionary, NSString, OSDWiFiNetwork;

@interface OSDWiFiManager : NSObject
{
    struct _Apple80211 *_wireless;
    struct __SCDynamicStore *_store;
    struct __SCPreferences *_prefs;
    NSDictionary *_wirelessDict;
    NSMutableDictionary *_configCategories;
    struct __SCNetworkInterface *_interface;
    struct __SCNetworkService *_service;
    NSArray *_dynamicStoreKeys;
    OSDWiFiNetwork *_current;
    NSMutableDictionary *_networks;
    NSMutableDictionary *_favorites;
    BOOL _networksChanged;
    NSMutableDictionary *_decayDict;
    NSString *_interfaceName;
    NSString *_macAddress;
    BOOL _isConnected;
    BOOL _enabled;
    int _autojoin;
    BOOL _associating;
    BOOL _isDirty;
    BOOL _macWorldChannels;
    int _scanningMode;
    OSDWiFiNetwork *_scanFor;
    OSDWiFiNetwork *_deferredJoin;
}

+ (void)initialize;
+ (id)sharedInstance;
- (id)_interfaceName;
- (void)setTxPower:(int)arg1;
- (int)txPower;
- (void)setTxBitrate:(int)arg1;
- (int)txBitrate;
- (int)signalStrengthForDict:(id)arg1;
- (BOOL)networkIsFavorite:(id)arg1;
- (void)forgetNetwork:(id)arg1;
- (void)cleanupNetworks;
- (void)removeNetworkNamed:(id)arg1;
- (id)availableNetworks;
- (void)setProxyPassword:(id)arg1 network:(id)arg2;
- (void)setProxyUsername:(id)arg1 network:(id)arg2;
- (void)setProxyUsesAuthentication:(BOOL)arg1 network:(id)arg2;
- (void)setProxyPort:(id)arg1 network:(id)arg2;
- (void)setProxyServer:(id)arg1 network:(id)arg2;
- (void)setPassword:(id)arg1 network:(id)arg2;
- (void)setUsername:(id)arg1 network:(id)arg2;
- (void)setSecurityType:(int)arg1 network:(id)arg2;
- (int)autojoinMode;
- (void)setDNSServers:(id)arg1 network:(id)arg2;
- (void)setSearchDomains:(id)arg1 network:(id)arg2;
- (void)setSubnetMask:(id)arg1 network:(id)arg2;
- (void)setRouterAddress:(id)arg1 network:(id)arg2;
- (void)setIPAddress:(id)arg1 network:(id)arg2;
- (void)setConfigurationType:(int)arg1 network:(id)arg2;
- (void)setDHCPClientID:(id)arg1 network:(id)arg2;
- (void)renewLease;
- (id)macAddress;
- (id)currentNetwork:(BOOL)arg1;
- (id)currentNetworkInfo;
- (void)_setupAirportHardwareEntity;
- (void)__scanComplete:(id)arg1;
- (void)_loadFavorites;
- (void)_saveFavorites;
- (id)_arrayFromCommaSeparatedString:(id)arg1;
- (void)_setSCValue:(id)arg1 forKey:(struct __CFString *)arg2 protocol:(struct __CFString *)arg3;
- (void)_updateAutojoinInformation;
- (void)_checkIsCurrentNetwork:(id)arg1;
- (void)configureJoinDict:(struct __CFDictionary *)arg1 forWPAType:(int)arg2;
- (BOOL)scanForNetwork:(id)arg1;
- (void)joinNetwork:(id)arg1;
- (void)_setInterfaceConfigValue:(id)arg1 forKey:(struct __CFString *)arg2;
- (void)_addNetworkForDictionary:(id)arg1;
- (id)_networkFromDictionary:(id)arg1;
- (void)setAutojoinMode:(int)arg1;
- (void)_getCurrentNetworkInfo;
- (void)_initDynamicStoreMonitor;
- (void)_initServiceInterface;
- (void)_configurationChanged:(unsigned char)arg1;
- (void)_scanComplete:(id)arg1 error:(int)arg2;
- (void)_dynamicStoreChanged;
- (BOOL)connected;
- (void)_load;
- (void)_save;
- (void).cxx_destruct;
- (BOOL)enabled;
- (BOOL)setEnabled:(BOOL)arg1;
- (id)init;
- (void)dealloc;
- (void)save;
- (struct __SCDynamicStore *)store;

@end

