//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <WebCore/DOMObject.h>

@class DOMNode;

@interface DOMNodeIterator : DOMObject
{
}

- (id)previousNode;
@property(readonly) BOOL pointerBeforeReferenceNode;
@property(readonly) DOMNode *referenceNode;
@property(readonly) BOOL expandEntityReferences;
@property(readonly) unsigned int whatToShow;
@property(readonly) DOMNode *root;
- (void)finalize;
@property(readonly) id <DOMNodeFilter> filter;
- (id)nextNode;
- (void)detach;
- (void)dealloc;

@end

