//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class MKMapItem, _MKNanoAddressSnapshotView;

@interface _MKNanoPlaceCardFooterView : UITableViewCell
{
    _MKNanoAddressSnapshotView *_snapshotView;
}

@property(retain, nonatomic) MKMapItem *mapItem;
@property(nonatomic) unsigned int pinColor;
- (void).cxx_destruct;
- (void)setNeedsUpdateConstraints;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
@property(nonatomic) BOOL showsName;
- (void)preloadSnapshotForWidth:(float)arg1;

@end

