//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PUICTableViewCell.h"

@class UIFont, UIImage, UIImageView, UILabel, _MKAutoLayoutContext;

@interface _MKNanoPillTableViewLabelCell : PUICTableViewCell
{
    UIFont *_pillBaseFont;
    _MKAutoLayoutContext *_context;
    UILabel *_titleLabel;
    UIImageView *_leftImageView;
    UIImageView *_rightImageView;
    BOOL _usingStandardFont;
    UIImage *_leftImage;
    UIImage *_rightImage;
}

+ (BOOL)usesConstraintBasedLayout;
+ (BOOL)requiresConstraintBasedLayout;
+ (void)initialize;
- (void).cxx_destruct;
- (void)setTitleText:(id)arg1;
- (void)updateConstraints;
- (void)setNumberOfLines:(unsigned int)arg1;
- (void)prepareForReuse;
- (struct CGSize)systemLayoutSizeFittingSize:(struct CGSize)arg1 withHorizontalFittingPriority:(float)arg2 verticalFittingPriority:(float)arg3;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;
@property(retain, nonatomic) UIImage *rightImage; // @synthesize rightImage=_rightImage;
- (void)setAttributedTitleText:(id)arg1;
- (void)textSizeChanged;
@property(retain, nonatomic) UIImage *leftImage; // @synthesize leftImage=_leftImage;

@end

