//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MapKit/MKStackingViewController.h>

@class ABPeoplePickerNavigationController, CNContact, MKMapItem, NSString;

@interface _MKPlaceViewController : MKStackingViewController
{
    BOOL _showShareActionsButton;
    BOOL _showEditButton;
    BOOL _showTitleBar;
    BOOL _hideDirectionsButtons;
    BOOL _hideInlineMap;
    BOOL _showInlineMapInHeader;
    BOOL _showNearbyApps;
    BOOL _showRemovePin;
    BOOL _showReportAProblem;
    BOOL _disableReportAProblem;
    BOOL _showRerouting;
    BOOL _showFlyoverTour;
    BOOL _showContactActions;
    BOOL _showCreateReminder;
    BOOL _showSimulateLocation;
    BOOL _showOpenInSkyline;
    MKMapItem *_mapItem;
    NSString *_headerTitle;
    float _headerHeight;
    id <_MKPlaceViewControllerDelegate> _placeViewControllerDelegate;
    CNContact *_contact;
    ABPeoplePickerNavigationController *_contactsNavigationController;
}

- (id)initWithMapItem:(id)arg1;
@property(retain, nonatomic) MKMapItem *mapItem; // @synthesize mapItem=_mapItem;
@property(copy, nonatomic) NSString *headerTitle; // @synthesize headerTitle=_headerTitle;
@property(nonatomic) float headerHeight; // @synthesize headerHeight=_headerHeight;
- (void).cxx_destruct;
@property(nonatomic) __weak ABPeoplePickerNavigationController *contactsNavigationController; // @synthesize contactsNavigationController=_contactsNavigationController;
@property(nonatomic) __weak id <_MKPlaceViewControllerDelegate> placeViewControllerDelegate; // @synthesize placeViewControllerDelegate=_placeViewControllerDelegate;
@property(nonatomic) BOOL showOpenInSkyline; // @synthesize showOpenInSkyline=_showOpenInSkyline;
@property(nonatomic) BOOL showSimulateLocation; // @synthesize showSimulateLocation=_showSimulateLocation;
@property(nonatomic) BOOL showCreateReminder; // @synthesize showCreateReminder=_showCreateReminder;
@property(nonatomic) BOOL showContactActions; // @synthesize showContactActions=_showContactActions;
@property(nonatomic) BOOL showFlyoverTour; // @synthesize showFlyoverTour=_showFlyoverTour;
@property(nonatomic) BOOL showRerouting; // @synthesize showRerouting=_showRerouting;
@property(nonatomic) BOOL disableReportAProblem; // @synthesize disableReportAProblem=_disableReportAProblem;
@property(nonatomic) BOOL showReportAProblem; // @synthesize showReportAProblem=_showReportAProblem;
@property(nonatomic) BOOL showRemovePin; // @synthesize showRemovePin=_showRemovePin;
@property(nonatomic) BOOL showNearbyApps; // @synthesize showNearbyApps=_showNearbyApps;
@property(nonatomic) BOOL showInlineMapInHeader; // @synthesize showInlineMapInHeader=_showInlineMapInHeader;
@property(nonatomic) BOOL hideInlineMap; // @synthesize hideInlineMap=_hideInlineMap;
@property(nonatomic) BOOL hideDirectionsButtons; // @synthesize hideDirectionsButtons=_hideDirectionsButtons;
@property(nonatomic) BOOL showTitleBar; // @synthesize showTitleBar=_showTitleBar;
@property(nonatomic) BOOL showEditButton; // @synthesize showEditButton=_showEditButton;
@property(nonatomic) BOOL showShareActionsButton; // @synthesize showShareActionsButton=_showShareActionsButton;
- (void)_openInfoAttribution;
- (void)updateActionVisibility;
- (void)setMapItem:(id)arg1 contact:(id)arg2 updateOriginalContact:(BOOL)arg3;
- (void)removeAdditionalViewController:(id)arg1;
- (void)addAdditionalViewController:(id)arg1 atPosition:(int)arg2;
- (id)additionalViewControllersAtPosition:(int)arg1;
- (id)initWithContact:(id)arg1 mapItem:(id)arg2;
@property(readonly, nonatomic) CNContact *contact; // @synthesize contact=_contact;

@end

