//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GEOPlace.h"

@class NSString;

@interface GEOPlace (MKGeoServicesExtras)
- (unsigned long long)businessID;
@property(readonly, retain, nonatomic) NSString *yelpID;
- (id)initWithPlacemark:(id)arg1;
@end

