//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSDate, NSString, NSURL;

@interface MKYelpDeal : NSObject <NSCopying>
{
    NSString *dealID;
    NSString *title;
    NSDate *startDate;
    NSDate *endDate;
    NSURL *url;
}

+ (id)dealWithJSONObject:(id)arg1;
@property(retain, nonatomic) NSDate *endDate; // @synthesize endDate;
@property(retain, nonatomic) NSDate *startDate; // @synthesize startDate;
- (void).cxx_destruct;
@property(retain, nonatomic) NSURL *url; // @synthesize url;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) NSString *title; // @synthesize title;
@property(retain, nonatomic) NSString *dealID; // @synthesize dealID;

@end

