//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString, NSURL;

@interface MMCSSimpleFile : NSObject
{
    int _fd;
    NSString *_authToken;
    int _encryptionBehavior;
    NSString *_localPath;
    NSURL *_requestURL;
    NSString *_requestorID;
    NSString *_guid;
    NSData *_signature;
    NSData *_fileHash;
    double _progress;
    unsigned long long _itemID;
    unsigned long long _protocolFileSize;
}

@property(retain) NSData *fileHash; // @synthesize fileHash=_fileHash;
@property(retain) NSData *signature; // @synthesize signature=_signature;
@property(retain) NSString *requestorID; // @synthesize requestorID=_requestorID;
@property int encryptionBehavior; // @synthesize encryptionBehavior=_encryptionBehavior;
@property int fd; // @synthesize fd=_fd;
@property(retain) NSString *localPath; // @synthesize localPath=_localPath;
@property(retain) NSURL *requestURL; // @synthesize requestURL=_requestURL;
@property(retain) NSString *guid; // @synthesize guid=_guid;
@property(retain) NSString *authToken; // @synthesize authToken=_authToken;
@property unsigned long long protocolFileSize; // @synthesize protocolFileSize=_protocolFileSize;
@property double progress; // @synthesize progress=_progress;
- (id)description;
- (id)init;
- (void)dealloc;
@property unsigned long long itemID; // @synthesize itemID=_itemID;

@end

