//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PrototypeTools/PTSRow.h>

@interface PTSEditFloatRow : PTSRow
{
    unsigned int _precision;
}

- (Class)rowTableViewCellClass;
- (id)between:(float)arg1 and:(float)arg2;
- (void)updateWithRow:(id)arg1;
- (id)precision:(unsigned int)arg1;
- (id)init;
@property(nonatomic) unsigned int precision; // @synthesize precision=_precision;

@end

