//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MTLArrayType : NSObject
{
    unsigned int _arrayLength;
    unsigned int _stride;
    id _details;
    unsigned int _elementType;
}

- (void)dealloc;
@property(readonly) unsigned int elementType; // @synthesize elementType=_elementType;
- (id)elementStructType;
- (id)elementArrayType;
@property(readonly) unsigned int stride;
- (id)initWithArrayLength:(unsigned int)arg1 elementType:(unsigned int)arg2 stride:(unsigned int)arg3 details:(id)arg4;
- (id)describe;
@property(readonly) unsigned int arrayLength;

@end

