//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MTLVertexAttribute : NSObject
{
    BOOL _active;
    NSString *_name;
    unsigned int _attributeIndex;
}

@property(readonly) NSString *name; // @synthesize name=_name;
@property(readonly, getter=isActive) BOOL active; // @synthesize active=_active;
- (id)description;
- (void)dealloc;
@property(readonly) unsigned int attributeIndex; // @synthesize attributeIndex=_attributeIndex;
- (id)initWithName:(id)arg1 attributeIndex:(unsigned int)arg2 isActive:(BOOL)arg3;

@end

