//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class MTLVertexAttributeDescriptorArray, MTLVertexBufferLayoutDescriptorArray;

@interface MTLVertexDescriptor : NSObject <NSCopying>
{
    MTLVertexBufferLayoutDescriptorArray *_vertexBufferArray;
    MTLVertexAttributeDescriptorArray *_attributeArray;
}

+ (id)vertexDescriptor;
@property(readonly) MTLVertexAttributeDescriptorArray *attributes; // @synthesize attributes=_attributeArray;
- (void)reset;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)init;
- (void)dealloc;
- (id)serializeDescriptor;
- (unsigned int)vertexBufferIndexAtAttributeIndex:(unsigned int)arg1;
- (unsigned int)offsetAtAttributeIndex:(unsigned int)arg1;
- (unsigned int)vertexFormatAtAttributeIndex:(unsigned int)arg1;
- (void)setVertexFormat:(unsigned int)arg1 offset:(unsigned int)arg2 vertexBufferIndex:(unsigned int)arg3 atAttributeIndex:(unsigned int)arg4;
- (void)setStride:(unsigned int)arg1 atVertexBufferIndex:(unsigned int)arg2;
- (void)setStride:(unsigned int)arg1 stepFunction:(unsigned int)arg2 stepRate:(unsigned int)arg3 atVertexBufferIndex:(unsigned int)arg4;
@property(readonly) MTLVertexBufferLayoutDescriptorArray *layouts; // @synthesize layouts=_vertexBufferArray;
- (unsigned int)stepRateAtVertexBufferIndex:(unsigned int)arg1;
- (unsigned int)stepFunctionAtVertexBufferIndex:(unsigned int)arg1;
- (unsigned int)strideAtVertexBufferIndex:(unsigned int)arg1;

@end

