//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface OSDConfigSecurity : NSObject
{
}

+ (id)_createConfigPackageV1:(id)arg1 cfgpkgFilePath:(id)arg2 privateKey:(id)arg3 error:(id *)arg4;
+ (_Bool)makeConfigPackageHumanReadable:(id)arg1 error:(id *)arg2;
+ (id)verifyAndExtractConfigPackage:(id)arg1 certificate:(id)arg2 error:(id *)arg3;
+ (_Bool)createConfigPackageFromFile:(id)arg1 osdcfgFilePath:(id)arg2 privateKey:(id)arg3 error:(id *)arg4;
+ (id)rawExtractConfigPackage:(id)arg1 error:(id *)arg2;
+ (id)_extractConfigPackageV2:(id)arg1 certificate:(id)arg2 error:(id *)arg3;
+ (id)_extractConfigPackageV1:(id)arg1 certificate:(id)arg2 error:(id *)arg3;
+ (id)_createConfigPackageV2:(id)arg1 cfgpkgFilePath:(id)arg2 privateKey:(id)arg3 error:(id *)arg4;
+ (_Bool)createConfigPackageFromDict:(id)arg1 osdcfgFilePath:(id)arg2 privateKey:(id)arg3 error:(id *)arg4;

@end

