//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface OSDEFISecurityParams : NSObject
{
    NSData *_nonce;
    NSData *_diagSecret;
}

@property(retain, nonatomic) NSData *nonce; // @synthesize nonce=_nonce;
@property(retain, nonatomic) NSData *diagSecret; // @synthesize diagSecret=_diagSecret;
- (void).cxx_destruct;

@end

