//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface OSDEFISecurityDeviceParams : NSObject
{
    NSData *_nonce;
    NSData *_diagSecret;
    NSString *_fileName;
    NSData *_hashToVerify;
}

@property(retain, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(retain, nonatomic) NSData *nonce; // @synthesize nonce=_nonce;
@property(retain, nonatomic) NSData *hashToVerify; // @synthesize hashToVerify=_hashToVerify;
@property(retain, nonatomic) NSData *diagSecret; // @synthesize diagSecret=_diagSecret;
- (void).cxx_destruct;

@end

