//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface OSDNonce : NSObject
{
    unsigned long _nonceSizeInBytes;
    NSData *_rawNonce;
    NSData *_lastRawNonce;
}

@property(retain, nonatomic) NSData *rawNonce; // @synthesize rawNonce=_rawNonce;
- (id)initWithNonceSizeInBytes:(unsigned long)arg1;
@property(retain, nonatomic) NSData *lastRawNonce; // @synthesize lastRawNonce=_lastRawNonce;
@property(nonatomic) unsigned long nonceSizeInBytes; // @synthesize nonceSizeInBytes=_nonceSizeInBytes;
- (void).cxx_destruct;
- (id)init;

@end

