//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface OSDSymmetricSecurity : NSObject
{
    NSData *_keyData;
}

- (id)decryptData:(id)arg1 symmetricType:(int)arg2 error:(id *)arg3;
- (id)encryptData:(id)arg1 symmetricType:(int)arg2 error:(id *)arg3;
- (id)initWithKeyData:(id)arg1;
- (id)cryptorHelper:(id)arg1 symmetricType:(int)arg2 encrypt:(_Bool)arg3 error:(id *)arg4;
@property(retain, nonatomic) NSData *keyData; // @synthesize keyData=_keyData;
- (void).cxx_destruct;

@end

