//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIFoundation/UIFont.h>

@interface UICTFont : UIFont
{
}

- (void)finalize;
- (BOOL)retainWeakReference;
- (BOOL)allowsWeakReference;
- (unsigned int)hash;
- (unsigned int)retainCount;
- (BOOL)isEqual:(id)arg1;
- (oneway void)release;
- (id)retain;
- (unsigned long)_cfTypeID;

@end

