//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DDDetectionControllerInteractionDelegate.h"
#import "WKActionSheetDelegate.h"

@class NSString, WKContentView;

@interface WKActionSheetAssistant : NSObject <WKActionSheetDelegate, DDDetectionControllerInteractionDelegate>
{
    struct RetainPtr<WKActionSheet> _interactionSheet;
    struct RetainPtr<_WKActivatedElementInfo> _elementInfo;
    WKContentView *_view;
}

- (void)showDataDetectorsSheet;
- (void)showLinkSheet;
- (void)showImageSheet;
- (struct CGRect)presentationRectInHostViewForSheet;
- (void)cleanupSheet;
- (void)updateSheetPosition;
- (id)hostViewForSheet;
- (struct CGRect)initialPresentationRectInHostViewForSheet;
- (void).cxx_destruct;
- (id).cxx_construct;
- (struct CGRect)_presentationRectForSheetGivenPoint:(struct CGPoint)arg1 inHostView:(id)arg2;
- (BOOL)presentSheet;
- (void)_createSheetWithElementActions:(id)arg1 showLinkTitle:(BOOL)arg2;
- (id)superviewForSheet;
- (id)initWithView:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

