//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WKDOMRange;

@interface WKDOMTextIterator : NSObject
{
    struct unique_ptr<WebCore::TextIterator, std::__1::default_delete<WebCore::TextIterator>> _textIterator;
    struct Vector<unsigned short, 0, WTF::CrashOnOverflow> _upconvertedText;
}

- (void)advance;
@property(readonly) unsigned int currentTextLength;
@property(readonly) const unsigned short *currentTextPointer;
@property(readonly) WKDOMRange *currentRange;
- (void).cxx_destruct;
- (id).cxx_construct;
- (id)initWithRange:(id)arg1;
@property(readonly) BOOL atEnd;

@end

