//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

#import "WKObject.h"

@class NSString;

@interface WKNSDictionary : NSDictionary <WKObject>
{
    struct ObjectStorage<WebKit::ImmutableDictionary> _dictionary;
}

@property(readonly) struct Object *_apiObject;
- (id)initWithObjects:(const id *)arg1 forKeys:(const id *)arg2 count:(unsigned int)arg3;
- (id)keyEnumerator;
- (id).cxx_construct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned int)count;
- (void)dealloc;
- (id)objectForKey:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

