//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CoreImage/CIFilter.h>

@class CIImage, CIVector, NSNumber;

@interface CIHoleDistortion : CIFilter
{
    CIImage *inputImage;
    CIVector *inputCenter;
    NSNumber *inputRadius;
}

+ (id)customAttributes;
- (id)outputImage;
- (void)setDefaults;
- (struct CGRect)computeDOD;
@property(retain, nonatomic) CIVector *inputCenter; // @synthesize inputCenter;
- (id)_colorKernel;
- (id)_geomKernel;
@property(retain, nonatomic) NSNumber *inputRadius; // @synthesize inputRadius;
- (BOOL)_isIdentity;
@property(retain, nonatomic) CIImage *inputImage; // @synthesize inputImage;

@end

