//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PLEntryNotificationOperatorComposition, PLSmartPLService;

@interface SmartPLMemoryTracking : NSObject
{
    PLSmartPLService *_operator;
    PLEntryNotificationOperatorComposition *_memoryTrackingNotification;
}

+ (id)defaults;
@property(retain) PLEntryNotificationOperatorComposition *memoryTrackingNotification; // @synthesize memoryTrackingNotification=_memoryTrackingNotification;
- (void)startWithOperator:(id)arg1;
- (void)handleMemoryTracking:(id)arg1;
@property __weak PLSmartPLService *operator; // @synthesize operator=_operator;
- (void).cxx_destruct;

@end

