//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FPTestLineFlow : NSObject
{
}

+ (id)testFlowInfoFor:(id)arg1 error:(id *)arg2;
+ (id)_testFlowInfoV1:(id)arg1 forStation:(id)arg2 forFlowID:(unsigned short)arg3 error:(id *)arg4;

@end

