//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FPVisualizedFlow : NSObject
{
}

+ (id)newVizualizedFlowLayer:(id *)arg1;
+ (id)newVisualizedFlowLayer:(id *)arg1;
+ (struct CGColor *)newColorForNextStation:(id *)arg1;
+ (unsigned int)_getColorForTotalPassCBs:(unsigned char)arg1;
+ (unsigned char)_totalPassCBs:(char *)arg1 error:(id *)arg2;

@end

