//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HKHealthService, NSArray, NSLock;

@interface HKHealthServiceSession : NSObject
{
    NSArray *_interestedTransitoryKeys;
    CDUnknownBlockType _transitoryDataHandler;
    HKHealthService *_service;
    NSLock *_propertyLock;
    unsigned int _sessionIdentifier;
    CDUnknownBlockType _sessionHandler;
    CDUnknownBlockType _characteristicsHandler;
}

- (id)initWithService:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) unsigned int sessionIdentifier; // @synthesize sessionIdentifier=_sessionIdentifier;
@property(copy, nonatomic) CDUnknownBlockType characteristicsHandler; // @synthesize characteristicsHandler=_characteristicsHandler;
@property(retain, nonatomic) NSLock *propertyLock; // @synthesize propertyLock=_propertyLock;
@property(copy) CDUnknownBlockType transitoryDataHandler;
@property(retain) NSArray *interestedTransitoryKeys;
@property(copy, nonatomic) CDUnknownBlockType sessionHandler; // @synthesize sessionHandler=_sessionHandler;
@property(readonly, nonatomic) HKHealthService *service; // @synthesize service=_service;

@end

