//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CoreFoundation/__NSCFType.h>

@interface __NSCFNumber : __NSCFType
{
}

+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
- (void)finalize;
- (id)descriptionWithLocale:(id)arg1;
- (BOOL)isEqualToNumber:(id)arg1;
- (long)longValue;
- (short)shortValue;
- (BOOL)charValue;
- (unsigned char)unsignedCharValue;
- (unsigned long)unsignedLongValue;
- (unsigned long long)unsignedLongLongValue;
- (const char *)objCType;
- (id)stringValue;
- (int)compare:(id)arg1;
- (unsigned int)unsignedIntValue;
- (long long)longLongValue;
- (unsigned int)unsignedIntegerValue;
- (BOOL)_isDeallocating;
- (BOOL)_tryRetain;
- (float)floatValue;
- (void)getValue:(void *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (int)integerValue;
- (double)doubleValue;
- (id)description;
- (unsigned int)hash;
- (unsigned int)retainCount;
- (BOOL)isEqual:(id)arg1;
- (BOOL)boolValue;
- (int)intValue;
- (oneway void)release;
- (id)retain;
- (unsigned short)unsignedShortValue;
- (unsigned long)_cfTypeID;
- (int)_reverseCompare:(id)arg1;
- (unsigned char)_getValue:(void *)arg1 forType:(long)arg2;
- (long)_cfNumberType;
- (BOOL)isNSNumber__;

@end

