//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CoreFoundation/NSDate.h>

@interface __NSPlaceholderDate : NSDate
{
}

+ (void)initialize;
+ (id)immutablePlaceholder;
- (id)initWithTimeIntervalSinceReferenceDate:(double)arg1;
- (double)timeIntervalSinceReferenceDate;
- (unsigned int)retainCount;
- (id)init;
- (void)dealloc;
- (oneway void)release;
- (id)retain;

@end

