//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CoreFoundation/NSMutableArray.h>

@interface __NSPlaceholderArray : NSMutableArray
{
}

+ (void)initialize;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)mutablePlaceholder;
+ (id)immutablePlaceholder;
- (id)initWithContentsOfURL:(id)arg1;
- (id)initWithObjects:(const id *)arg1 count:(unsigned int)arg2;
- (void)removeObjectAtIndex:(unsigned int)arg1;
- (id)initWithContentsOfFile:(id)arg1;
- (void)insertObject:(id)arg1 atIndex:(unsigned int)arg2;
- (void)replaceObjectAtIndex:(unsigned int)arg1 withObject:(id)arg2;
- (id)initWithCapacity:(unsigned int)arg1;
- (unsigned int)retainCount;
- (id)init;
- (id)objectAtIndex:(unsigned int)arg1;
- (unsigned int)count;
- (void)dealloc;
- (oneway void)release;
- (id)retain;

@end

