//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CallHistory/CHLogger.h>

@class CallDBManager, CallDBProperties, NSManagedObjectContext, NSString;

@interface CallHistoryDBHandle : CHLogger
{
    NSManagedObjectContext *fCallRecordContext;
    NSManagedObjectContext *fCallDBPropertiesContext;
    CallDBProperties *fCallDBProperties;
    CallDBManager *callDBManager;
    NSString *objectId;
    id _observerCallRecordRef;
    id _observerCallDBPropRef;
}

+ (id)create;
+ (id)createWithDBManager:(id)arg1;
- (void)deleteAll;
@property(readonly, nonatomic) NSString *objectId; // @synthesize objectId;
@property(readonly, nonatomic) CallDBManager *callDBManager; // @synthesize callDBManager;
- (id)timerLastReset;
- (id)fetchWithCallTypes:(unsigned int)arg1;
- (id)createCallRecord;
- (void)mergeCallDBPropChangesFromRemoteAppSave;
- (void)mergeCallRecordChangesFromRemoteAppSave;
- (void)registerForNotifications:(id)arg1;
- (id)callRecordContext;
- (void)handleCallRecordMergeConflicts:(id)arg1;
- (void)updateCallDBProperties;
- (id)getArrayForCallTypeMask:(unsigned int)arg1;
- (id)fetchWithPredicate:(id)arg1 forEntity:(id)arg2 withLimit:(BOOL)arg3;
- (void)postTimersChangedNotification;
- (void)handleCallDBPropContextDidSaveNotification:(id)arg1;
- (void)handleCallRecordContextDidSaveNotification:(id)arg1;
- (id)fetchWithPredicate:(id)arg1 forEntity:(id)arg2;
- (void)setCallDBProperties;
- (id)fetchAllNoLimit;
- (id)fetchObjectsWithUniqueIds:(id)arg1;
- (void)deleteObjectWithUniqueId:(id)arg1;
- (id)fetchObjectsWithPredicate:(id)arg1;
- (id)fetchObjectWithUniqueId:(id)arg1;
- (id)fetchAll;
- (id)initWithDBManager:(id)arg1;
- (void)resetTimers;
- (id)timerLifetime;
- (id)timerOutgoing;
- (id)timerIncoming;
- (void)deleteObjectsWithUniqueIds:(id)arg1;
- (void)unRegisterForNotifications;
- (BOOL)save:(id *)arg1;
- (void).cxx_destruct;
- (void)dealloc;

@end

