//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@interface _NSConstantDate : NSDate
{
}

+ (void)load;
+ (id)alloc;
- (double)timeIntervalSinceReferenceDate;
- (unsigned int)retainCount;
- (void)dealloc;
- (oneway void)release;
- (id)retain;

@end

