//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSNumber.h"

@interface _PFCachedNumber : NSNumber
{
}

+ (id)value:(const void *)arg1 withObjCType:(const char *)arg2;
+ (id)valueWithBytes:(const void *)arg1 objCType:(const char *)arg2;
+ (id)copyWithZone:(struct _NSZone *)arg1;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)new;
+ (id)alloc;
- (id)descriptionWithLocale:(id)arg1;
- (long)longValue;
- (short)shortValue;
- (id)objectID;
- (id)initWithBytes:(const void *)arg1 objCType:(const char *)arg2;
- (BOOL)charValue;
- (unsigned char)unsignedCharValue;
- (unsigned long)unsignedLongValue;
- (unsigned long long)unsignedLongLongValue;
- (const char *)objCType;
- (id)stringValue;
- (unsigned int)unsignedIntValue;
- (long long)longLongValue;
- (unsigned int)unsignedIntegerValue;
- (BOOL)_isDeallocating;
- (BOOL)_tryRetain;
- (float)floatValue;
- (void)getValue:(void *)arg1;
- (int)integerValue;
- (double)doubleValue;
- (id)description;
- (unsigned int)retainCount;
- (id)autorelease;
- (id)copy;
- (id)init;
- (void)dealloc;
- (BOOL)boolValue;
- (int)intValue;
- (oneway void)release;
- (id)retain;
- (unsigned short)unsignedShortValue;

@end

