//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface CBProcessControl : NSObject
{
    void *_intCBPC;
}

+ (id)processControlWithIPodObj:(CDStruct_08b567e9 *)arg1;
@property(readonly) NSString *swVersion; // @dynamic swVersion;
@property(readonly) unsigned short eraseCount; // @dynamic eraseCount;
@property(readonly) unsigned char relativeFailCount; // @dynamic relativeFailCount;
@property(readonly) unsigned short absoluteFailCount; // @dynamic absoluteFailCount;
- (CDStruct_08b567e9 *)_internalProcCntrl;
- (id)initWithStatus:(int)arg1 andFailCount:(int)arg2;
- (id)initWithIPodObj:(CDStruct_08b567e9 *)arg1;
@property(readonly) int status; // @dynamic status;
@property(readonly) NSDate *timestamp; // @dynamic timestamp;
- (id)description;
- (void)dealloc;

@end

