//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Typedef'd Structures

typedef struct {
    char *_field1;
    char *_field2[20];
    int _field3;
    char _field4[100];
    _Bool _field5;
    _Bool _field6;
    _Bool _field7;
} CDStruct_07d12476;

typedef struct {
    unsigned int :2;
    unsigned int :8;
    unsigned int :10;
    unsigned int :12;
    unsigned int _field1;
    unsigned char _field2[24];
} CDStruct_08b567e9;

