//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CBProcessControl, NSString;

@protocol ControlBitsIPxInterface <NSObject>
+ (int)eraseControlBitsUponSysCfgWrite:(int)arg1;
+ (CBProcessControl *)readControlBits:(unsigned char)arg1;
+ (int)writeControlBits:(unsigned char)arg1 status:(int)arg2 swVersion:(NSString *)arg3;
+ (int)writeControlBits:(unsigned char)arg1 ecid:(long long)arg2 status:(int)arg3 swVersion:(NSString *)arg4;
@end

