//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <FactoryTest/ControlBits.h>

@interface ControlBits_Legacy_0v0 : ControlBits
{
}

+ (int)readControlBits:(unsigned char)arg1 status:(int *)arg2 failCount:(int *)arg3 secure:(char *)arg4;
+ (int)writeControlBits:(unsigned char)arg1 status:(int)arg2;

@end

