//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDateFormatter, NSMutableDictionary, NSString;

@interface PDCAPropertyList : NSObject
{
    NSMutableDictionary *plist;
    NSString *currentSequence;
    NSDateFormatter *dateFormatter;
}

- (id)plist;
- (_Bool)setStopTime:(id)arg1;
- (_Bool)addParametricTest:(id)arg1 result:(_Bool)arg2 value:(id)arg3 failureMessage:(id)arg4 subtest:(id)arg5 subsubtest:(id)arg6 upperLimit:(id)arg7 lowerLimit:(id)arg8 priority:(int)arg9 units:(id)arg10;
- (_Bool)addPassFailTest:(id)arg1 result:(_Bool)arg2 failureMessage:(id)arg3 subtest:(id)arg4 subsubtest:(id)arg5;
- (_Bool)addDeviceAttributes:(id)arg1;
- (_Bool)addTestSequenceRun:(id)arg1 softwareName:(id)arg2 softwareVersion:(id)arg3 startTime:(id)arg4 stopTime:(id)arg5 limitsVersion:(id)arg6 deviceAttributes:(id)arg7;
- (_Bool)stringIsAlphanumeric:(id)arg1;
- (_Bool)stringIsNumeric:(id)arg1;
- (_Bool)createTest:(id)arg1 name:(id)arg2 result:(_Bool)arg3 failureMessage:(id)arg4 subtest:(id)arg5 subsubtest:(id)arg6;
- (id)makeAlphanumericString:(id)arg1;
- (_Bool)stringIsAlphanumericPeriod:(id)arg1;
- (id)initWithPath:(id)arg1;
- (_Bool)setStartTime:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)init;
- (void)dealloc;

@end

