//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RMSFairPlaySession : NSObject
{
    BOOL _handshakeComplete;
}

@property(readonly, nonatomic, getter=isHandshakeComplete) BOOL handshakeComplete; // @synthesize handshakeComplete=_handshakeComplete;
- (id)headerForURL:(id)arg1;
- (id)handshakeIterationWithData:(id)arg1;
- (id)handshakeData;
- (void)invalidate;

@end

