//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <SpriteKit/SKNode.h>

@interface SKCropNode : SKNode
{
    SKNode *_mask;
    struct SKCSprite *_csprite;
}

@property(retain, nonatomic) SKNode *maskNode;
- (void).cxx_destruct;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (BOOL)isEqualToNode:(id)arg1;

@end

