//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString, NSURL;

@interface MCBookmark : NSObject <NSCopying>
{
    NSURL *_URL;
    NSString *_title;
    NSString *_path;
}

- (id)serializableDictionary;
- (id)initWithSerializableDictionary:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSURL *URL; // @synthesize URL=_URL;
@property(retain, nonatomic) NSString *path; // @synthesize path=_path;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (id)description;
- (BOOL)isEqual:(id)arg1;

@end

