//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ManagedConfiguration/MCProfile.h>

@class MCProfileServiceProfile, NSArray;

@interface MCConfigurationProfile : MCProfile
{
    NSArray *_payloads;
    NSArray *_managedPayloads;
    BOOL _isCloudProfile;
    BOOL _isCloudLocked;
    BOOL _isMDMProfile;
    MCProfileServiceProfile *_OTAProfile;
}

@property(nonatomic) BOOL isMDMProfile; // @synthesize isMDMProfile=_isMDMProfile;
@property(nonatomic) BOOL isCloudLocked; // @synthesize isCloudLocked=_isCloudLocked;
@property(nonatomic) BOOL isCloudProfile; // @synthesize isCloudProfile=_isCloudProfile;
@property(retain, nonatomic) MCProfileServiceProfile *OTAProfile; // @synthesize OTAProfile=_OTAProfile;
- (id)earliestCertificateExpiryDate;
- (id)localizedManagedPayloadSummaryByType;
- (id)localizedPayloadSummaryByType;
- (BOOL)isManagedByProfileService;
- (id)subjectSummaryFromCertificateWithPersistentID:(id)arg1;
- (id)subjectSummaryFromCertificatePayloadWithUUID:(id)arg1;
- (id)managedPayloads;
- (id)_localizedPayloadSummaryByType:(id)arg1;
- (id)installationWarningsIncludeUnsignedProfileWarning:(BOOL)arg1;
- (void)_sortPayloads;
- (id)initWithDictionary:(id)arg1 allowEmptyPayload:(BOOL)arg2 outError:(id *)arg3;
- (id)_subjectSummaryFromCertificate:(struct __SecCertificate *)arg1;
- (struct __SecCertificate *)copyCertificateFromPayloadWithUUID:(id)arg1;
- (id)payloadWithUUID:(id)arg1;
- (id)payloads;
- (id)_sortPayloads:(id)arg1;
- (void)_addObjectsOfClass:(Class)arg1 fromArray:(id)arg2 toArray:(id)arg3;
- (id)stubDictionary;
- (struct __SecCertificate *)copyCertificateWithPersistentID:(id)arg1;
- (void).cxx_destruct;
- (id)description;

@end

