//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumberFormatter, NSObject<OS_dispatch_queue>;

@interface MCFormatterVendor : NSObject
{
    NSNumberFormatter *_numberFormatter;
    NSObject<OS_dispatch_queue> *_syncQueue;
}

+ (id)sharedInstance;
- (void)_localeDidChange:(id)arg1;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;
- (id)numberFormatter;

@end

