//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class RadiosPreferences;

@interface MCNetrbManager : NSObject
{
    struct __CFRunLoopSource *_scRunLoopSource;
    struct __SCDynamicStore *_scDynamicStore;
    struct NETRBClient *_netClient;
    int _state;
    int _reason;
    BOOL _needStateUpdate;
    RadiosPreferences *_radioPrefs;
}

+ (id)sharedManager;
- (void)getState:(int *)arg1 andReason:(int *)arg2;
- (BOOL)didUserPreventData;
- (void)detachMIS;
- (void)readMISState:(int *)arg1 andReason:(int *)arg2;
- (void)stopService;
- (void)authenticate;
- (void)attachMIS;
- (void)cellDataChangedNotification:(id)arg1;
- (void).cxx_destruct;
- (void)setState:(int)arg1;
- (id)init;

@end

