//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MCProfile, NSArray, NSDictionary, NSString;

@interface MCPayload : NSObject
{
    MCProfile *_profile;
    NSString *_type;
    NSString *_payloadDescription;
    NSString *_displayName;
    NSString *_identifier;
    NSString *_organization;
    NSString *_UUID;
    int _version;
    NSString *_persistentResourceID;
    BOOL _mustInstallNonInteractively;
}

+ (id)payloadFromDictionary:(id)arg1 profile:(id)arg2 outError:(id *)arg3;
+ (id)localizedParenthesizedFormDescriptionForPayloadCount:(unsigned int)arg1;
+ (id)wrapperPayloadDictionary;
+ (id)badFieldValueErrorWithField:(id)arg1;
+ (id)missingFieldErrorWithField:(id)arg1 underlyingError:(id)arg2;
+ (id)badFieldValueErrorWithField:(id)arg1 underlyingError:(id)arg2;
+ (id)localizedDescriptionForPayloadCount:(unsigned int)arg1;
+ (id)payloadsFromArray:(id)arg1 profile:(id)arg2 outError:(id *)arg3;
+ (id)localizedPluralForm;
+ (id)localizedSingularForm;
+ (id)typeStrings;
+ (id)badFieldTypeErrorWithField:(id)arg1;
@property(readonly, nonatomic) __weak MCProfile *profile; // @synthesize profile=_profile;
@property(readonly, retain, nonatomic) NSString *payloadDescription; // @synthesize payloadDescription=_payloadDescription;
@property(retain, nonatomic) NSString *persistentResourceID; // @synthesize persistentResourceID=_persistentResourceID;
@property(nonatomic) BOOL mustInstallNonInteractively; // @synthesize mustInstallNonInteractively=_mustInstallNonInteractively;
- (id)subtitle2Description;
@property(readonly, retain, nonatomic) NSArray *installationWarnings;
- (id)payloadDescriptionKeyValueSections;
- (id)subtitle1Description;
- (id)subtitle1Label;
- (id)stubDictionary;
- (id)malformedPayloadErrorWithError:(id)arg1;
- (id)initWithDictionary:(id)arg1 profile:(id)arg2 outError:(id *)arg3;
@property(readonly, retain, nonatomic) NSString *organization; // @synthesize organization=_organization;
@property(readonly, retain, nonatomic) NSString *friendlyName;
@property(readonly, nonatomic) NSDictionary *restrictions;
- (void).cxx_destruct;
@property(readonly, nonatomic) int version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
- (id)subtitle2Label;
@property(readonly, retain, nonatomic) NSString *UUID; // @synthesize UUID=_UUID;
- (id)title;
@property(readonly, retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(readonly, retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)description;

@end

