//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDate, NSDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface MCProfile : NSObject
{
    int _trustQueueTrustLevel;
    BOOL _trustQueueTrustHasBeenEvaluated;
    NSObject<OS_dispatch_queue> *_trustEvaluationQueue;
    NSString *_signerQueueSignerSummary;
    NSArray *_signerQueueSignerCertificates;
    NSObject<OS_dispatch_queue> *_signerEvaluationQueue;
    BOOL _encrypted;
    BOOL _isLocked;
    BOOL _needsReboot;
    BOOL _isStub;
    BOOL _mustInstallNonInteractively;
    NSString *_profileDescription;
    NSString *_displayName;
    NSString *_identifier;
    NSString *_UUID;
    NSString *_organization;
    int _version;
    NSDate *_installDate;
    NSDate *_expiryDate;
    NSString *_removalPasscode;
    NSString *_productVersion;
    NSString *_productBuildVersion;
    NSDate *_removalDate;
    NSDictionary *_installOptions;
    NSString *_localizedConsentText;
}

+ (int)evaluateTrust:(struct __SecTrust *)arg1;
+ (id)dataFromCMSEncodedData:(id)arg1 outSignerCertificates:(id *)arg2;
+ (id)profileDictionaryFromProfileData:(id)arg1 outError:(id *)arg2;
+ (id)_malformedProfileError;
+ (id)profileWithData:(id)arg1 fileName:(id)arg2 outError:(id *)arg3;
+ (id)profileWithData:(id)arg1 fileName:(id)arg2 allowEmptyPayload:(BOOL)arg3 outError:(id *)arg4;
+ (id)signerSummaryOfCertificate:(struct __SecCertificate *)arg1;
+ (int)evaluateTrustOfCertificateChain:(id)arg1;
+ (id)missingFieldErrorWithField:(id)arg1;
+ (BOOL)checkString:(id)arg1 isOneOfStrings:(id)arg2 key:(id)arg3 errorDomain:(id)arg4 errorCode:(int)arg5 errorString:(id)arg6 outError:(id *)arg7;
+ (int)evaluateTrustOfCertificateChain:(id)arg1 outIsAllowedToWriteDefaults:(char *)arg2;
+ (id)profileWithDictionary:(id)arg1 fileName:(id)arg2 allowEmptyPayload:(BOOL)arg3 outError:(id *)arg4;
+ (id)removeOptionalNonZeroLengthStringInDictionary:(id)arg1 key:(id)arg2 errorDomain:(id)arg3 invalidDataCode:(int)arg4 invalidDataErrorString:(id)arg5 outError:(id *)arg6;
+ (id)removeRequiredNonZeroLengthStringInDictionary:(id)arg1 key:(id)arg2 errorDomain:(id)arg3 missingDataCode:(int)arg4 missingDataErrorString:(id)arg5 invalidDataCode:(int)arg6 invalidDataErrorString:(id)arg7 outError:(id *)arg8;
+ (id)profileWithData:(id)arg1 outError:(id *)arg2;
+ (id)removeOptionalObjectInDictionary:(id)arg1 key:(id)arg2 type:(Class)arg3 errorDomain:(id)arg4 invalidDataCode:(int)arg5 invalidDataErrorString:(id)arg6 outError:(id *)arg7;
+ (id)badFieldTypeErrorWithField:(id)arg1;
+ (id)removeRequiredObjectInDictionary:(id)arg1 key:(id)arg2 type:(Class)arg3 errorDomain:(id)arg4 missingDataCode:(int)arg5 missingDataErrorString:(id)arg6 invalidDataCode:(int)arg7 invalidDataErrorString:(id)arg8 outError:(id *)arg9;
@property(readonly, nonatomic) BOOL isSigned;
- (unsigned int)countOfPayloadsOfClass:(Class)arg1;
- (BOOL)containsPayloadOfClass:(Class)arg1;
- (BOOL)writeStubToDirectory:(id)arg1;
@property(readonly, retain, nonatomic) NSString *profileIDHashFileName;
- (BOOL)writeStubToPath:(id)arg1;
@property(readonly, retain, nonatomic) NSString *stubFileName;
@property(readonly, nonatomic) NSString *localizedConsentText; // @synthesize localizedConsentText=_localizedConsentText;
@property(nonatomic) BOOL mustInstallNonInteractively; // @synthesize mustInstallNonInteractively=_mustInstallNonInteractively;
@property(retain, nonatomic) NSDictionary *installOptions; // @synthesize installOptions=_installOptions;
@property(readonly, nonatomic) NSDate *removalDate; // @synthesize removalDate=_removalDate;
@property(readonly, retain, nonatomic) NSString *productBuildVersion; // @synthesize productBuildVersion=_productBuildVersion;
@property(readonly, retain, nonatomic) NSString *productVersion; // @synthesize productVersion=_productVersion;
@property(readonly, nonatomic) BOOL needsReboot; // @synthesize needsReboot=_needsReboot;
@property(retain, nonatomic) NSDate *installDate; // @synthesize installDate=_installDate;
@property(nonatomic, getter=isEncrypted) BOOL encrypted; // @synthesize encrypted=_encrypted;
- (id)appAccessibilityParameters;
- (id)restrictionsWithHeuristicsAppliedOutError:(id *)arg1;
- (BOOL)mayInstallWithOptions:(id)arg1 hasInteractionClient:(BOOL)arg2 outError:(id *)arg3;
- (void)evaluateSignerTrustAsynchronouslyWithCompletion:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) struct __SecCertificate *signerCertificate;
- (void)evaluateSignerTrust;
@property(readonly, nonatomic) NSString *signerSummary;
@property(readonly, nonatomic) int trustLevel;
@property(retain, nonatomic) NSArray *signerCertificates;
@property(readonly, retain, nonatomic) NSDate *earliestCertificateExpiryDate;
@property(readonly, retain, nonatomic) NSArray *localizedManagedPayloadSummaryByType;
@property(readonly, retain, nonatomic) NSArray *localizedPayloadSummaryByType;
@property(readonly, nonatomic) BOOL isManagedByProfileService;
- (id)subjectSummaryFromCertificateWithPersistentID:(id)arg1;
- (id)subjectSummaryFromCertificatePayloadWithUUID:(id)arg1;
@property(readonly, retain, nonatomic) NSArray *managedPayloads;
- (id)installationWarningsIncludeUnsignedProfileWarning:(BOOL)arg1;
@property(readonly, retain, nonatomic) NSArray *installationWarnings;
- (id)malformedProfileErrorWithError:(id)arg1;
- (id)initWithDictionary:(id)arg1 allowEmptyPayload:(BOOL)arg2 outError:(id *)arg3;
- (struct __SecCertificate *)copyCertificateFromPayloadWithUUID:(id)arg1;
- (id)payloadWithUUID:(id)arg1;
@property(readonly, retain, nonatomic) NSArray *payloads;
@property(retain, nonatomic) NSString *removalPasscode; // @synthesize removalPasscode=_removalPasscode;
- (id)stubDictionary;
@property(readonly, nonatomic) BOOL isStub; // @synthesize isStub=_isStub;
@property(readonly, retain, nonatomic) NSDate *expiryDate; // @synthesize expiryDate=_expiryDate;
@property(readonly, retain, nonatomic) NSString *organization; // @synthesize organization=_organization;
@property(readonly, retain, nonatomic) NSString *profileDescription; // @synthesize profileDescription=_profileDescription;
@property(readonly, retain, nonatomic) NSString *friendlyName;
- (struct __SecCertificate *)copyCertificateWithPersistentID:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) int version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(nonatomic, getter=isLocked) BOOL locked; // @synthesize locked=_isLocked;
@property(readonly, retain, nonatomic) NSString *UUID; // @synthesize UUID=_UUID;
@property(readonly, retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)description;

@end

