//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MCUserNotificationQueueEntry : NSObject
{
    BOOL _displayOnLockScreen;
    BOOL _displayInAppWhitelistModes;
    NSString *_title;
    NSString *_message;
    NSString *_defaultButtonText;
    NSString *_alternateButtonText;
    NSString *_otherButtonText;
    CDUnknownBlockType _completionBlock;
    id _notification;
    double _dismissAfterTimeInterval;
}

@property(retain, nonatomic) id notification; // @synthesize notification=_notification;
@property(nonatomic) double dismissAfterTimeInterval; // @synthesize dismissAfterTimeInterval=_dismissAfterTimeInterval;
@property(nonatomic) BOOL displayInAppWhitelistModes; // @synthesize displayInAppWhitelistModes=_displayInAppWhitelistModes;
@property(nonatomic) BOOL displayOnLockScreen; // @synthesize displayOnLockScreen=_displayOnLockScreen;
@property(retain, nonatomic) NSString *otherButtonText; // @synthesize otherButtonText=_otherButtonText;
@property(retain, nonatomic) NSString *alternateButtonText; // @synthesize alternateButtonText=_alternateButtonText;
@property(retain, nonatomic) NSString *defaultButtonText; // @synthesize defaultButtonText=_defaultButtonText;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;

@end

