//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ManagedConfiguration/MCPayload.h>

@class NSMutableDictionary, NSString;

@interface MCVPNPayloadBase : MCPayload
{
    NSMutableDictionary *_configurationDictionary;
    NSString *_serviceName;
    NSString *_vpnType;
    id <NEProfilePayloadBaseDelegate> _nePayloadBase;
    NSString *_userNameKey;
    NSString *_passwordKey;
    NSString *_proxyUserNameKey;
    NSString *_proxyPasswordKey;
    NSString *_sharedSecretKey;
    NSString *_pinKey;
}

+ (id)NEVPNPayloadBaseDelegateWithConfigurationDict:(id)arg1;
+ (id)NEAlwaysOnVPNPayloadBaseDelegateWithConfigurationDict:(id)arg1;
@property(copy, nonatomic) NSString *serviceName; // @synthesize serviceName=_serviceName;
@property(retain, nonatomic) NSString *pinKey; // @synthesize pinKey=_pinKey;
@property(retain, nonatomic) NSString *sharedSecretKey; // @synthesize sharedSecretKey=_sharedSecretKey;
@property(retain, nonatomic) NSString *proxyPasswordKey; // @synthesize proxyPasswordKey=_proxyPasswordKey;
@property(retain, nonatomic) NSString *proxyUserNameKey; // @synthesize proxyUserNameKey=_proxyUserNameKey;
@property(retain, nonatomic) NSString *passwordKey; // @synthesize passwordKey=_passwordKey;
@property(retain, nonatomic) NSString *userNameKey; // @synthesize userNameKey=_userNameKey;
@property(retain, nonatomic) id <NEProfilePayloadBaseDelegate> nePayloadBase; // @synthesize nePayloadBase=_nePayloadBase;
@property(copy, nonatomic) NSString *vpnType; // @synthesize vpnType=_vpnType;
@property(retain, nonatomic) NSMutableDictionary *configurationDictionary; // @synthesize configurationDictionary=_configurationDictionary;
- (id)installationWarnings;
- (id)payloadDescriptionKeyValueSections;
- (id)stubDictionary;
- (id)initWithDictionary:(id)arg1 profile:(id)arg2 outError:(id *)arg3;
- (void).cxx_destruct;
- (id)description;

@end

