//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ManagedConfiguration/MCPayload.h>

@class NSArray, NSDictionary, NSNumber, NSString;

@interface MCWiFiPayload : MCPayload
{
    BOOL _isHidden;
    BOOL _isWEP;
    BOOL _isWPA;
    BOOL _passwordRequired;
    BOOL _usernameRequired;
    BOOL _autoJoin;
    BOOL _proxyPACFallbackAllowed;
    BOOL _isHotspot;
    BOOL _serviceProviderRoamingEnabled;
    NSString *_ssid;
    NSString *_encryptionType;
    NSDictionary *_eapClientConfig;
    NSString *_password;
    NSString *_username;
    NSString *_certificateUUID;
    NSArray *_payloadCertificateAnchorUUID;
    int _proxyType;
    NSString *_proxyServer;
    NSNumber *_proxyServerPort;
    NSString *_proxyUsername;
    NSString *_proxyPassword;
    NSString *_proxyPACURLString;
    NSString *_credentialUUID;
    NSNumber *_priority;
    NSString *_domainName;
    NSString *_HESSID;
    NSArray *_roamingConsortiumOIs;
    NSArray *_NAIRealmNames;
    NSArray *_MCCAndMNCs;
    NSString *_displayedOperatorName;
}

+ (id)localizedPluralForm;
+ (id)localizedSingularForm;
+ (id)typeStrings;
@property(nonatomic) int proxyType; // @synthesize proxyType=_proxyType;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
@property(retain, nonatomic) NSString *domainName; // @synthesize domainName=_domainName;
@property(retain, nonatomic) NSString *displayedOperatorName; // @synthesize displayedOperatorName=_displayedOperatorName;
@property(nonatomic, getter=isServiceProviderRoamingEnabled) BOOL serviceProviderRoamingEnabled; // @synthesize serviceProviderRoamingEnabled=_serviceProviderRoamingEnabled;
@property(retain, nonatomic) NSString *HESSID; // @synthesize HESSID=_HESSID;
@property(nonatomic) BOOL isHotspot; // @synthesize isHotspot=_isHotspot;
@property(retain, nonatomic) NSString *credentialUUID; // @synthesize credentialUUID=_credentialUUID;
@property(nonatomic) BOOL proxyPACFallbackAllowed; // @synthesize proxyPACFallbackAllowed=_proxyPACFallbackAllowed;
@property(retain, nonatomic) NSString *proxyPACURLString; // @synthesize proxyPACURLString=_proxyPACURLString;
@property(retain, nonatomic) NSString *proxyPassword; // @synthesize proxyPassword=_proxyPassword;
@property(retain, nonatomic) NSString *proxyUsername; // @synthesize proxyUsername=_proxyUsername;
@property(retain, nonatomic) NSNumber *proxyServerPort; // @synthesize proxyServerPort=_proxyServerPort;
@property(retain, nonatomic) NSArray *payloadCertificateAnchorUUID; // @synthesize payloadCertificateAnchorUUID=_payloadCertificateAnchorUUID;
@property(retain, nonatomic) NSString *certificateUUID; // @synthesize certificateUUID=_certificateUUID;
@property(nonatomic) BOOL autoJoin; // @synthesize autoJoin=_autoJoin;
@property(nonatomic) BOOL usernameRequired; // @synthesize usernameRequired=_usernameRequired;
@property(nonatomic) BOOL passwordRequired; // @synthesize passwordRequired=_passwordRequired;
@property(nonatomic) BOOL isWPA; // @synthesize isWPA=_isWPA;
@property(nonatomic) BOOL isWEP; // @synthesize isWEP=_isWEP;
@property(retain, nonatomic) NSString *encryptionType; // @synthesize encryptionType=_encryptionType;
@property(retain, nonatomic) NSString *ssid; // @synthesize ssid=_ssid;
@property(retain, nonatomic) NSDictionary *eapClientConfig; // @synthesize eapClientConfig=_eapClientConfig;
- (id)_localizedEncryptionTypeString;
@property(retain, nonatomic) NSArray *MCCAndMNCs; // @synthesize MCCAndMNCs=_MCCAndMNCs;
@property(retain, nonatomic) NSArray *NAIRealmNames; // @synthesize NAIRealmNames=_NAIRealmNames;
@property(retain, nonatomic) NSArray *roamingConsortiumOIs; // @synthesize roamingConsortiumOIs=_roamingConsortiumOIs;
- (BOOL)_isEAPSIMConfig:(id)arg1;
- (id)_eapPasswordFromConfig:(id)arg1 isRequired:(char *)arg2;
- (id)_eapUsernameFromConfig:(id)arg1 isRequired:(char *)arg2;
- (BOOL)_eapConfigIsValid:(id)arg1 error:(id *)arg2;
@property(retain, nonatomic) NSString *proxyServer; // @synthesize proxyServer=_proxyServer;
- (id)subtitle2Description;
- (id)installationWarnings;
- (id)payloadDescriptionKeyValueSections;
- (id)subtitle1Description;
- (id)subtitle1Label;
- (id)stubDictionary;
- (id)initWithDictionary:(id)arg1 profile:(id)arg2 outError:(id *)arg3;
- (void).cxx_destruct;
@property(retain, nonatomic) NSNumber *priority; // @synthesize priority=_priority;
- (id)subtitle2Label;
@property(nonatomic) BOOL isHidden; // @synthesize isHidden=_isHidden;
- (id)description;
@property(retain, nonatomic) NSString *password; // @synthesize password=_password;

@end

