//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Named Structures

struct AggState {
    int state;
    double level;
    double timestamp;
};

struct in4in6_addr {
    unsigned int i46a_pad32[3];
    struct in_addr i46a_addr4;
};

struct in6_addr {
    union {
        unsigned char __u6_addr8[16];
        unsigned short __u6_addr16[8];
        unsigned int __u6_addr32[4];
    } __u6_addr;
};

struct in_addr {
    unsigned int s_addr;
};

struct in_sockinfo {
    int insi_fport;
    int insi_lport;
    unsigned long long insi_gencnt;
    unsigned int insi_flags;
    unsigned int insi_flow;
    unsigned char insi_vflag;
    unsigned char insi_ip_ttl;
    unsigned int rfu_1;
    CDUnion_95c9f286 insi_faddr;
    CDUnion_95c9f286 insi_laddr;
    struct {
        unsigned char in4_tos;
    } insi_v4;
    struct {
        unsigned char in6_hlim;
        int in6_cksum;
        unsigned short in6_ifindex;
        short in6_hops;
    } insi_v6;
};

struct kern_ctl_info {
    unsigned int kcsi_id;
    unsigned int kcsi_reg_unit;
    unsigned int kcsi_flags;
    unsigned int kcsi_recvbufsize;
    unsigned int kcsi_sendbufsize;
    unsigned int kcsi_unit;
    char kcsi_name[96];
};

struct kern_event_info {
    unsigned int kesi_vendor_code_filter;
    unsigned int kesi_class_filter;
    unsigned int kesi_subclass_filter;
};

struct ndrv_info {
    unsigned int ndrvsi_if_family;
    unsigned int ndrvsi_if_unit;
    char ndrvsi_if_name[16];
};

struct proc_bsdinfo {
    unsigned int _field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    unsigned int _field6;
    unsigned int _field7;
    unsigned int _field8;
    unsigned int _field9;
    unsigned int _field10;
    unsigned int _field11;
    unsigned int _field12;
    char _field13[16];
    char _field14[32];
    unsigned int _field15;
    unsigned int _field16;
    unsigned int _field17;
    unsigned int _field18;
    unsigned int _field19;
    int _field20;
    unsigned long long _field21;
    unsigned long long _field22;
};

struct proc_fdinfo {
    int _field1;
    unsigned int _field2;
};

struct proc_fileinfo {
    unsigned int fi_openflags;
    unsigned int fi_status;
    long long fi_offset;
    int fi_type;
    unsigned int fi_guardflags;
};

struct proc_taskallinfo {
    struct proc_bsdinfo _field1;
    struct proc_taskinfo _field2;
};

struct proc_taskinfo {
    unsigned long long _field1;
    unsigned long long _field2;
    unsigned long long _field3;
    unsigned long long _field4;
    unsigned long long _field5;
    unsigned long long _field6;
    int _field7;
    int _field8;
    int _field9;
    int _field10;
    int _field11;
    int _field12;
    int _field13;
    int _field14;
    int _field15;
    int _field16;
    int _field17;
    int _field18;
};

struct sockaddr_un {
    unsigned char sun_len;
    unsigned char sun_family;
    char sun_path[104];
};

struct sockbuf_info {
    unsigned int sbi_cc;
    unsigned int sbi_hiwat;
    unsigned int sbi_mbcnt;
    unsigned int sbi_mbmax;
    unsigned int sbi_lowat;
    short sbi_flags;
    short sbi_timeo;
};

struct socket_fdinfo {
    struct proc_fileinfo pfi;
    struct socket_info psi;
};

struct socket_info {
    struct vinfo_stat soi_stat;
    unsigned long long soi_so;
    unsigned long long soi_pcb;
    int soi_type;
    int soi_protocol;
    int soi_family;
    short soi_options;
    short soi_linger;
    short soi_state;
    short soi_qlen;
    short soi_incqlen;
    short soi_qlimit;
    short soi_timeo;
    unsigned short soi_error;
    unsigned int soi_oobmark;
    struct sockbuf_info soi_rcv;
    struct sockbuf_info soi_snd;
    int soi_kind;
    unsigned int rfu_1;
    union {
        struct in_sockinfo pri_in;
        struct tcp_sockinfo pri_tcp;
        struct un_sockinfo pri_un;
        struct ndrv_info pri_ndrv;
        struct kern_event_info pri_kern_event;
        struct kern_ctl_info pri_kern_ctl;
    } soi_proto;
};

struct tcp_sockinfo {
    struct in_sockinfo tcpsi_ini;
    int tcpsi_state;
    int tcpsi_timer[4];
    int tcpsi_mss;
    unsigned int tcpsi_flags;
    unsigned int rfu_1;
    unsigned long long tcpsi_tp;
};

struct un_sockinfo {
    unsigned long long unsi_conn_so;
    unsigned long long unsi_conn_pcb;
    CDUnion_e948d331 unsi_addr;
    CDUnion_e948d331 unsi_caddr;
};

struct vinfo_stat {
    unsigned int vst_dev;
    unsigned short vst_mode;
    unsigned short vst_nlink;
    unsigned long long vst_ino;
    unsigned int vst_uid;
    unsigned int vst_gid;
    long long vst_atime;
    long long vst_atimensec;
    long long vst_mtime;
    long long vst_mtimensec;
    long long vst_ctime;
    long long vst_ctimensec;
    long long vst_birthtime;
    long long vst_birthtimensec;
    long long vst_size;
    long long vst_blocks;
    int vst_blksize;
    unsigned int vst_flags;
    unsigned int vst_gen;
    unsigned int vst_rdev;
    long long vst_qspare[2];
};

#pragma mark Typedef'd Unions

typedef union {
    struct sockaddr_un ua_sun;
    char ua_dummy[255];
} CDUnion_e948d331;

typedef union {
    struct in4in6_addr ina_46;
    struct in6_addr ina_6;
} CDUnion_95c9f286;

