//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLAgent.h"

@class NSMutableSet, PLNSNotificationOperatorComposition;

@interface PLApplicationAgent : PLAgent
{
    PLNSNotificationOperatorComposition *_notificationSBApplicationStateChanged;
    NSMutableSet *_keyboardPlugins;
}

+ (id)installedBundleIDs;
+ (id)pluginEntryFromProxy:(id)arg1;
+ (id)appNameForBundleID:(id)arg1;
+ (id)entryAggregateDefinitionApplicationReason;
+ (id)entryEventNoneAllPlugins;
+ (id)entryEventNoneAllApps;
+ (id)entryEventNoneDefinitionApplicationMetadata;
+ (id)entryEventForwardDefinitionApplication;
+ (id)entryAggregateDefinitions;
+ (id)entryEventNoneDefinitions;
+ (id)entryEventBackwardDefinitions;
+ (id)entryEventForwardDefinitions;
+ (id)entryEventPointDefinitions;
+ (id)accountingGroupDefinitions;
+ (void)load;
+ (id)installedPlugins;
@property(retain) NSMutableSet *keyboardPlugins; // @synthesize keyboardPlugins=_keyboardPlugins;
@property(readonly) PLNSNotificationOperatorComposition *notificationSBApplicationStateChanged; // @synthesize notificationSBApplicationStateChanged=_notificationSBApplicationStateChanged;
- (void)storeUninstalledAppsInfo:(id)arg1;
- (void)storeInstalledAppsInfo:(id)arg1;
- (void)logUninstalledApp:(id)arg1;
- (void)logInstalledPlugin:(id)arg1;
- (void)logInstalledApp:(id)arg1;
- (void)addAccountingEvent:(id)arg1;
- (void)buildQueryWithQuery:(id)arg1 withKey:(id)arg2 withValue:(id)arg3;
- (void)logEventPointApplicationForDisplayID:(id)arg1;
- (void)logEventPointApplication;
- (void)logAllPlugins;
- (void)logAllApps;
- (void)logEventPointApplicationMetaDataForDisplayID:(id)arg1 withPid:(int)arg2;
- (void)logEventPointApplicationForDisplayID:(id)arg1 withPid:(int)arg2 withState:(id)arg3 withReasons:(id)arg4;
- (id)trimConditionsForEntryKey:(id)arg1 forTrimDate:(id)arg2;
- (void)initOperatorDependancies;
- (void).cxx_destruct;
- (void)log;
- (id)init;

@end

