//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLAgent.h"

@class PLXPCListenerOperatorComposition;

@interface PLHealthKitAgent : PLAgent
{
    PLXPCListenerOperatorComposition *_queryHandler;
    PLXPCListenerOperatorComposition *_hrReqHandler;
}

+ (id)entryEventIntervalDefinitions;
+ (id)entryEventPointDefinitions;
+ (void)load;
@property(retain) PLXPCListenerOperatorComposition *hrReqHandler; // @synthesize hrReqHandler=_hrReqHandler;
@property(retain) PLXPCListenerOperatorComposition *queryHandler; // @synthesize queryHandler=_queryHandler;
- (void)initOperatorDependancies;
- (void).cxx_destruct;

@end

