//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLAgent.h"

@class NSDate, NSMutableDictionary, PLXPCListenerOperatorComposition;

@interface PLIdentityServicesAgent : PLAgent
{
    PLXPCListenerOperatorComposition *_localMessageHandler;
    PLXPCListenerOperatorComposition *_networkStatsHandler;
    PLXPCListenerOperatorComposition *_infraWiFiRequestHandler;
    PLXPCListenerOperatorComposition *_localLinkTypeHandler;
    NSMutableDictionary *_previousStatsByPriority;
    NSDate *_initialEntryDate;
    NSDate *_lastLocalDeliveryLogDate;
    NSMutableDictionary *_lastEntryDatePerCategory;
}

+ (id)entryDefinitionIDSSocketStats;
+ (id)entryDefinitionIDSMessageStats;
+ (id)entryDefinitionLocalInfraWiFiRequests;
+ (id)entryDefinitionIDSLocalLink;
+ (id)entryEventIntervalDefinitions;
+ (id)entryEventForwardDefinitions;
+ (id)entryEventPointDefinitions;
+ (void)load;
@property(retain) NSMutableDictionary *lastEntryDatePerCategory; // @synthesize lastEntryDatePerCategory=_lastEntryDatePerCategory;
@property(retain) NSDate *initialEntryDate; // @synthesize initialEntryDate=_initialEntryDate;
@property(retain) NSMutableDictionary *previousStatsByPriority; // @synthesize previousStatsByPriority=_previousStatsByPriority;
@property(retain) PLXPCListenerOperatorComposition *localLinkTypeHandler; // @synthesize localLinkTypeHandler=_localLinkTypeHandler;
@property(retain) PLXPCListenerOperatorComposition *infraWiFiRequestHandler; // @synthesize infraWiFiRequestHandler=_infraWiFiRequestHandler;
@property(retain) PLXPCListenerOperatorComposition *networkStatsHandler; // @synthesize networkStatsHandler=_networkStatsHandler;
@property(retain) PLXPCListenerOperatorComposition *localMessageHandler; // @synthesize localMessageHandler=_localMessageHandler;
@property(retain) NSDate *lastLocalDeliveryLogDate; // @synthesize lastLocalDeliveryLogDate=_lastLocalDeliveryLogDate;
- (void)logLocalMessageTopic:(id)arg1;
- (void)logLocalLinkType:(id)arg1;
- (void)logLocalInfraWiFiFrequests:(id)arg1;
- (void)logIDSNetworkEntries:(id)arg1;
- (void)initOperatorDependancies;
- (void).cxx_destruct;
- (id)init;

@end

