//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLAgent.h"

@class NSDate, NSDictionary, PLEntryNotificationOperatorComposition;

@interface PLProcessNetworkAgent : PLAgent
{
    struct __NStatManager *_statManagerRef;
    PLEntryNotificationOperatorComposition *_batteryLevelChanged;
    NSDictionary *_lastEntry;
    NSDate *_lastEntryTime;
}

+ (id)entryEventNoneDefinitions;
+ (id)entryEventIntervalDefinitions;
+ (id)entryEventBackwardDefinitions;
+ (id)entryEventForwardDefinitions;
+ (id)entryEventPointDefinitions;
+ (id)accountingGroupDefinitions;
+ (id)railDefinitions;
+ (id)entryEventIntervalDefinitionUsage;
+ (id)entryEventBackwardDefinitionUsage;
+ (id)entryEventPointDefinitionConnection;
+ (void)load;
@property(retain) NSDate *lastEntryTime; // @synthesize lastEntryTime=_lastEntryTime;
@property(retain) NSDictionary *lastEntry; // @synthesize lastEntry=_lastEntry;
@property(retain) PLEntryNotificationOperatorComposition *batteryLevelChanged; // @synthesize batteryLevelChanged=_batteryLevelChanged;
- (void)initOperatorDependancies;
- (void)addSource:(id)arg1 toPID:(id)arg2;
- (void)logEventPointConnectionEvent:(id)arg1 forSource:(id)arg2;
- (void)transferSource:(id)arg1 fromPID:(id)arg2 toPID:(id)arg3;
- (void)didRemoveSource:(id)arg1;
- (void)didSetDescriptionBlock:(id)arg1 withDescription:(id)arg2;
- (void)didSetCountsBlock:(id)arg1 withCounts:(id)arg2;
@property struct __NStatManager *statManagerRef; // @synthesize statManagerRef=_statManagerRef;
- (void)didAddNewSource:(struct __NStatSource *)arg1;
- (void).cxx_destruct;
- (id)init;

@end

