//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <SAObjects/SADomainObject.h>

#import "SAAceSerializable.h"

@class NSArray, NSDictionary, NSString, NSURL, SALocalSearchOperationHours, SALocation;

@interface SALocalSearchBusiness2 : SADomainObject <SAAceSerializable>
{
}

+ (id)business2WithDictionary:(id)arg1 context:(id)arg2;
+ (id)business2;
@property(copy, nonatomic) NSString *descriptionText;
@property(copy, nonatomic) NSArray *reviewList;
@property(copy, nonatomic) NSArray *photoList;
@property(retain, nonatomic) SALocalSearchOperationHours *operationHours;
@property(copy, nonatomic) NSArray *offerLists;
@property(copy, nonatomic) NSDictionary *identifierMap;
@property(copy, nonatomic) NSString *priceRange;
@property(copy, nonatomic) NSURL *businessUrl;
- (void)updateUsingSet:(id)arg1 add:(id)arg2 remove:(id)arg3;
- (id)encodedClassName;
@property(copy, nonatomic) NSArray *categories;
@property(retain, nonatomic) SALocation *address;
@property(copy, nonatomic) NSString *phoneNumber;
@property(copy, nonatomic) NSString *name;
@property(copy, nonatomic) NSString *extSessionGuid;
- (id)groupIdentifier;
@property(copy, nonatomic) NSString *currencySymbol;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

