//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface PLCloudAssetBundle : NSObject
{
    NSString *_masterIdentifier;
    NSArray *_resources;
    unsigned int _combinedAvailableResourcesSize;
}

- (id)initWithAsset:(id)arg1 verifyAvailability:(BOOL)arg2;
@property(readonly, nonatomic) unsigned int combinedAvailableResourcesSize; // @synthesize combinedAvailableResourcesSize=_combinedAvailableResourcesSize;
@property(readonly, retain, nonatomic) NSString *masterIdentifier; // @synthesize masterIdentifier=_masterIdentifier;
@property(readonly, retain, nonatomic) NSArray *resources; // @synthesize resources=_resources;
- (id)description;

@end

