//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EAAccessoryInternal, NSArray, NSString;

@interface EAAccessory : NSObject
{
    EAAccessoryInternal *_internal;
}

- (id)_shortDescription;
@property(readonly, nonatomic) NSString *manufacturer;
- (id)macAddress;
@property(readonly, nonatomic) NSString *serialNumber;
@property(readonly, nonatomic) unsigned int connectionID;
@property(readonly, nonatomic) NSString *modelNumber;
@property(readonly, nonatomic) NSString *name;
@property(nonatomic) id <EAAccessoryDelegate> delegate;
- (id)description;
- (id)init;
- (void)dealloc;
- (BOOL)supportsPointOfInterest;
- (void)updateItemProperty:(int)arg1 withValue:(id)arg2;
- (void)updateSystemProperty:(int)arg1 withValue:(id)arg2;
- (BOOL)supportsAccessibility;
- (id)getVehicleInfoData;
- (void)setVehicleInfovehicleInfoInitialData:(id)arg1;
- (BOOL)sendEphemeris:(id)arg1;
- (BOOL)sendEphemerisPointDataGpsWeek:(unsigned int)arg1 gpsTOW:(double)arg2 latitude:(double)arg3 longitude:(double)arg4 accuracy:(unsigned short)arg5;
- (BOOL)sendGpsWeek:(unsigned int)arg1 gpsTOW:(double)arg2;
- (BOOL)getEphemerisExpirationInterval:(double *)arg1;
- (BOOL)getEphemerisRecommendRefreshInterval:(double *)arg1;
- (BOOL)getEphemerisURL:(id *)arg1;
- (void)resetIAPTimeSyncKalmanFilter;
- (void)getIAPTimeSyncInfo:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)setIAPTimeSyncParams:(id)arg1;
- (BOOL)setNMEASentencesToFilter:(id)arg1;
- (BOOL)getNMEASentence:(id *)arg1;
- (BOOL)accessoryHasNMEASentencesAvailable;
- (BOOL)supportsLocation;
- (BOOL)shouldBeHiddenFromUI;
- (BOOL)supportsPublicIap;
- (id)wakeToken;
- (id)vehicleInfoInitialData;
- (id)vehicleInfoSupportedTypes;
- (int)locationSentenceTypesMask;
- (unsigned int)eqIndex;
- (id)eqNames;
- (id)audioPorts;
- (int)classType;
- (id)preferredApp;
- (id)allPublicProtocolStrings;
- (BOOL)isAvailableOverBonjour;
- (BOOL)hasIPConnection;
- (id)_createWakeToken;
@property(readonly, nonatomic) NSArray *protocolStrings;
@property(readonly, nonatomic) NSString *hardwareRevision;
@property(readonly, nonatomic) NSString *firmwareRevision;
- (void)_removeSession:(id)arg1;
- (void)_addSession:(id)arg1;
- (id)_protocolIDForProtocolString:(id)arg1;
- (void)setVehicleInfoSupportedTypes:(id)arg1;
- (void)setLocationSentenceTypesMask:(int)arg1;
- (void)setEqIndex:(unsigned int)arg1;
- (void)setEqNames:(id)arg1;
- (void)_endSession:(unsigned int)arg1;
- (void)_openCompleteForSession:(unsigned int)arg1;
- (void)_updateAccessoryInfo:(id)arg1;
- (void)setBonjourName:(id)arg1;
- (id)bonjourName;
- (void)setIsAvailableOverBonjour:(BOOL)arg1;
- (void)setHasIPConnection:(BOOL)arg1;
- (BOOL)_internalNotPresentInIAPAccessoriesArray;
- (void)_setNotPresentInIAPAccessoriesArray:(BOOL)arg1;
- (void)_setConnected:(BOOL)arg1;
- (unsigned int)_internalConnectionID;
- (id)_initWithAccessory:(id)arg1;
@property(readonly, nonatomic, getter=isConnected) BOOL connected;

@end

