//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UICollectionViewFlowLayout.h>

@class NSIndexPath, UILongPressGestureRecognizer, _UIActivityGroupActivityCell;

@interface _UIActivityGroupViewFlowLayout : UICollectionViewFlowLayout
{
    UILongPressGestureRecognizer *_editingGestureRecognizer;
    NSIndexPath *_indexPathForDraggedItem;
    _UIActivityGroupActivityCell *_draggingView;
    struct UIOffset _draggingOffset;
}

@property(nonatomic) struct UIOffset draggingOffset; // @synthesize draggingOffset=_draggingOffset;
- (void)invalidateGroupViewLayoutAnimated:(BOOL)arg1;
- (id)draggingViewForItemAtIndexPath:(id)arg1;
- (void)cancelDraggingForGesture:(id)arg1;
- (BOOL)shouldCancelDraggingForGesture:(id)arg1;
- (void)updateDraggingViewForGesture:(id)arg1;
- (void)beginDraggingForGesture:(id)arg1;
@property(copy, nonatomic) NSIndexPath *indexPathForDraggedItem; // @synthesize indexPathForDraggedItem=_indexPathForDraggedItem;
- (void)adjustLayoutAttributesForDraggingIfNeeded:(id)arg1;
- (void)adjustLayoutAttributesIfNeeded:(id)arg1;
@property(retain, nonatomic) _UIActivityGroupActivityCell *draggingView; // @synthesize draggingView=_draggingView;
- (id)initialLayoutAttributesForAppearingItemAtIndexPath:(id)arg1;
- (id)finalLayoutAttributesForDisappearingItemAtIndexPath:(id)arg1;
- (BOOL)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;
- (id)indexPathForItemRecognizedByGesture:(id)arg1;
@property(retain, nonatomic) UILongPressGestureRecognizer *editingGestureRecognizer; // @synthesize editingGestureRecognizer=_editingGestureRecognizer;
- (void)handleEditingGesture:(id)arg1;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (void)dealloc;

@end

