//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UICollectionViewFlowLayout.h>

@interface _UIAlertControllerCollectionViewFlowLayout : UICollectionViewFlowLayout
{
    BOOL _hideSeparators;
    float _alignedDescriptiveLabelTextWidth;
    BOOL _shouldRoundFirstCell;
}

+ (Class)layoutAttributesClass;
@property BOOL shouldRoundFirstCell; // @synthesize shouldRoundFirstCell=_shouldRoundFirstCell;
- (float)_decorationDimension;
- (id)_topDecorationViewLayoutAttributesAtIndexPath:(id)arg1;
@property BOOL hideSeparators;
- (BOOL)_collectionViewIsLayingOutHorizontallyWithCellHeight:(float)arg1;
@property float alignedDescriptiveLabelTextWidth;
- (id)layoutAttributesForDecorationViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (id)init;

@end

