//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate.h"
#import "_UIAlertActionRepresenting.h"

@class NSLayoutConstraint, NSMutableArray, NSString, UIAlertAction, UIAlertControllerVisualStyle, UIGestureRecognizer, UIImageView, UILabel;

@interface _UIAlertControllerActionView : UIView <UIGestureRecognizerDelegate, _UIAlertActionRepresenting>
{
    NSLayoutConstraint *_minimumHeightConstraint;
    UIView *labelContainerView;
    UILabel *label;
    UILabel *descriptiveLabel;
    UIImageView *imageView;
    UIImageView *checkView;
    UIView *highlightedBackgroundContainerView;
    NSMutableArray *highlightedBackgroundConstraints;
    unsigned int _roundedCorners;
    NSMutableArray *havingDescriptiveLabelConstraints;
    NSMutableArray *notHavingDescriptiveLabelConstraints;
    NSLayoutConstraint *_descriptiveLabelWidthConstraint;
    UIAlertAction *_action;
    UIAlertControllerVisualStyle *_visualStyle;
    id selectedTarget;
    SEL selectedAction;
    id highlightTarget;
    SEL highlightAction;
    BOOL _hasDescriptiveText;
    UIGestureRecognizer *_selectGestureRecognizer;
    BOOL _discrete;
}

@property BOOL discrete; // @synthesize discrete=_discrete;
- (void)setHighlightTarget:(id)arg1 action:(SEL)arg2;
- (void)setSelectedTarget:(id)arg1 action:(SEL)arg2;
@property(readonly) float currentDescriptiveLabelTextWidth;
@property float alignedDescriptiveLabelTextWidth;
- (void)_updateMinimumHeight;
- (void)_recomputeBackgroundColor;
- (void)_updateTextAlignmentForDescriptiveText:(BOOL)arg1;
- (void)_prepareConstraintsForDescriptiveText:(BOOL)arg1;
- (float)_minimumLabelScaleFactor;
- (id)_titleFont;
- (void)_recomputeTextColor;
- (void)_triggerSelect;
- (id)_touchForEvent:(id)arg1;
- (void)_updateFontSize;
- (void)_prepareConstraints;
- (void)_contentSizeChanged;
- (void)_action:(id)arg1 changedToChecked:(BOOL)arg2;
- (void)_action:(id)arg1 changedToEnabled:(BOOL)arg2;
@property UIAlertControllerVisualStyle *visualStyle;
- (void)_selectGestureChanged:(id)arg1;
- (void)_installSelectGestureRecognizer;
- (void)_uninstallSelectGestureRecognizer;
- (void)_updateBackgroundView;
@property(copy, nonatomic) UIAlertAction *action;
@property(nonatomic, getter=isHighlighted) BOOL highlighted;
- (void)_updateStyle;
- (BOOL)_isFocusableElement;
- (void)tintColorDidChange;
- (void)_focusStateDidChange;
- (id)tintColor;
- (void)traitCollectionDidChange:(id)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

