//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _UIBlendingHighlightView : UIView
{
    UIView *_colorBurnView;
    UIView *_plusDView;
}

+ (id)_blendingPressedView;
+ (id)_blendingSeparatorView;
- (id)initWithFrame:(struct CGRect)arg1 colorBurnColor:(id)arg2 plusDColor:(id)arg3;
@property float cornerRadius;
- (void)dealloc;

@end

