//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class NSURL, _UIDocumentPickerContainerModel, _UIDocumentPickerSortOrderView, _UIDocumentPickerViewServiceViewController;

@interface _UIDocumentPickerDocumentTableViewController : UITableViewController
{
    BOOL _shouldHideSortBar;
    _UIDocumentPickerViewServiceViewController *_serviceViewController;
    NSURL *_observedURL;
    _UIDocumentPickerContainerModel *_model;
    id _monitoringToken;
    _UIDocumentPickerSortOrderView *_sortView;
}

@property(retain, nonatomic) NSURL *observedURL; // @synthesize observedURL=_observedURL;
@property(retain, nonatomic) id monitoringToken; // @synthesize monitoringToken=_monitoringToken;
@property(retain, nonatomic) _UIDocumentPickerSortOrderView *sortView; // @synthesize sortView=_sortView;
@property(nonatomic) BOOL shouldHideSortBar; // @synthesize shouldHideSortBar=_shouldHideSortBar;
- (void)setMonitoring:(BOOL)arg1;
- (void)_dynamicTypeSizeChanged:(id)arg1;
- (void)_sortViewChanged:(id)arg1;
- (id)initWithModel:(id)arg1;
- (void)containersChangedWithSnapshot:(id)arg1 differences:(id)arg2;
@property(retain, nonatomic) _UIDocumentPickerContainerModel *model; // @synthesize model=_model;
@property(nonatomic) _UIDocumentPickerViewServiceViewController *serviceViewController; // @synthesize serviceViewController=_serviceViewController;
- (void)willMoveToParentViewController:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)didMoveToParentViewController:(id)arg1;
- (void)viewDidLayoutSubviews;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)dealloc;

@end

