//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSMapTable, NSString, NSURL, _UIDocumentPickerContainerModel;

@interface _UIDocumentPickerContainerItem : NSObject
{
    _UIDocumentPickerContainerModel *_weak_parentModel;
    BOOL _pickable;
    id _item;
    int _type;
    NSMapTable *_thumbnailsBySize;
    NSString *_pickabilityReason;
}

+ (void)clearLRUThumbnailCache;
+ (void)markThumbnailAsRecentlyUsed:(id)arg1;
+ (id)_lruThumbnailArray;
@property(copy, nonatomic) NSString *pickabilityReason; // @synthesize pickabilityReason=_pickabilityReason;
@property(retain, nonatomic) NSMapTable *thumbnailsBySize; // @synthesize thumbnailsBySize=_thumbnailsBySize;
- (id)sortTag;
@property(readonly, nonatomic) NSDate *sortDate;
- (id)tagBlipsWithHeight:(float)arg1 scale:(float)arg2;
@property(readonly, retain, nonatomic) NSString *subtitle2;
@property(readonly, retain, nonatomic) NSString *subtitle;
- (id)thumbnailWithSize:(struct CGSize)arg1 scale:(float)arg2;
- (id)_blipWithTags:(id)arg1 height:(float)arg2 scale:(float)arg3;
- (id)tags;
- (id)_blockingThumbnailWithSize:(struct CGSize)arg1 scale:(float)arg2;
- (id)_createThumbnailWithSize:(struct CGSize)arg1 scale:(float)arg2;
@property(nonatomic) __weak _UIDocumentPickerContainerModel *parentModel;
- (id)_defaultThumbnailWithSize:(struct CGSize)arg1 scale:(float)arg2;
@property(retain, nonatomic) id item; // @synthesize item=_item;
@property(nonatomic) BOOL pickable; // @synthesize pickable=_pickable;
- (id)initWithItem:(id)arg1;
@property(readonly, retain, nonatomic) NSString *title;
@property(readonly, nonatomic) int type; // @synthesize type=_type;
@property(readonly, retain, nonatomic) NSURL *url;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;

@end

