//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class _UIBackdropView;

@interface _UIDimmingKnockoutBackdropView : UIView
{
    _UIBackdropView *backdropView;
    UIView *dimmingKnockoutView;
}

- (id)_dimmingKnockoutBackgroundColorForBackdropStyle:(int)arg1;
- (id)_filterForBackdropStyle:(int)arg1;
- (id)initWithStyle:(int)arg1;
@property float cornerRadius;
- (void)dealloc;

@end

