//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UISearchBarDelegate.h"

@class NSLayoutConstraint, NSString, UIButton, UISearchBar, UISegmentedControl, UIViewController, _UIDocumentPickerSearchContainerModel, _UINavigationControllerPalette;

@interface _UIDocumentPickerSearchPaletteView : UIView <UISearchBarDelegate>
{
    _UINavigationControllerPalette *_palette;
    UISearchBar *_searchBar;
    UISegmentedControl *_containerDisplayMode;
    _UIDocumentPickerSearchContainerModel *_searchModel;
    UIViewController *_searchController;
    UIButton *_cancelButton;
    NSLayoutConstraint *_searchFieldLeftConstraint;
    NSLayoutConstraint *_searchFieldRightConstraint;
}

@property(retain, nonatomic) UIViewController *searchController; // @synthesize searchController=_searchController;
@property(retain, nonatomic) _UIDocumentPickerSearchContainerModel *searchModel; // @synthesize searchModel=_searchModel;
@property(nonatomic) _UINavigationControllerPalette *palette; // @synthesize palette=_palette;
@property(retain, nonatomic) NSLayoutConstraint *searchFieldRightConstraint; // @synthesize searchFieldRightConstraint=_searchFieldRightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *searchFieldLeftConstraint; // @synthesize searchFieldLeftConstraint=_searchFieldLeftConstraint;
- (void)updateViewsAndConstraintsForSearch:(BOOL)arg1;
@property(retain, nonatomic) UISegmentedControl *containerDisplayMode; // @synthesize containerDisplayMode=_containerDisplayMode;
- (void)searchCanceled:(id)arg1;
- (void)displayModeChanged:(id)arg1;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
- (id)serviceViewController;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

