//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

@interface _UIEmojiScrollView : UIScrollView
{
    double _delay;
    BOOL _canDragToScroll;
}

- (void)_lookForScrolling;
- (void)_stopLookingForScrolling;
- (double)_touchDelayForScrollDetection;
- (BOOL)touchesShouldCancelInContentView:(id)arg1;
- (BOOL)touchesShouldBegin:(id)arg1 withEvent:(id)arg2 inContentView:(id)arg3;
- (void)setContentOffset:(struct CGPoint)arg1;
@property double delay; // @synthesize delay=_delay;
- (id)initWithFrame:(struct CGRect)arg1;

@end

