//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIWindow.h>

@class _UIHostedWindowHostingHandle;

@interface _UIHostedWindow : UIWindow
{
    int _hostTintAdjustmentMode;
}

- (BOOL)_presentActionSheet:(id)arg1 inView:(id)arg2 fromYCoordinate:(float)arg3;
@property(nonatomic, setter=_setHostTintAdjustmentMode:) int _hostTintAdjustmentMode; // @synthesize _hostTintAdjustmentMode;
@property(readonly, nonatomic) _UIHostedWindowHostingHandle *hostingHandle;
- (unsigned int)contextID;
- (int)_defaultTintAdjustmentMode;
- (void)_unregisterScrollToTopView:(id)arg1;
- (void)_registerScrollToTopView:(id)arg1;
- (void)_updateTransformLayerForClassicPresentation;
- (void)_updateAppTintView;
- (BOOL)_canPromoteFromKeyWindowStack;
- (void)_configureContextOptions:(id)arg1;
- (BOOL)_isClippedByScreenJail;
- (BOOL)_isOffsetByScreenJail;
- (BOOL)_isScaledByScreenJail;
- (BOOL)_isRotatedByScreenJail;
- (BOOL)_usesWindowServerHitTesting;
- (BOOL)_isConstrainedByScreenJail;
- (BOOL)_isWindowServerHostingManaged;
- (BOOL)_needsShakesWhenInactive;
- (id)initWithFrame:(struct CGRect)arg1;

@end

