//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIAlertControllerContaining.h"
#import "UIAlertControllerVisualStyleProviding.h"
#import "_UIAlertControllerTextFieldViewControllerContaining.h"

@class NSArray, NSAttributedString, NSMutableArray, NSObject<UIAlertControllerVisualStyleProviding>, NSSet, NSString, UIAlertAction, UIGestureRecognizer, UIPopoverController, UIView, _UIAlertControllerTextFieldViewController;

@interface UIAlertController : UIViewController <UIAlertControllerContaining, _UIAlertControllerTextFieldViewControllerContaining, UIAlertControllerVisualStyleProviding>
{
    NSString *_message;
    NSAttributedString *_attributedTitle;
    NSAttributedString *_attributedMessage;
    NSMutableArray *_actions;
    NSSet *_linkedAlertControllers;
    UIAlertAction *_cancelAction;
    int _resolvedStyle;
    int _preferredStyle;
    NSObject<UIAlertControllerVisualStyleProviding> *_styleProvider;
    UIViewController *_contentViewController;
    _UIAlertControllerTextFieldViewController *_textFieldViewController;
    BOOL _textFieldsHidden;
    UIGestureRecognizer *_backButtonDismissGestureRecognizer;
    id _ownedTransitioningDelegate;
    BOOL _shouldEnsureContentControllerViewIsVisibleOnAppearance;
    BOOL __shouldAllowNilParameters;
    BOOL __shouldFlipFrameForShimDismissal;
    UIAlertAction *__defaultAlertAction;
    UIPopoverController *__compatibilityPopoverController;
}

+ (id)_alertControllerWithTitle:(id)arg1 message:(id)arg2;
+ (void)_setShouldUsePresentationController:(BOOL)arg1;
+ (BOOL)_shouldUsePresentationController;
+ (id)alertControllerWithTitle:(id)arg1 message:(id)arg2 preferredStyle:(int)arg3;
+ (BOOL)_shouldSendLegacyMethodsFromViewWillTransitionToSize;
@property(nonatomic, setter=_setCompatibilityPopoverController:) UIPopoverController *_compatibilityPopoverController; // @synthesize _compatibilityPopoverController=__compatibilityPopoverController;
@property(setter=_setShouldAllowNilParameters:) BOOL _shouldAllowNilParameters; // @synthesize _shouldAllowNilParameters=__shouldAllowNilParameters;
@property(setter=_setDefaultAlertAction:) UIAlertAction *_defaultAlertAction; // @synthesize _defaultAlertAction=__defaultAlertAction;
@property(nonatomic, setter=_setShouldEnsureContentControllerViewIsVisibleOnAppearance:) BOOL _shouldEnsureContentControllerViewIsVisibleOnAppearance; // @synthesize _shouldEnsureContentControllerViewIsVisibleOnAppearance;
- (void)_removeAllTextFields;
@property(copy, nonatomic, getter=_attributedMessage, setter=_setAttributedMessage:) NSAttributedString *attributedMessage;
@property(copy, nonatomic, getter=_attributedTitle, setter=_setAttributedTitle:) NSAttributedString *attributedTitle;
- (BOOL)_shouldFitWidthToContentViewControllerWidth;
- (BOOL)_shouldSizeToFillSuperview;
- (void)_flipFrameForShimDismissalIfNecessary;
- (void)_updateViewFrameForLandscapePresentationInShimIfNecessary;
- (id)linkedAlertControllers;
- (void)unlinkAlertController:(id)arg1;
- (void)linkAlertController:(id)arg1;
- (void)_dismissFromPopoverDimmingView;
- (BOOL)_shouldDismissAction:(id)arg1;
- (void)_actionViewTapped:(id)arg1;
- (void)_actionViewHighlightChanged:(id)arg1;
@property(retain, nonatomic, getter=_styleProvider, setter=_setStyleProvider:) NSObject<UIAlertControllerVisualStyleProviding> *styleProvider;
@property(setter=_setTextFieldsHidden:) BOOL _textFieldsHidden;
- (void)addTextFieldWithConfigurationHandler:(CDUnknownBlockType)arg1;
- (void)_actionChanged:(id)arg1;
- (void)_addActionWithTitle:(id)arg1 image:(id)arg2 style:(int)arg3 handler:(CDUnknownBlockType)arg4;
- (void)_addActionWithTitle:(id)arg1 style:(int)arg2 handler:(CDUnknownBlockType)arg3;
- (void)_returnKeyPressedInLastTextField;
- (struct __CFString *)_powerLoggingEventName;
- (void)viewDidDisappear;
- (void)_logBeingDismissed;
- (void)viewDidAppear;
- (void)_logBeingPresented;
- (BOOL)_hasContentToDisplay;
@property(readonly) BOOL _shouldProvideDimmingView;
- (BOOL)_isPresentedAsPopover;
- (id)_alertControllerContainer;
@property BOOL _shouldFlipFrameForShimDismissal; // @synthesize _shouldFlipFrameForShimDismissal=__shouldFlipFrameForShimDismissal;
- (int)_modalPresentationStyleForResolvedStyle;
- (BOOL)_viewControllerIsPresentedInPopover:(id)arg1;
- (void)_fireOffActionOnTargetIfValidForAction:(id)arg1;
- (void)_dismissAnimated:(BOOL)arg1 triggeringAction:(id)arg2 triggeredByPopoverDimmingView:(BOOL)arg3;
- (id)cancelAction;
- (void)_attemptAnimatedDismissWithGestureRecognizer:(id)arg1;
- (void)_reevaluateResolvedStyle;
- (void)_dismissFromBackButton:(id)arg1;
@property(readonly) UIAlertAction *_cancelAction; // @synthesize _cancelAction;
- (id)visualStyleForAlertControllerStyle:(int)arg1 traitCollection:(id)arg2 descriptor:(id)arg3;
- (id)_currentDescriptor;
@property(readonly) int _resolvedStyle; // @synthesize _resolvedStyle;
- (void)_recomputePreferredContentSize;
- (void)_installBackGestureRecognizer;
- (void)_resolvedStyleChanged;
- (void)_updateProvidedStyle;
- (void)_clearActionHandlers;
- (void)_uninstallBackGestureRecognizer;
- (void)setTextFieldsCanBecomeFirstResponder:(BOOL)arg1;
- (void)_dismissAnimated:(BOOL)arg1 triggeringAction:(id)arg2;
@property(readonly, nonatomic) NSArray *textFields;
- (void)_updateShouldAlignToKeyboard;
@property(retain, nonatomic) UIViewController *contentViewController;
@property(nonatomic) int preferredStyle;
- (id)_textFieldViewController;
@property(readonly) NSMutableArray *_actions; // @synthesize _actions;
- (id)_alertControllerView;
- (void)setCancelAction:(id)arg1;
- (void)_updateModalPresentationStyle;
- (void)addAction:(id)arg1;
- (void)_addActionWithTitle:(id)arg1 style:(int)arg2 handler:(CDUnknownBlockType)arg3 shouldDismissHandler:(CDUnknownBlockType)arg4;
- (id)_containedAlertController;
- (float)_contentVerticalInsets;
@property(readonly) BOOL _shouldAlignToKeyboard;
- (id)_dismissGestureRecognizer;
- (BOOL)_canDismissWithGestureRecognizer;
@property(copy, nonatomic) NSString *message;
@property(readonly) UIView *_dimmingView;
- (void)_getRotationContentSettings:(CDStruct_f39609a0 *)arg1;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (BOOL)_requiresCustomPresentationController;
- (id)_presentationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (BOOL)_isSupportedInterfaceOrientation:(int)arg1;
- (id)_requiredNotificationsForRemoteServices;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)setModalPresentationStyle:(int)arg1;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)preferredContentSizeDidChangeForChildContentContainer:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)traitCollectionDidChange:(id)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
@property(readonly, nonatomic) NSArray *actions;
@property(readonly) UIView *_foregroundView;
@property(copy, nonatomic) NSString *title;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

