//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIDictationView.h>

@interface UIDictationPopUpView : UIDictationView
{
}

- (id)createEndpointButtonWithRect:(struct CGRect)arg1 action:(SEL)arg2;
- (BOOL)drawsOwnBackground;
- (void)returnToKeyboard;
- (void)setState:(int)arg1;
- (void)layoutSubviews;

@end

