//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIInputSetHostView.h>

@class UIKBRenderConfig;

@interface UIInputSetContainerView : UIInputSetHostView
{
    UIKBRenderConfig *_renderConfig;
}

+ (BOOL)_notifyOnExplicitLayout;
- (id)_inputWindowController;
- (void)_setAccessoryViewFrame:(struct CGRect)arg1;
- (struct CGRect)_accessoryViewFrame;
- (id)_inheritedRenderConfig;
- (int)textEffectsVisibilityLevel;
- (void)_setRenderConfig:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

