//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKBRenderFactoryEmoji_iPhone.h>

@interface UIKBRenderFactoryEmoji_iPad : UIKBRenderFactoryEmoji_iPhone
{
}

- (float)keyCornerRadius;
- (id)thinKeycapsFontName;
- (void)_customizeTraits:(id)arg1 forPopupForKey:(id)arg2 withRenderConfig:(id)arg3 keycapsFontName:(id)arg4;
- (id)lightKeycapsFontName;
- (id)_traitsForKey:(id)arg1 onKeyplane:(id)arg2;

@end

