//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKBKeyView.h>

#import "UIKeyboardEmojiInput.h"
#import "UIKeyboardEmojiPressIndicationDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSMutableArray, NSString, UIKeyboardEmojiCategory, UIKeyboardEmojiInputController, UILabel, UIPageControl, UIScrollView, UIView;

@interface UIKeyboardEmojiScrollView : UIKBKeyView <UIScrollViewDelegate, UIKeyboardEmojiInput, UIKeyboardEmojiPressIndicationDelegate>
{
    UIKeyboardEmojiInputController *_inputController;
    UIKeyboardEmojiCategory *_category;
    UIPageControl *_pageControl;
    UIScrollView *_scrollView;
    UILabel *_categoryLabel;
    UILabel *_optionalDescription;
    NSMutableArray *_pages;
    int _currentPage;
    UIView *_pressIndicator;
    BOOL _whiteText;
}

@property BOOL whiteText; // @synthesize whiteText=_whiteText;
@property(retain, nonatomic) UIView *pressIndicator; // @synthesize pressIndicator=_pressIndicator;
- (void)goToFirstPage;
- (void)setScrollDelay:(double)arg1;
- (BOOL)shouldCache;
- (void)reloadForCategory:(id)arg1;
- (void)saveFirstVisibleEmojiIndex;
- (int)emojiCountPerPageForRotation;
- (void)interruptScrolling;
- (void)delayLayout;
- (void)ensureSurrounded;
- (void)clearPages;
- (void)layoutPages;
- (void)layoutRecents;
- (void)doLayout;
- (void)pageChanged;
- (void)removePressIndicator;
- (void)installPressIndicatorAtPoint:(struct CGPoint)arg1;
- (int)currentPage;
- (void)forceLayout;
- (id)initWithFrame:(struct CGRect)arg1 keyplane:(id)arg2 key:(id)arg3;
- (void)setRenderConfig:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

