//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface UIKeyboardEmoji : NSObject
{
    NSString *_emojiString;
    BOOL _hasDingbat;
}

+ (id)emojiWithString:(id)arg1 hasDingbat:(BOOL)arg2;
@property BOOL hasDingbat; // @synthesize hasDingbat=_hasDingbat;
- (id)key;
@property(retain, nonatomic) NSString *emojiString; // @synthesize emojiString=_emojiString;
- (id)initWithString:(id)arg1 hasDingbat:(BOOL)arg2;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;

@end

