//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface UIKeyboardEmojiCategory : NSObject
{
    int _categoryType;
    NSArray *_emoji;
    int _lastVisibleFirstEmojiIndex;
}

+ (id)categoryForType:(int)arg1;
+ (id)localizedStringForKey:(id)arg1;
+ (id)emojiRecentsFromPreferences;
+ (BOOL)hasVariantsForEmoji:(id)arg1;
+ (int)numberOfCategories;
+ (id)categories;
@property(nonatomic) int lastVisibleFirstEmojiIndex; // @synthesize lastVisibleFirstEmojiIndex=_lastVisibleFirstEmojiIndex;
@property(readonly, getter=recentDescription) NSString *recentDescription;
@property(readonly, getter=displaySymbol) NSString *displaySymbol;
- (void)releaseCategories;
@property(readonly, getter=displayName) NSString *displayName;
@property int categoryType; // @synthesize categoryType=_categoryType;
@property(retain) NSArray *emoji; // @synthesize emoji=_emoji;
@property(readonly, nonatomic, getter=name) NSString *name;
- (id)description;
- (void)dealloc;

@end

