//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSDictionary, UIKBRenderConfig, UIKeyboardEmojiInputController, UIKeyboardEmojiView, UITouch;

@interface UIKeyboardEmojiPage : UIView
{
    NSArray *_emoji;
    int _numRows;
    int _numCols;
    int _numPages;
    struct CGPoint _emojiPadding;
    struct CGPoint _margin;
    struct CGSize _emojiSize;
    struct CGRect _keyActivationRect;
    UITouch *_activeTouch;
    BOOL _needsLayout;
    BOOL _needsEmojiRendering;
    UIKBRenderConfig *_renderConfig;
    NSDictionary *_emojiAttributes;
    UIKeyboardEmojiView *_touched;
    UIKeyboardEmojiView *_pendingDisplay;
    UIKeyboardEmojiView *_onDisplay;
    UIKeyboardEmojiInputController *_inputController;
}

@property(retain, nonatomic) NSDictionary *emojiAttributes; // @synthesize emojiAttributes=_emojiAttributes;
@property BOOL needsEmojiRendering; // @synthesize needsEmojiRendering=_needsEmojiRendering;
@property struct CGRect keyActivationRect; // @synthesize keyActivationRect=_keyActivationRect;
- (void)generateSubviews;
- (int)takeEmoji:(id)arg1 fromIndex:(int)arg2;
@property(readonly, nonatomic) int emojiCountPerPage;
- (void)touchMoved:(id)arg1;
- (void)touchBegan:(id)arg1;
@property UIKeyboardEmojiInputController *inputController; // @synthesize inputController=_inputController;
- (void)removeDisplayedPopup:(id)arg1;
- (void)showPendingPopup:(id)arg1;
- (id)closestForPoint:(struct CGPoint)arg1;
- (void)touchEnded:(id)arg1;
- (void)checkForStalePopup:(id)arg1;
- (struct CGRect)emojiRectForPoint:(struct CGPoint)arg1 index:(unsigned int *)arg2;
@property(retain) UIKeyboardEmojiView *pendingDisplay; // @synthesize pendingDisplay=_pendingDisplay;
@property(retain) UIKeyboardEmojiView *touched; // @synthesize touched=_touched;
- (struct CGRect)rectForRow:(int)arg1 Col:(int)arg2;
- (void)deactivatePopUps;
@property(retain) UIKeyboardEmojiView *onDisplay; // @synthesize onDisplay=_onDisplay;
- (void)cancelPendingPopupChanges;
- (void)updateLayoutConstants;
@property(retain) NSArray *emoji; // @synthesize emoji=_emoji;
- (void)touchCancelled:(id)arg1;
@property(retain) UITouch *activeTouch; // @synthesize activeTouch=_activeTouch;
@property(retain) UIKBRenderConfig *renderConfig; // @synthesize renderConfig=_renderConfig;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)removeFromSuperview;
- (void)setFrame:(struct CGRect)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

