//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKeyboardEmojiCategoryBar.h>

@class UIImage;

@interface UIKeyboardEmojiCategoryBar_iPad : UIKeyboardEmojiCategoryBar
{
    UIImage *categoryKeyImage;
    UIImage *categoryKeyHighlightedImage;
    UIImage *dividerImage;
    UIImage *dividerHighlightedImage;
}

@property(retain) UIImage *dividerImage; // @synthesize dividerImage;
@property(retain) UIImage *dividerHighlightedImage; // @synthesize dividerHighlightedImage;
@property(retain) UIImage *categoryKeyHighlightedImage; // @synthesize categoryKeyHighlightedImage;
- (struct CGRect)frameForSegment:(int)arg1;
@property(retain) UIImage *categoryKeyImage; // @synthesize categoryKeyImage;
- (void)updateSegmentAndDividers:(int)arg1;
- (void)releaseImagesAndViews;
- (void)updateSegmentImages;
- (void)layoutSubviews;
- (void)drawRect:(struct CGRect)arg1;

@end

