//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class UIKBRenderConfig, UIKeyboardEmoji, UIKeyboardEmojiImageView, UIView, UIView<UIKeyboardEmojiPressIndicationDelegate>;

@interface UIKeyboardEmojiView : UIControl
{
    UIKeyboardEmoji *_emoji;
    UIView *_popup;
    UIKeyboardEmojiImageView *_imageView;
    UIKBRenderConfig *_renderConfig;
    UIView<UIKeyboardEmojiPressIndicationDelegate> *_delegate;
}

+ (void)recycleEmojiView:(id)arg1;
+ (id)emojiViewForEmoji:(id)arg1 withFrame:(struct CGRect)arg2;
- (id)initWithFrame:(struct CGRect)arg1 emoji:(id)arg2;
- (void)setEmoji:(id)arg1 withFrame:(struct CGRect)arg2;
@property(retain) UIView *popup; // @synthesize popup=_popup;
@property(retain) UIKeyboardEmojiImageView *imageView; // @synthesize imageView=_imageView;
- (id)createAndInstallKeyPopupView;
- (void)uninstallPopup;
@property(retain) UIKeyboardEmoji *emoji; // @synthesize emoji=_emoji;
@property(retain, nonatomic) UIKBRenderConfig *renderConfig; // @synthesize renderConfig=_renderConfig;
@property(retain) UIView<UIKeyboardEmojiPressIndicationDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)dealloc;

@end

