//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString;

@interface UIKeyboardEmojiImageView : UIView
{
    NSString *_emojiString;
}

- (id)initWithFrame:(struct CGRect)arg1 emojiString:(id)arg2;
@property(retain, nonatomic) NSString *emojiString;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;

@end

