//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UITabBarItem, UIView;

@interface UITabBarItemProxy : NSObject
{
    UITabBarItem *_item;
    UIView *_view;
}

- (id)initWithItem:(id)arg1 inTabBar:(id)arg2;
- (id)item;
- (void)setSelected:(BOOL)arg1;
- (id)view;
- (void)dealloc;

@end

