//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ABPropertyGroupItem, ABPropertyIDSRequest, NSArray, NSMutableArray;

@interface ABPropertyBestFaceTimeQuery : NSObject
{
    NSMutableArray *_faceTimeableItems;
    id <ABPropertyBestFaceTimeQueryDelegate> _delegate;
    NSArray *_propertyItems;
    ABPropertyIDSRequest *_faceTimeIDSRequest;
}

@property(nonatomic) id <ABPropertyBestFaceTimeQueryDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dealloc;
@property(retain) NSMutableArray *faceTimeableItems; // @synthesize faceTimeableItems=_faceTimeableItems;
@property(retain, nonatomic) NSArray *propertyItems; // @synthesize propertyItems=_propertyItems;
@property(retain, nonatomic) ABPropertyIDSRequest *faceTimeIDSRequest; // @synthesize faceTimeIDSRequest=_faceTimeIDSRequest;
- (id)initWithPropertyItems:(id)arg1;
@property(readonly) ABPropertyGroupItem *bestFaceTimeProperty;

@end

