//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <GeoServices/GEONetworkObserver.h>

#import "GEOGizmoXPCInterface.h"

@class NSXPCConnection;

@interface _GEOCompanionNetworkObserver : GEONetworkObserver <GEOGizmoXPCInterface>
{
    NSXPCConnection *_connection;
    BOOL _initialized;
}

- (BOOL)isNetworkReachable;
- (void)_networkObserversInitialize;
- (void)initializeIfNecessary;
- (void)didChangePairedDeviceReachability:(BOOL)arg1;
- (void)didChangeActiveTileGroup:(id)arg1;
- (void)updateNavigationRouteStatus:(id)arg1;
- (void)updateNavigationRouteDetails:(id)arg1 routeStatus:(id)arg2 routeContext:(id)arg3;
- (id)init;
- (void)dealloc;

@end

