//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class GEOPDViewportInfo, NSData, NSString;

@interface GEOPDSearchParameters : PBCodable <NSCopying>
{
    unsigned int _maxResults;
    NSString *_searchString;
    int _sortOrder;
    NSData *_suggestionEntryMetadata;
    NSData *_suggestionMetadata;
    GEOPDViewportInfo *_viewportInfo;
    CDStruct_6c9bcd7c _has;
}

- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)mergeFrom:(id)arg1;
@property(retain, nonatomic) GEOPDViewportInfo *viewportInfo; // @synthesize viewportInfo=_viewportInfo;
- (id)initWithSearchQuery:(id)arg1 entryMetadata:(id)arg2 metadata:(id)arg3 maxResults:(unsigned int)arg4 traits:(id)arg5;
@property(nonatomic) BOOL hasSortOrder;
@property(readonly, nonatomic) BOOL hasViewportInfo;
@property(retain, nonatomic) NSData *suggestionEntryMetadata; // @synthesize suggestionEntryMetadata=_suggestionEntryMetadata;
@property(readonly, nonatomic) BOOL hasSuggestionEntryMetadata;
@property(retain, nonatomic) NSData *suggestionMetadata; // @synthesize suggestionMetadata=_suggestionMetadata;
@property(readonly, nonatomic) BOOL hasSuggestionMetadata;
@property(nonatomic) BOOL hasMaxResults;
@property(nonatomic) unsigned int maxResults; // @synthesize maxResults=_maxResults;
@property(retain, nonatomic) NSString *searchString; // @synthesize searchString=_searchString;
- (id)dictionaryRepresentation;
@property(nonatomic) int sortOrder; // @synthesize sortOrder=_sortOrder;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;
@property(readonly, nonatomic) BOOL hasSearchString;

@end

