//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class GEOLatLng, GEOStructuredAddress, NSString;

@interface GEOPDPlaceRefinementParameters : PBCodable <NSCopying>
{
    unsigned long long _muid;
    GEOStructuredAddress *_addressHint;
    GEOLatLng *_locationHint;
    NSString *_placeNameHint;
    int _resultProviderId;
    CDStruct_12a4a01e _has;
}

- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (id)initWithSearchURLQuery:(id)arg1 coordinate:(CDStruct_c3b9c2ee)arg2 muid:(unsigned long long)arg3 resultProviderId:(int)arg4;
- (id)initWithCoordinateHint:(CDStruct_c3b9c2ee)arg1 addressHint:(id)arg2 placeNameHint:(id)arg3;
- (id)initWithMapItemToRefine:(id)arg1;
- (id)initWithMuid:(unsigned long long)arg1 addressHint:(id)arg2 locationHint:(CDStruct_c3b9c2ee)arg3 placeNameHint:(id)arg4 resultProviderId:(int)arg5;
@property(retain, nonatomic) NSString *placeNameHint; // @synthesize placeNameHint=_placeNameHint;
@property(retain, nonatomic) GEOStructuredAddress *addressHint; // @synthesize addressHint=_addressHint;
@property(retain, nonatomic) GEOLatLng *locationHint; // @synthesize locationHint=_locationHint;
@property(readonly, nonatomic) BOOL hasPlaceNameHint;
@property(readonly, nonatomic) BOOL hasAddressHint;
@property(readonly, nonatomic) BOOL hasLocationHint;
@property(nonatomic) BOOL hasMuid;
@property(nonatomic) unsigned long long muid; // @synthesize muid=_muid;
@property(nonatomic) int resultProviderId; // @synthesize resultProviderId=_resultProviderId;
@property(nonatomic) BOOL hasResultProviderId;
- (id)dictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;

@end

