//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSString;

@interface GEOResourceLoader : NSObject
{
    NSString *_directory;
    NSString *_additionalDirectoryToConsider;
    NSMutableArray *_resourcesToLoad;
    CDUnknownBlockType _completionHandler;
    CDUnknownBlockType _progressHandler;
    int _numberOfDownloadsInProgress;
    int _numberOfCopiesInProgress;
    NSMutableArray *_loadedResources;
    BOOL _canceled;
    NSString *_baseURLString;
    unsigned int _maxConcurrentLoads;
    NSArray *_resourceInfos;
    long _queuePriority;
}

- (void)_loadResourceFromNetwork:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)_writeResourceToDisk:(id)arg1 withData:(id)arg2 orExistingPathOnDisk:(id)arg3 allowCreatingHardLink:(BOOL)arg4 checksum:(id)arg5 completionHandler:(CDUnknownBlockType)arg6;
- (BOOL)_establishHardLinkIfPossibleForResource:(id)arg1 toResource:(id)arg2 error:(id *)arg3;
- (id)_urlForResource:(id)arg1;
- (void)_loadNextResource;
- (void)startWithProgressHandler:(CDUnknownBlockType)arg1 completionHandler:(CDUnknownBlockType)arg2 priority:(long)arg3;
@property(readonly, nonatomic) NSArray *loadedResources; // @synthesize loadedResources=_loadedResources;
- (id)initWithTargetDirectory:(id)arg1 baseURLString:(id)arg2 resources:(id)arg3 maximumConcurrentLoads:(unsigned int)arg4 additionalDirectoryToConsider:(id)arg5;
- (void)_cleanup;
- (void)dealloc;
- (void)cancel;

@end

