//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSLock, NSString;

@interface GEOUserSession : NSObject
{
    double _sessionCreationTime;
    double _usageSessionIDGenerationTime;
    CDStruct_612aec5b _sessionID;
    NSString *_sessionIDString;
    CDStruct_612aec5b _usageCollectionSessionID;
    unsigned int _sequenceNumber;
    NSLock *_lock;
}

+ (void)setIsGeod;
+ (id)sharedInstance;
@property(readonly) double sessionCreationTime;
@property(readonly) CDStruct_612aec5b usageCollectionSessionID;
@property(readonly) NSString *sessionIDString;
- (void)_safe_renewUsageCollectionSessionID;
- (void)_updateSessionID;
- (void)_setDefault:(id)arg1 forKey:(id)arg2;
- (void)_updateWithNewUUIDForSessionID:(CDStruct_612aec5b *)arg1;
- (void)_renewUsageCollectionSessionID;
- (id)_defaultForKey:(id)arg1;
@property(readonly) unsigned int sequenceNumber;
@property(readonly) CDStruct_612aec5b sessionID;
- (id)init;
- (void)dealloc;

@end

