//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CoreDAVSubmittable.h"

@class CoreDAVErrorItem, CoreDAVRequestLogger, NSData, NSDate, NSDictionary, NSError, NSHTTPURLResponse, NSMutableArray, NSMutableDictionary, NSString, NSURL, NSURLConnection, NSURLRequest;

@interface CoreDAVTask : NSObject <CoreDAVSubmittable>
{
    id <CoreDAVTaskManager> _taskManager;
    id <CoreDAVAccountInfoProvider> _accountInfoProvider;
    int _numDownloadedElements;
    int _depth;
    NSHTTPURLResponse *_response;
    NSURLConnection *_connection;
    NSURLRequest *_request;
    double _timeoutInterval;
    int _responseStatusCode;
    NSDate *_dateConnectionWentOut;
    BOOL _didSendRequest;
    BOOL _didFailWithError;
    BOOL _didCancel;
    BOOL _didReceiveResponse;
    BOOL _didReceiveData;
    BOOL _didFinishLoading;
    BOOL _finished;
    id _context;
    BOOL _receivedBadPasswordResponse;
    BOOL _justTriedTokenAuth;
    BOOL _everTriedTokenAuth;
    BOOL _shouldRetryWithClientToken;
    BOOL _didRetryWithClientToken;
    BOOL _requestIsCompressed;
    BOOL _compressedRequestFailed;
    NSError *_passwordNotificationError;
    id <CoreDAVResponseBodyParser> _responseBodyParser;
    CoreDAVRequestLogger *_logger;
    NSURL *_url;
    BOOL _allowAutomaticRedirects;
    id <CoreDAVTaskDelegate> _delegate;
    CDUnknownBlockType _requestProgressBlock;
    CDUnknownBlockType _responseProgressBlock;
    CDUnknownBlockType _completionBlock;
    NSError *_error;
    unsigned int _totalBytesReceived;
    NSMutableDictionary *_overriddenHeaders;
    NSMutableArray *_redirectHistory;
    NSDictionary *_requestProperties;
    NSData *_fakeResponseData;
    BOOL _haveParsedFakeResponseData;
    CoreDAVErrorItem *_forbiddenErrorItem;
    NSString *_uniqueID;
}

+ (id)stringFromDepth:(int)arg1;
+ (unsigned int)uniqueQueryID;
- (void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;
- (BOOL)connection:(id)arg1 canAuthenticateAgainstProtectionSpace:(id)arg2;
- (void)connection:(id)arg1 willSendRequestForAuthenticationChallenge:(id)arg2;
- (BOOL)connectionShouldUseCredentialStorage:(id)arg1;
@property(retain, nonatomic) NSDictionary *requestProperties; // @synthesize requestProperties=_requestProperties;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(nonatomic) int depth; // @synthesize depth=_depth;
- (unsigned int)cachePolicy;
- (id)_applyAuthenticationChain:(struct __CFArray *)arg1 toRequest:(id)arg2;
- (void)_failImmediately;
- (void)_handleBadPasswordResponse;
- (void)tearDownResources;
- (id)_requestForLogging;
- (id)_connectionForLogging;
- (id)httpMethod;
- (void)reportStatusWithError:(id)arg1;
- (int)numDownloadedElements;
@property(nonatomic) id <CoreDAVTaskManager> taskManager; // @synthesize taskManager=_taskManager;
- (void)startModal;
- (id)requestBody;
- (void)overrideRequestHeader:(id)arg1 withValue:(id)arg2;
@property(nonatomic) int responseStatusCode; // @synthesize responseStatusCode=_responseStatusCode;
- (id)credentialForOAuthChallenge:(id)arg1;
@property(nonatomic) BOOL allowAutomaticRedirects; // @synthesize allowAutomaticRedirects=_allowAutomaticRedirects;
- (BOOL)_shouldHandleStatusCode:(int)arg1;
- (BOOL)shouldLogResponseBody;
@property(copy, nonatomic) CDUnknownBlockType responseProgressBlock; // @synthesize responseProgressBlock=_responseProgressBlock;
@property(nonatomic) unsigned int totalBytesReceived; // @synthesize totalBytesReceived=_totalBytesReceived;
@property(copy, nonatomic) CDUnknownBlockType requestProgressBlock; // @synthesize requestProgressBlock=_requestProgressBlock;
- (void)handleWebLoginRequestWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)_sendTimeSpentInNetworkingToProvider;
- (id)_applyStorageSession:(struct __CFURLStorageSession *)arg1 toRequest:(id)arg2;
- (BOOL)_includeGeneralHeaders;
- (id)_createBodyData;
- (id)_compressBodyData:(id)arg1;
@property(retain, nonatomic) id <CoreDAVResponseBodyParser> responseBodyParser; // @synthesize responseBodyParser=_responseBodyParser;
- (void)performCoreDAVTask;
- (id)requestBodyStream;
- (id)lastRedirectURL;
@property(readonly, nonatomic) NSDictionary *responseHeaders;
- (id)additionalHeaderValues;
- (id)copyDefaultParserForContentType:(id)arg1;
- (void)finishEarlyWithError:(id)arg1;
- (void)submitWithTaskManager:(id)arg1;
- (void)finishCoreDAVTaskWithError:(id)arg1;
@property(nonatomic) id <CoreDAVAccountInfoProvider> accountInfoProvider; // @synthesize accountInfoProvider=_accountInfoProvider;
@property(readonly, nonatomic, getter=isFinished) BOOL finished;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)loadRequest:(id)arg1;
- (void)reset;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
- (id)initWithURL:(id)arg1;
@property(retain, nonatomic) id context; // @synthesize context=_context;
@property(readonly, nonatomic) NSURL *url; // @synthesize url=_url;
@property(nonatomic) id <CoreDAVTaskDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (BOOL)validate:(id *)arg1;
- (id)connection:(id)arg1 needNewBodyStream:(id)arg2;
- (void)connection:(id)arg1 didSendBodyData:(int)arg2 totalBytesWritten:(int)arg3 totalBytesExpectedToWrite:(int)arg4;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
@property(nonatomic) double timeoutInterval; // @synthesize timeoutInterval=_timeoutInterval;
- (BOOL)markAsFinished;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

