//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AVFoundation/AVMetadataItem.h>

@class AVMutableMetadataItemInternal, NSDictionary, NSLocale, NSString;

@interface AVMutableMetadataItem : AVMetadataItem
{
    AVMutableMetadataItemInternal *_mutablePriv;
}

+ (id)keyPathsForValuesAffectingIdentifier;
+ (id)metadataItem;
- (id)keySpace;
@property(copy) NSString *extendedLanguageTag;
- (void)setKeySpace:(id)arg1;
@property(copy) NSDictionary *extraAttributes;
- (void)setKey:(id)arg1;
- (id)key;
@property(copy) NSLocale *locale;
@property CDStruct_1b6d18a9 time;
@property(copy) NSString *identifier;
@property(copy) id <NSObject><NSCopying> value;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property CDStruct_1b6d18a9 duration;
@property(copy) NSString *dataType;

@end

