//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSValue.h"

@interface CMTimeAsValue : NSValue
{
    CDStruct_1b6d18a9 _time;
}

+ (id)valueWithCMTime:(CDStruct_1b6d18a9)arg1;
- (CDStruct_1b6d18a9)CMTimeValue;
- (long)longValue;
- (short)shortValue;
- (BOOL)charValue;
- (unsigned char)unsignedCharValue;
- (unsigned long)unsignedLongValue;
- (unsigned long long)unsignedLongLongValue;
- (const char *)objCType;
- (unsigned int)unsignedIntValue;
- (long long)longLongValue;
- (unsigned int)unsignedIntegerValue;
- (float)floatValue;
- (void)getValue:(void *)arg1;
- (int)integerValue;
- (double)doubleValue;
- (id)description;
- (BOOL)boolValue;
- (int)intValue;
- (unsigned short)unsignedShortValue;

@end

